# Rerun PoET-2 on 4 different zero-shot tasks

## Define the directories and input

In [1]:
import pandas as pd
from os.path import exists
from os import chdir
import glob
import sys
import os
from scipy.stats import spearmanr,linregress
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.metrics import roc_auc_score

chdir("/n/groups/marks/projects/marks_lab_and_oatml/ProteinGym2/")

dms_subs_ref_df = pd.read_csv("ProteinGym/reference_files/DMS_substitutions.csv")
dms_indels_ref_df = pd.read_csv("ProteinGym/reference_files/DMS_indels.csv")
clinical_subs_ref_df = pd.read_csv("ProteinGym/reference_files/clinical_substitutions.csv")
clinical_indels_ref_df = pd.read_csv("ProteinGym/reference_files/clinical_indels.csv")

dms_subs_output_dir = './PR/.cache/ProteinGym/zero_shot_substitutions_scores/PoET-2/'
dms_subs_dms_dir = "./PR/.cache/ProteinGym/DMS_ProteinGym_substitutions/"
dms_indels_output_dir = './PR/.cache/ProteinGym/zero_shot_indels_scores/PoET-2/'
dms_indels_dms_dir = "./PR/.cache/ProteinGym/DMS_ProteinGym_indels/"

clinical_subs_output_dir = './PR/.cache/ProteinGym/zero_shot_clinical_substitutions_scores/PoET-2'
clinical_subs_dms_dir = "./PR/.cache/ProteinGym/clinical_ProteinGym_substitutions"
clinical_indels_output_dir = "./PR/.cache/ProteinGym/zero_shot_clinical_indels_scores/PoET-2"
clinical_indels_dms_dir = "./PR/.cache/ProteinGym/clinical_ProteinGym_indels"

In [2]:
model_dict = {
    "model_list_zero_shot_substitutions_DMS": {
        "PoET-2": {"input_score_name": "PoET-2","location":"PoET-2","directionality":1,"key":"mutated_sequence","model_type":"Structure & MSA"}
    },
    "model_list_zero_shot_indels_DMS": {
        "PoET-2": {"input_score_name": "PoET-2","location":"PoET-2","directionality":1,"key":"mutated_sequence","model_type":"Structure & MSA"}
    },
    "model_list_zero_shot_substitutions_clinical": {
        "PoET-2": {"input_score_name": "PoET-2","location":"PoET-2","directionality":1,"key":"mutated_sequence","model_type":"Structure & MSA"}
    },
    "model_list_zero_shot_indels_clinical": {
        "PoET-2": {"input_score_name": "PoET-2","location":"PoET-2","directionality":1,"key":"mutated_sequence","model_type":"Structure & MSA"},
#         "PoET": {"input_score_name": "PoET_score","location":"PoET","directionality":1,"key":"mutated_sequence","model_type":"Structure & MSA"},
#         "Provean": {
#             "input_score_name": "provean_score",
#             "location": "Provean",
#             "directionality": 1,
#             "key": "mutated_sequence",
#             "model_type": "MSA"
#         },
    },
}

## Define the shared functions
Estimate runtime

In [54]:
def estimate_runtime_dms_subs(test_cost, test_time, unit="hours", ref_df=dms_subs_ref_df):
    ref_df["proxy_cost"] = ref_df["DMS_total_number_mutants"] * ref_df["seq_len"]
    ref_df[f"estimated_{unit}"] = ref_df["proxy_cost"] / test_cost * test_time
    ref_df = ref_df.reset_index()
    print(ref_df[["index","DMS_id",f"estimated_{unit}"]]
          .sort_values(f"estimated_{unit}", ascending=False)
          .head(20)
         )
    return ref_df


def estimate_runtime_dms_indels(test_cost, test_time, unit="min", ref_df=dms_indels_ref_df):
    ref_df["proxy_cost"] = ref_df["DMS_total_number_mutants"]
    ref_df[f"estimated_{unit}"] = ref_df["proxy_cost"] / test_cost * test_time
    ref_df = ref_df.reset_index()
    print(ref_df[["index","DMS_id",f"estimated_{unit}"]]
          .sort_values(f"estimated_{unit}", ascending=False)
          .head(20)
         )
    return ref_df


def estimate_runtime_clinical_subs(test_cost, test_time, unit="min", 
                                   ref_df=clinical_subs_ref_df, clinical_sub_dir=clinical_subs_dms_dir):

    def calculate_total_number_mutants(DMS_id, clinical_sub_dir=clinical_sub_dir):
        return len(pd.read_csv(f"{clinical_sub_dir}/{DMS_id}.csv", sep=","))
    ref_df["total_number_mutants"] = ref_df['DMS_id'].map(calculate_total_number_mutants)
    ref_df["proxy_cost"] = ref_df["total_number_mutants"]
    ref_df[f"estimated_{unit}"] = ref_df["proxy_cost"] / test_cost * test_time
    ref_df = ref_df.reset_index()
    print(ref_df[["index","DMS_id","total_number_mutants", f"estimated_{unit}"]]
          .sort_values(f"estimated_{unit}", ascending=False)
          .head(20)
         )
    return ref_df


def estimate_runtime_clinical_indels(test_cost, test_time, unit="min", 
                                     ref_df=clinical_indels_ref_df, clinical_indel_dir=clinical_indels_dms_dir):

    def calculate_total_number_mutants(DMS_id, clinical_indel_dir=clinical_indel_dir):
        return len(pd.read_csv(f"{clinical_indel_dir}/{DMS_id}.csv", sep=","))
    ref_df["total_number_mutants"] = ref_df['DMS_id'].map(calculate_total_number_mutants)
    ref_df["proxy_cost"] = ref_df["total_number_mutants"]
    ref_df[f"estimated_{unit}"] = ref_df["proxy_cost"] / test_cost * test_time
    ref_df = ref_df.reset_index()
    print(ref_df[["index","DMS_id","total_number_mutants", f"estimated_{unit}"]]
          .sort_values(f"estimated_{unit}", ascending=False)
          .head(20)
         )
    return ref_df

Check runs

In [55]:
def check_runs(ref_df, output_dir):
    num_finished = 0
    index_unfinished = []
    for index, row in ref_df.iterrows():
        score_csv = output_dir + '/' + row['DMS_id'] + '.csv'
        if exists(score_csv):
            num_finished += 1
        else:
            index_unfinished.append(index)         

    if num_finished > 0:
        print(output_dir, index_unfinished, f"{len(index_unfinished)} unfinished")
        print(output_dir, f"{num_finished} finished")

Calculate Spearman and AUROC

In [56]:
def calc_spearman(ref_df, output_dir, dms_dir, model_dict_key):
    list_DMS = ref_df['DMS_id']
    model_list = model_dict[model_dict_key].keys()
    
    DMS_spearman = {'DMS_ID': [], 'number of mutants': []}

    for model in model_list:
        if model not in DMS_spearman:
            DMS_spearman[model] = np.full(shape=len(list_DMS), fill_value=np.nan)
        else:
            print(f"Duplicate model name {model}")

    for i, DMS_id in enumerate(list_DMS):
        print(DMS_id)
        DMS_spearman['DMS_ID'].append(DMS_id)

        DMS_file = dms_dir + os.sep + ref_df.iloc[i]["DMS_filename"]

        try:
            DMS_score = pd.read_csv(DMS_file)
            DMS_spearman['number of mutants'].append(len(DMS_score))
    #         print("DMS has entries: ", len(DMS_score))
        except:
            print(f"No DMS scores for {DMS_id}")
            DMS_spearman['number of mutants'].append(0)
            continue

        for model in model_list:
            try:
                model_score = pd.read_csv(output_dir + os.sep + DMS_id + ".csv")[[model]]
#                 model_score = pd.read_csv(output_dir + os.sep + model_dict[model_dict_key][model]["location"] + os.sep + DMS_id + ".csv")[[model]]
    #             print("PoET-2 has entries:", len(model_score))
            except:
                print(f"Scoring file for {DMS_id} in {model} missing")
                DMS_spearman[model][i] = np.nan # this line can be taken out later
                continue

            assert len(DMS_score) == len(model_score)
            result = pd.concat([DMS_score, model_score], axis=1)

            if 'DMS_score' in result.columns:
                DMS_spearman[model][i] = spearmanr(result['DMS_score'], result[model_dict[model_dict_key][model]["input_score_name"]]*model_dict[model_dict_key][model]["directionality"]).statistic
            elif model == "Site_Independent" or model == "EVmutation":
                DMS_spearman[model][i] = spearmanr(result['normalized_fitness'], result[model_dict[model_dict_key][model]["input_score_name"]]*model_dict[model_dict_key][model]["directionality"]).statistic            
            else:
                if model == "EVE_ensemble":
                    result['evol_indices_ensemble'] = result.drop('mutant', axis=1).mean(axis=1)
                merged_df = pd.merge(result, DMS_score, on=model_dict[model_dict_key][model]['key'], how='inner')
                DMS_spearman[model][i] = spearmanr(merged_df['DMS_score'], merged_df[model_dict[model_dict_key][model]["input_score_name"]]*model_dict[model_dict_key][model]["directionality"]).statistic
            
    return DMS_spearman


def build_performance_all_DMS(dms_spearman, ref_df, model_dict_key):
    """
    Convert per-assay Spearman values into the ProteinGym
    `performance_all_DMS['Spearman']` table:

        index   = DMS_id            (one row per assay)
        columns = [<one col per model>, 'number_mutants',
                   'UniProt_ID', 'Selection Type']

    so it can be fed straight into the 3-level groupby-mean averaging.
    Only UniProt_ID and Selection Type metadata are attached
    (no MSA_Neff_L_category / Taxon).
    """
    model_list = model_dict[model_dict_key].keys()
    # 1. per-assay spearman -> DataFrame, normalise id/count column names
    df = pd.DataFrame(dms_spearman) if isinstance(dms_spearman, dict) else dms_spearman.copy()
    df = df.rename(columns={'DMS_ID': 'DMS_id',
                            'number of mutants': 'number_mutants'})

    # 2. attach metadata from the reference file
    meta = ref_df[['DMS_id', 'UniProt_ID', 'coarse_selection_type']].rename(
        columns={'coarse_selection_type': 'Selection Type'})
    df = df.merge(meta, on='DMS_id', how='left')

    # 3. replace the missing-model sentinel (-1) with NaN so it is skipped
    #    by mean(numeric_only=True) at every averaging level
    model_cols = [m for m in model_list if m in df.columns]
    df[model_cols] = df[model_cols].replace(-1, np.nan)

    # 4. index by assay, order columns to mirror performance_all_DMS['Spearman']
    df = df.set_index('DMS_id')
    return df[model_cols + ['number_mutants', 'UniProt_ID', 'Selection Type']]


def average_across_assays(perf):
    """3-level nested mean: assays -> protein -> function category -> overall."""
    perf = perf.drop(columns=['number_mutants'])                       # not a metric
    per_protein  = perf.groupby(['UniProt_ID', 'Selection Type']).mean(numeric_only=True)
    per_function = per_protein.groupby('Selection Type').mean(numeric_only=True)
    return per_function.mean(numeric_only=True)                        # one value per model

Substitute for sklearn.roc_auc_score, shared by all auroc calculation functions (no longer using this)

In [57]:
def roc_auc_score(y_true, y_score):
    """
    AUROC = P(score(positive) > score(negative)), tie-corrected.
    Equivalent to sklearn.metrics.roc_auc_score for binary {0,1} labels.
    """
    y_true  = np.asarray(y_true)
    y_score = np.asarray(y_score)

    pos = (y_true == 1)
    n_pos = pos.sum()
    n_neg = (~pos).sum()
    if n_pos == 0 or n_neg == 0:
        return np.nan                       # AUROC undefined with one class

    ranks = rankdata(y_score)               # average ranks -> handles ties
    auc = (ranks[pos].sum() - n_pos * (n_pos + 1) / 2.0) / (n_pos * n_neg)
    return auc

In [21]:
def calc_auroc(ref_df, output_dir, clinical_dir, model_dict_key, label_col='DMS_bin_score'):
    """
    AUROC for clinical substitutions.
    `label_col` is the binary {0,1} ground-truth column in the clinical files
    (pathogenic = 1, benign = 0) -- set it to whatever your files use.
    """
    list_clin = ref_df['DMS_id']
    model_list = model_dict[model_dict_key].keys()

    clin_auroc = {'DMS_ID': [], 'number of variants': []}
    for model in model_list:
        if model not in clin_auroc:
            clin_auroc[model] = np.full(shape=len(list_clin), fill_value=np.nan)
        else:
            print(f"Duplicate model name {model}")

    for i, DMS_id in enumerate(list_clin):
        clin_auroc['DMS_ID'].append(DMS_id)

        clin_file = clinical_dir + os.sep + ref_df.iloc[i]["DMS_filename"]
        try:
            clin_labels = pd.read_csv(clin_file)
            clin_labels[label_col] = clin_labels[label_col].map({'Pathogenic': 0, 'Benign': 1})
            clin_auroc['number of variants'].append(len(clin_labels))
        except:
            print(f"No clinical labels for {DMS_id}")
            clin_auroc['number of variants'].append(0)
            continue

        for model in model_list:
            cfg = model_dict[model_dict_key][model]
            try:
                model_score = pd.read_csv(
                    output_dir + os.sep + DMS_id + ".csv")
            except:
                print(f"Scoring file for {DMS_id} in {model} missing")
                continue   # leave as NaN (not -1) so it is skipped in averaging

            # --- align labels with scores ---
            assert len(clin_labels) == len(model_score)
            merged = pd.concat([clin_labels.reset_index(drop=True),
                                model_score.reset_index(drop=True)], axis=1)
#             if cfg.get("key"):                       # per-mutant merge (e.g. EVE, EVmutation)
            if model == "EVE_ensemble":
                score_cols = [c for c in model_score.columns if c != cfg["key"]]
                model_score[cfg["input_score_name"]] = model_score[score_cols].mean(axis=1)
                merged = pd.merge(clin_labels, model_score, on=cfg["key"], how="inner")

            y_true  = merged[label_col]
            y_score = merged[cfg["input_score_name"]] * cfg["directionality"]

            # AUROC is undefined unless both classes are present and scores are finite
            valid = y_score.notna()
            if y_true[valid].nunique() < 2:
                print(f"Only one class for {DMS_id} in {model}; AUROC undefined")
                continue
            try:
                clin_auroc[model][i] = roc_auc_score(y_true=y_true[valid],
                                                     y_score=y_score[valid])
            except Exception as e:
                print(f"AUROC issue for {DMS_id} in {model}: {e}")

    return clin_auroc


def overall_auroc(clin_auroc, model_list, round_per_gene=True):
    """Official clinical-substitution aggregation: unweighted mean of per-gene AUCs."""
    df = pd.DataFrame(clin_auroc) if isinstance(clin_auroc, dict) else clin_auroc.copy()
    out = {}
    for model in model_list:
        aucs = df[model].dropna()                 # genes where AUC was computable
        if round_per_gene:
            aucs = aucs.round(3)                  # official rounds each gene first
        out[model] = round(aucs.mean(), 3) if len(aucs) else np.nan
    return pd.Series(out).sort_values(ascending=False)

Separately for substitutions (aggregate over genes) and indels (number of variants too small to aggregate meaningfully)

In [3]:
def compute_pooled_auc(gene_ids, model_dict_key, scores_folder, clinical_folder, label_col="DMS_score_bin"):
    """Pool all variants across genes, then compute a single AUC per model.
    Used for indels where per-gene sample sizes are too small.
    """
    pooled = []
    model_config = model_dict[model_dict_key]
    model_list = model_dict[model_dict_key].keys()
    clin_auroc = dict()
    for gene_id in gene_ids:
        score_file = os.path.join(scores_folder, f"{gene_id}.csv")
        if not os.path.exists(score_file):
            print(f"Missing score file for {gene_id}")
            continue

        score_df = pd.read_csv(score_file)
        if "PoET-2" not in score_df.columns:
            print(f"Missing score column for {gene_id}")
            continue
        
        clinical_file = os.path.join(clinical_folder, f"{gene_id}.csv")
        if not os.path.exists(clinical_file):
            print(f"Missing clinical file for {gene_id}")
            continue

        true_df = pd.read_csv(clinical_file)
        if label_col not in true_df.columns:
            print(f"Missing {label_col} column for {gene_id} in clinical file")
            continue
        
        true_df[label_col] = true_df[label_col].values
        # convert to binary labels if there are strings
        true_df[label_col] = [1 if val == "Pathogenic" else val for val in true_df[label_col]]
        true_df[label_col] = [0 if val == "Benign" else val for val in true_df[label_col]]
        # flip labels (since pathogenic should be less fit)
        true_df[label_col] = np.array(true_df[label_col])
        assert np.all((true_df[label_col] == 1) | (true_df[label_col] == 0)), "Labels contain NaNs"
        true_df[label_col] = 1 - true_df[label_col]
        
        assert len(true_df) == len(score_df), f"length mismatch for {gene_id}"
        merged = pd.concat([true_df[[label_col]].reset_index(drop=True),
                            score_df[['PoET-2']].reset_index(drop=True)], axis=1)
        pooled.append(merged)

    if not pooled:
        print("No data loaded!")
        return pd.Series(dtype=float)
    
    pooled = pd.concat(pooled, ignore_index=True)
    print(f"Pooled {len(pooled)} variants across {len(gene_ids)} genes")
    
    out = dict()
    for model in model_list:
        cfg = model_dict[model_dict_key][model]
        score_name = cfg["input_score_name"]
        if score_name not in pooled.columns:
            print(f"Missing score column '{score_name}' for {model}")
            out[model] = np.nan; continue

        y_true  = pooled[label_col]
        y_score = pooled[score_name] * cfg["directionality"]

        # AUROC is undefined unless both classes are present and scores are finite
#         valid = y_score.notna() & y_true.notna()
        valid = y_score.notna()
        if y_true[valid].nunique() < 2:
            print(f"Only one class in {model}; AUROC undefined")
            out[model] = np.nan
            continue
        try:
            out[model] = round(roc_auc_score(y_true=y_true[valid].values,
                                             y_score=y_score[valid].values), 3)
        except Exception as e:
            print(f"AUROC issue in {model}: {e}")
            out[model] = np.nan
                               
    return pd.Series(out).sort_values(ascending=False)

# DMS subs

## Estimate runtime

In [27]:
zika_cost = 32778648
zika_runtime_hours = 3.0
dms_subs_df = estimate_runtime_dms_subs(zika_cost, zika_runtime_hours)

     index                            DMS_id  estimated_hours
181    181             SPG1_STRSG_Olson_2014        22.016678
73      73         HIS7_YEAST_Pokusaeva_2019         9.989748
182    182                SPG1_STRSG_Wu_2016         6.124104
128    128      POLG_CXB3N_Mattenberger_2021         3.141850
0        0   A0A140D2T1_ZIKV_Sourisseau_2019         3.000000
28      28            CAPSD_AAV2S_Sinai_2021         2.847379
122    122           PABP_YEAST_Melamed_2013         1.991313
124    124              PHOT_CHLRE_Chen_2023         1.809265
97      97               MSH2_HUMAN_Jia_2020         1.431746
129    129       POLG_DEN26_Suphatrakul_2023         1.391818
74      74             HMDH_HUMAN_Jiang_2019         1.369684
69      69             GRB2_HUMAN_Faure_2021         1.258480
67      67          GFP_AEQVI_Sarkisyan_2016         1.126459
6        6               A4_HUMAN_Seuma_2022         1.043771
31      31  CAS9_STRP1_Spencer_2017_positive         1.016276
55      55             ENV_HV1BR_Haddox_2016         1.013621
139    139          Q2N0S5_9HIV1_Haddox_2018         1.001897
7        7             A4D664_9INFA_Soh_2019         1.001768
1        1      A0A192B1T2_9HIV1_Haddox_2018         0.980724
76      76            HSP82_YEAST_Flynn_2019         0.862645

In [28]:
len(dms_subs_df)

217

## Check runs finished

In [44]:
check_runs(dms_subs_ref_df, dms_subs_output_dir)

217
./PR/.cache/ProteinGym/zero_shot_substitutions_scores/PoET-2/ []
./PR/.cache/ProteinGym/zero_shot_substitutions_scores/PoET-2/ 217

## Calculate Spearman

In [83]:
dms_subs_spearman = calc_spearman(dms_subs_ref_df, dms_subs_output_dir, dms_subs_dms_dir, "model_list_zero_shot_substitutions_DMS")

A0A140D2T1_ZIKV_Sourisseau_2019
A0A192B1T2_9HIV1_Haddox_2018
A0A1I9GEU1_NEIME_Kennouche_2019
A0A247D711_LISMN_Stadelmann_2021
A0A2Z5U3Z0_9INFA_Doud_2016
A0A2Z5U3Z0_9INFA_Wu_2014
A4_HUMAN_Seuma_2022
A4D664_9INFA_Soh_2019
A4GRB6_PSEAI_Chen_2020
AACC1_PSEAI_Dandage_2018
ACE2_HUMAN_Chan_2020
ADRB2_HUMAN_Jones_2020
AICDA_HUMAN_Gajula_2014_3cycles
AMFR_HUMAN_Tsuboyama_2023_4G3O
AMIE_PSEAE_Wrenbeck_2017
ANCSZ_Hobbs_2022
ARGR_ECOLI_Tsuboyama_2023_1AOY
B2L11_HUMAN_Dutta_2010_binding-Mcl-1
BBC1_YEAST_Tsuboyama_2023_1TG0
BCHB_CHLTE_Tsuboyama_2023_2KRU
BLAT_ECOLX_Deng_2012
BLAT_ECOLX_Firnberg_2014
BLAT_ECOLX_Jacquier_2013
BLAT_ECOLX_Stiffler_2015
BRCA1_HUMAN_Findlay_2018
BRCA2_HUMAN_Erwood_2022_HEK293T
C6KNH7_9INFA_Lee_2018
CALM1_HUMAN_Weile_2017
CAPSD_AAV2S_Sinai_2021
CAR11_HUMAN_Meitlis_2020_gof
CAR11_HUMAN_Meitlis_2020_lof
CAS9_STRP1_Spencer_2017_positive
CASP3_HUMAN_Roychowdhury_2020
CASP7_HUMAN_Roychowdhury_2020
CATR_CHLRE_Tsuboyama_2023_2AMI
CBPA2_HUMAN_Tsuboyama_2023_1O6X
CBS_HUMAN_Sun_2020
CBX4_HUMAN_Tsuboyama_2023_2K28
CCDB_ECOLI_Adkar_2012
CCDB_ECOLI_Tripathi_2016
CCR5_HUMAN_Gill_2023
CD19_HUMAN_Klesmith_2019_FMC_singles
CP2C9_HUMAN_Amorosi_2021_abundance
CP2C9_HUMAN_Amorosi_2021_activity
CSN4_MOUSE_Tsuboyama_2023_1UFM
CUE1_YEAST_Tsuboyama_2023_2MYX
D7PM05_CLYGR_Somermeyer_2022
DLG4_HUMAN_Faure_2021
DLG4_RAT_McLaughlin_2012
DN7A_SACS2_Tsuboyama_2023_1JIC
DNJA1_HUMAN_Tsuboyama_2023_2LO1
DOCK1_MOUSE_Tsuboyama_2023_2M0Y
DYR_ECOLI_Nguyen_2023
DYR_ECOLI_Thompson_2019
ENV_HV1B9_DuenasDecamp_2016
ENV_HV1BR_Haddox_2016
ENVZ_ECOLI_Ghose_2023
EPHB2_HUMAN_Tsuboyama_2023_1F0M
ERBB2_HUMAN_Elazar_2016
ESTA_BACSU_Nutschel_2020
F7YBW8_MESOW_Ding_2023
F7YBW8_MESOW_Aakre_2015
FECA_ECOLI_Tsuboyama_2023_2D1U
FKBP3_HUMAN_Tsuboyama_2023_2KFV
GAL4_YEAST_Kitzman_2015
GCN4_YEAST_Staller_2018
GDIA_HUMAN_Silverstein_2021
GFP_AEQVI_Sarkisyan_2016
GLPA_HUMAN_Elazar_2016
GRB2_HUMAN_Faure_2021
HCP_LAMBD_Tsuboyama_2023_2L6Q
HECD1_HUMAN_Tsuboyama_2023_3DKM
HEM3_HUMAN_Loggerenberg_2023
HIS7_YEAST_Pokusaeva_2019
HMDH_HUMAN_Jiang_2019
HSP82_YEAST_Cote-Hammarlof_2020_growth-H2O2
HSP82_YEAST_Flynn_2019
HSP82_YEAST_Mishra_2016
HXK4_HUMAN_Gersing_2022_activity
HXK4_HUMAN_Gersing_2023_abundance
I6TAH8_I68A0_Doud_2015
IF1_ECOLI_Kelsic_2016
ILF3_HUMAN_Tsuboyama_2023_2L33
ISDH_STAAW_Tsuboyama_2023_2LHR
KCNE1_HUMAN_Muhammad_2023_expression
KCNE1_HUMAN_Muhammad_2023_function
KCNH2_HUMAN_Kozek_2020
KCNJ2_MOUSE_Coyote-Maestas_2022_function
KCNJ2_MOUSE_Coyote-Maestas_2022_surface
KKA2_KLEPN_Melnikov_2014
LGK_LIPST_Klesmith_2015
LYAM1_HUMAN_Elazar_2016
MAFG_MOUSE_Tsuboyama_2023_1K1V
MBD11_ARATH_Tsuboyama_2023_6ACV
MET_HUMAN_Estevam_2023
MK01_HUMAN_Brenan_2016
MLAC_ECOLI_MacRae_2023
MSH2_HUMAN_Jia_2020
MTH3_HAEAE_RockahShmuel_2015
MTHR_HUMAN_Weile_2021
MYO3_YEAST_Tsuboyama_2023_2BTT
NCAP_I34A1_Doud_2015
NKX31_HUMAN_Tsuboyama_2023_2L9R
NPC1_HUMAN_Erwood_2022_HEK293T
NPC1_HUMAN_Erwood_2022_RPE1
NRAM_I33A0_Jiang_2016
NUD15_HUMAN_Suiter_2020
NUSA_ECOLI_Tsuboyama_2023_1WCL
NUSG_MYCTU_Tsuboyama_2023_2MI6
OBSCN_HUMAN_Tsuboyama_2023_1V1C
ODP2_GEOSE_Tsuboyama_2023_1W4G
OPSD_HUMAN_Wan_2019
OTC_HUMAN_Lo_2023
OTU7A_HUMAN_Tsuboyama_2023_2L2D
OXDA_RHOTO_Vanella_2023_activity
OXDA_RHOTO_Vanella_2023_expression
P53_HUMAN_Giacomelli_2018_Null_Etoposide
P53_HUMAN_Giacomelli_2018_Null_Nutlin
P53_HUMAN_Giacomelli_2018_WT_Nutlin
P53_HUMAN_Kotler_2018
P84126_THETH_Chan_2017
PA_I34A1_Wu_2015
PABP_YEAST_Melamed_2013
PAI1_HUMAN_Huttinger_2021
PHOT_CHLRE_Chen_2023
PIN1_HUMAN_Tsuboyama_2023_1I6C
PITX2_HUMAN_Tsuboyama_2023_2L7M
PKN1_HUMAN_Tsuboyama_2023_1URF
POLG_CXB3N_Mattenberger_2021
POLG_DEN26_Suphatrakul_2023
POLG_HCVJF_Qi_2014
POLG_PESV_Tsuboyama_2023_2MXD
PPARG_HUMAN_Majithia_2016
PPM1D_HUMAN_Miller_2022
PR40A_HUMAN_Tsuboyama_2023_1UZC
PRKN_HUMAN_Clausen_2023
PSAE_PICP2_Tsuboyama_2023_1PSE
PTEN_HUMAN_Matreyek_2021
PTEN_HUMAN_Mighell_2018
Q2N0S5_9HIV1_Haddox_2018
Q53Z42_HUMAN_McShan_2019_binding-TAPBPR
Q53Z42_HUMAN_McShan_2019_expression
Q59976_STRSQ_Romero_2015
Q6WV12_9MAXI_Somermeyer_2022
Q837P4_ENTFA_Meier_2023
Q837P5_ENTFA_Meier_2023
Q8WTC7_9CNID_Somermeyer_2022
R1AB_SARS2_Flynn_2022
RAD_ANTMA_Tsuboyama_2023_2CJJ
RAF1_HUMAN_Zinkus-Boltz_2019
RASH_HUMAN_Bandaru_2017
RASK_HUMAN_Weng_2022_abundance
RASK_HUMAN_Weng_2022_binding-DARPin_K55
RBP1_HUMAN_Tsuboyama_2023_2KWH
RCD1_ARATH_Tsuboyama_2023_5OAO
RCRO_LAMBD_Tsuboyama_2023_1ORC
RD23A_HUMAN_Tsuboyama_2023_1IFY
RDRP_I33A0_Li_2023
REV_HV1H2_Fernandes_2016
RFAH_ECOLI_Tsuboyama_2023_2LCL
RL20_AQUAE_Tsuboyama_2023_1GYZ
RL40A_YEAST_Mavor_2016
RL40A_YEAST_Roscoe_2013
RL40A_YEAST_Roscoe_2014
RNC_ECOLI_Weeks_2023
RPC1_BP434_Tsuboyama_2023_1R69
RPC1_LAMBD_Li_2019_high-expression
RPC1_LAMBD_Li_2019_low-expression
RS15_GEOSE_Tsuboyama_2023_1A32
S22A1_HUMAN_Yee_2023_abundance
S22A1_HUMAN_Yee_2023_activity
SAV1_MOUSE_Tsuboyama_2023_2YSB
SBI_STAAM_Tsuboyama_2023_2JVG
SC6A4_HUMAN_Young_2021
SCIN_STAAR_Tsuboyama_2023_2QFF
SCN5A_HUMAN_Glazer_2019
SDA_BACSU_Tsuboyama_2023_1PV0
SERC_HUMAN_Xie_2023
SHOC2_HUMAN_Kwon_2022
SOX30_HUMAN_Tsuboyama_2023_7JJK
SPA_STAAU_Tsuboyama_2023_1LP1
SPG1_STRSG_Olson_2014
SPG1_STRSG_Wu_2016
SPG2_STRSG_Tsuboyama_2023_5UBS
SPIKE_SARS2_Starr_2020_binding
SPIKE_SARS2_Starr_2020_expression
SPTN1_CHICK_Tsuboyama_2023_1TUD
SQSTM_MOUSE_Tsuboyama_2023_2RRU
SR43C_ARATH_Tsuboyama_2023_2N88
SRBS1_HUMAN_Tsuboyama_2023_2O2W
SRC_HUMAN_Ahler_2019
SRC_HUMAN_Chakraborty_2023_binding-DAS_25uM
SRC_HUMAN_Nguyen_2022
SUMO1_HUMAN_Weile_2017
SYUA_HUMAN_Newberry_2020
TADBP_HUMAN_Bolognesi_2019
TAT_HV1BR_Fernandes_2016
TCRG1_MOUSE_Tsuboyama_2023_1E0L
THO1_YEAST_Tsuboyama_2023_2WQG
TNKS2_HUMAN_Tsuboyama_2023_5JRT
TPK1_HUMAN_Weile_2017
TPMT_HUMAN_Matreyek_2018
TPOR_HUMAN_Bridgford_2020
TRPC_SACS2_Chan_2017
TRPC_THEMA_Chan_2017
UBC9_HUMAN_Weile_2017
UBE4B_HUMAN_Tsuboyama_2023_3L1X
UBE4B_MOUSE_Starita_2013
UBR5_HUMAN_Tsuboyama_2023_1I2T
VG08_BPP22_Tsuboyama_2023_2GP8
VILI_CHICK_Tsuboyama_2023_1YU5
VKOR1_HUMAN_Chiasson_2020_abundance
VKOR1_HUMAN_Chiasson_2020_activity
VRPI_BPT7_Tsuboyama_2023_2WNM
YAIA_ECOLI_Tsuboyama_2023_2KVT
YAP1_HUMAN_Araya_2012
YNZC_BACSU_Tsuboyama_2023_2JVD

In [84]:
dms_subs_spearman.keys()

dict_keys(['DMS_ID', 'number of mutants', 'PoET-2'])

In [91]:
dms_subs_perf = build_performance_all_DMS(dms_subs_spearman, dms_subs_ref_df, "model_list_zero_shot_substitutions_DMS")
dms_subs_leaderboard = average_across_assays(dms_subs_perf).sort_values(ascending=False)
print(dms_subs_leaderboard)

PoET-2    0.500141
dtype: float64

In [86]:
len(dms_subs_spearman['DMS_ID'])

217

In [87]:
dms_subs_spearman['PoET-2']

array([0.4654173 , 0.49981055, 0.02942379, 0.54325031, 0.60054724,
       0.56368136, 0.40032339, 0.38857022, 0.73920917, 0.52508455,
       0.27909446, 0.5513496 , 0.45951355, 0.35285138, 0.6415395 ,
       0.61182726, 0.58639299, 0.40883849, 0.52611437, 0.51560449,
       0.5507582 , 0.76295805, 0.71496152, 0.7589067 , 0.57461511,
       0.43498884, 0.47255988, 0.24921442, 0.57057537, 0.34600688,
       0.51516666, 0.19380037, 0.63869412, 0.64962204, 0.67843703,
       0.79627836, 0.37571409, 0.74026488, 0.48397551, 0.55861699,
       0.35200566, 0.3129669 , 0.66120122, 0.71039203, 0.61378154,
       0.62157748, 0.68591186, 0.7238249 , 0.54254705, 0.47811423,
       0.81547185, 0.5217321 , 0.50983376, 0.46734614, 0.40440058,
       0.34207421, 0.20238294, 0.79981439, 0.57168708, 0.41810324,
       0.57056208, 0.41844762, 0.57066311, 0.40459642, 0.53877755,
       0.21403597, 0.47273213, 0.75377826, 0.40393965, 0.626085  ,
       0.67027183, 0.42354651, 0.4497878 , 0.59106765, 0.45831482,
       0.36421786, 0.36746564, 0.44649784, 0.50354167, 0.43795454,
       0.38851616, 0.58682685, 0.47695686, 0.3589023 , 0.07994373,
       0.56723121, 0.43413785, 0.3677724 , 0.36254125, 0.65696222,
       0.49858263, 0.36754929, 0.61902374, 0.82233405, 0.5523249 ,
       0.16128968, 0.37174996, 0.4017721 , 0.67515616, 0.31546036,
       0.5046642 , 0.46386995, 0.65310362, 0.7231575 , 0.60920699,
       0.66252092, 0.68431848, 0.59998293, 0.59671755, 0.80592832,
       0.20191003, 0.59364465, 0.62908222, 0.64536096, 0.38236597,
       0.38216142, 0.47905048, 0.44245951, 0.46824837, 0.71671903,
       0.61931927, 0.58255097, 0.70520416, 0.47229869, 0.71968896,
       0.71696942, 0.62153134, 0.38369367, 0.48090663, 0.66678936,
       0.73460961, 0.67400377, 0.61511725, 0.63421333, 0.86344824,
       0.71800196, 0.60215915, 0.50226542, 0.55859495, 0.55415362,
       0.3717699 , 0.61204898, 0.63186379, 0.4559093 , 0.43955382,
       0.36949637, 0.36880234, 0.67114148, 0.49467051, 0.34062881,
       0.51875048, 0.33363083, 0.69350791, 0.36832826, 0.53213415,
       0.66421047, 0.55988539, 0.56983766, 0.31817724, 0.3122595 ,
       0.71820209, 0.39973718, 0.46674289, 0.4668049 , 0.61537644,
       0.77916965, 0.49648907, 0.4685656 , 0.48952007, 0.64376401,
       0.57927585, 0.59017373, 0.4965019 , 0.57647409, 0.3464218 ,
       0.10295704, 0.58664052, 0.56750087, 0.3402051 , 0.43930723,
       0.58889515, 0.40410785, 0.17323407, 0.6035419 , 0.47401305,
       0.61021495, 0.67311885, 0.68337695, 0.74878158, 0.69762283,
       0.51311765, 0.41538846, 0.40688505, 0.54188712, 0.09435588,
       0.10965668, 0.36718651, 0.79066746, 0.58257262, 0.62799368,
       0.29747901, 0.57350414, 0.45675023, 0.61325693, 0.49089423,
       0.54343937, 0.49183577, 0.43775459, 0.65001888, 0.37439168,
       0.65874731, 0.5254675 , 0.43833665, 0.52259829, 0.62397362,
       0.44510604, 0.66426116])

Compare with authors' spearman

In [70]:
author_dir = './PR/proteingym_v1.3_zero_shot_substitutions_scores_poet_2_afdb_v6'

author_dms_subs_spearman = calc_spearman(dms_subs_ref_df, author_dir, dms_subs_dms_dir, "model_list_zero_shot_substitutions_DMS")

A0A140D2T1_ZIKV_Sourisseau_2019
A0A192B1T2_9HIV1_Haddox_2018
A0A1I9GEU1_NEIME_Kennouche_2019
A0A247D711_LISMN_Stadelmann_2021
A0A2Z5U3Z0_9INFA_Doud_2016
A0A2Z5U3Z0_9INFA_Wu_2014
A4_HUMAN_Seuma_2022
A4D664_9INFA_Soh_2019
A4GRB6_PSEAI_Chen_2020
AACC1_PSEAI_Dandage_2018
ACE2_HUMAN_Chan_2020
ADRB2_HUMAN_Jones_2020
AICDA_HUMAN_Gajula_2014_3cycles
AMFR_HUMAN_Tsuboyama_2023_4G3O
AMIE_PSEAE_Wrenbeck_2017
ANCSZ_Hobbs_2022
ARGR_ECOLI_Tsuboyama_2023_1AOY
B2L11_HUMAN_Dutta_2010_binding-Mcl-1
BBC1_YEAST_Tsuboyama_2023_1TG0
BCHB_CHLTE_Tsuboyama_2023_2KRU
BLAT_ECOLX_Deng_2012
BLAT_ECOLX_Firnberg_2014
BLAT_ECOLX_Jacquier_2013
BLAT_ECOLX_Stiffler_2015
BRCA1_HUMAN_Findlay_2018
BRCA2_HUMAN_Erwood_2022_HEK293T
C6KNH7_9INFA_Lee_2018
CALM1_HUMAN_Weile_2017
CAPSD_AAV2S_Sinai_2021
CAR11_HUMAN_Meitlis_2020_gof
CAR11_HUMAN_Meitlis_2020_lof
CAS9_STRP1_Spencer_2017_positive
CASP3_HUMAN_Roychowdhury_2020
CASP7_HUMAN_Roychowdhury_2020
CATR_CHLRE_Tsuboyama_2023_2AMI
CBPA2_HUMAN_Tsuboyama_2023_1O6X
CBS_HUMAN_Sun_2020
CBX4_HUMAN_Tsuboyama_2023_2K28
CCDB_ECOLI_Adkar_2012
CCDB_ECOLI_Tripathi_2016
CCR5_HUMAN_Gill_2023
CD19_HUMAN_Klesmith_2019_FMC_singles
CP2C9_HUMAN_Amorosi_2021_abundance
CP2C9_HUMAN_Amorosi_2021_activity
CSN4_MOUSE_Tsuboyama_2023_1UFM
CUE1_YEAST_Tsuboyama_2023_2MYX
D7PM05_CLYGR_Somermeyer_2022
DLG4_HUMAN_Faure_2021
DLG4_RAT_McLaughlin_2012
DN7A_SACS2_Tsuboyama_2023_1JIC
DNJA1_HUMAN_Tsuboyama_2023_2LO1
DOCK1_MOUSE_Tsuboyama_2023_2M0Y
DYR_ECOLI_Nguyen_2023
DYR_ECOLI_Thompson_2019
ENV_HV1B9_DuenasDecamp_2016
ENV_HV1BR_Haddox_2016
ENVZ_ECOLI_Ghose_2023
EPHB2_HUMAN_Tsuboyama_2023_1F0M
ERBB2_HUMAN_Elazar_2016
ESTA_BACSU_Nutschel_2020
F7YBW8_MESOW_Ding_2023
F7YBW8_MESOW_Aakre_2015
FECA_ECOLI_Tsuboyama_2023_2D1U
FKBP3_HUMAN_Tsuboyama_2023_2KFV
GAL4_YEAST_Kitzman_2015
GCN4_YEAST_Staller_2018
GDIA_HUMAN_Silverstein_2021
GFP_AEQVI_Sarkisyan_2016
GLPA_HUMAN_Elazar_2016
GRB2_HUMAN_Faure_2021
HCP_LAMBD_Tsuboyama_2023_2L6Q
HECD1_HUMAN_Tsuboyama_2023_3DKM
HEM3_HUMAN_Loggerenberg_2023
HIS7_YEAST_Pokusaeva_2019
HMDH_HUMAN_Jiang_2019
HSP82_YEAST_Cote-Hammarlof_2020_growth-H2O2
HSP82_YEAST_Flynn_2019
HSP82_YEAST_Mishra_2016
HXK4_HUMAN_Gersing_2022_activity
HXK4_HUMAN_Gersing_2023_abundance
I6TAH8_I68A0_Doud_2015
IF1_ECOLI_Kelsic_2016
ILF3_HUMAN_Tsuboyama_2023_2L33
ISDH_STAAW_Tsuboyama_2023_2LHR
KCNE1_HUMAN_Muhammad_2023_expression
KCNE1_HUMAN_Muhammad_2023_function
KCNH2_HUMAN_Kozek_2020
KCNJ2_MOUSE_Coyote-Maestas_2022_function
KCNJ2_MOUSE_Coyote-Maestas_2022_surface
KKA2_KLEPN_Melnikov_2014
LGK_LIPST_Klesmith_2015
LYAM1_HUMAN_Elazar_2016
MAFG_MOUSE_Tsuboyama_2023_1K1V
MBD11_ARATH_Tsuboyama_2023_6ACV
MET_HUMAN_Estevam_2023
MK01_HUMAN_Brenan_2016
MLAC_ECOLI_MacRae_2023
MSH2_HUMAN_Jia_2020
MTH3_HAEAE_RockahShmuel_2015
MTHR_HUMAN_Weile_2021
MYO3_YEAST_Tsuboyama_2023_2BTT
NCAP_I34A1_Doud_2015
NKX31_HUMAN_Tsuboyama_2023_2L9R
NPC1_HUMAN_Erwood_2022_HEK293T
NPC1_HUMAN_Erwood_2022_RPE1
NRAM_I33A0_Jiang_2016
NUD15_HUMAN_Suiter_2020
NUSA_ECOLI_Tsuboyama_2023_1WCL
NUSG_MYCTU_Tsuboyama_2023_2MI6
OBSCN_HUMAN_Tsuboyama_2023_1V1C
ODP2_GEOSE_Tsuboyama_2023_1W4G
OPSD_HUMAN_Wan_2019
OTC_HUMAN_Lo_2023
OTU7A_HUMAN_Tsuboyama_2023_2L2D
OXDA_RHOTO_Vanella_2023_activity
OXDA_RHOTO_Vanella_2023_expression
P53_HUMAN_Giacomelli_2018_Null_Etoposide
P53_HUMAN_Giacomelli_2018_Null_Nutlin
P53_HUMAN_Giacomelli_2018_WT_Nutlin
P53_HUMAN_Kotler_2018
P84126_THETH_Chan_2017
PA_I34A1_Wu_2015
PABP_YEAST_Melamed_2013
PAI1_HUMAN_Huttinger_2021
PHOT_CHLRE_Chen_2023
PIN1_HUMAN_Tsuboyama_2023_1I6C
PITX2_HUMAN_Tsuboyama_2023_2L7M
PKN1_HUMAN_Tsuboyama_2023_1URF
POLG_CXB3N_Mattenberger_2021
POLG_DEN26_Suphatrakul_2023
POLG_HCVJF_Qi_2014
POLG_PESV_Tsuboyama_2023_2MXD
PPARG_HUMAN_Majithia_2016
PPM1D_HUMAN_Miller_2022
PR40A_HUMAN_Tsuboyama_2023_1UZC
PRKN_HUMAN_Clausen_2023
PSAE_PICP2_Tsuboyama_2023_1PSE
PTEN_HUMAN_Matreyek_2021
PTEN_HUMAN_Mighell_2018
Q2N0S5_9HIV1_Haddox_2018
Q53Z42_HUMAN_McShan_2019_binding-TAPBPR
Q53Z42_HUMAN_McShan_2019_expression
Q59976_STRSQ_Romero_2015
Q6WV12_9MAXI_Somermeyer_2022
Q837P4_ENTFA_Meier_2023
Q837P5_ENTFA_Meier_2023
Q8WTC7_9CNID_Somermeyer_2022
R1AB_SARS2_Flynn_2022
RAD_ANTMA_Tsuboyama_2023_2CJJ
RAF1_HUMAN_Zinkus-Boltz_2019
RASH_HUMAN_Bandaru_2017
RASK_HUMAN_Weng_2022_abundance
RASK_HUMAN_Weng_2022_binding-DARPin_K55
RBP1_HUMAN_Tsuboyama_2023_2KWH
RCD1_ARATH_Tsuboyama_2023_5OAO
RCRO_LAMBD_Tsuboyama_2023_1ORC
RD23A_HUMAN_Tsuboyama_2023_1IFY
RDRP_I33A0_Li_2023
REV_HV1H2_Fernandes_2016
RFAH_ECOLI_Tsuboyama_2023_2LCL
RL20_AQUAE_Tsuboyama_2023_1GYZ
RL40A_YEAST_Mavor_2016
RL40A_YEAST_Roscoe_2013
RL40A_YEAST_Roscoe_2014
RNC_ECOLI_Weeks_2023
RPC1_BP434_Tsuboyama_2023_1R69
RPC1_LAMBD_Li_2019_high-expression
RPC1_LAMBD_Li_2019_low-expression
RS15_GEOSE_Tsuboyama_2023_1A32
S22A1_HUMAN_Yee_2023_abundance
S22A1_HUMAN_Yee_2023_activity
SAV1_MOUSE_Tsuboyama_2023_2YSB
SBI_STAAM_Tsuboyama_2023_2JVG
SC6A4_HUMAN_Young_2021
SCIN_STAAR_Tsuboyama_2023_2QFF
SCN5A_HUMAN_Glazer_2019
SDA_BACSU_Tsuboyama_2023_1PV0
SERC_HUMAN_Xie_2023
SHOC2_HUMAN_Kwon_2022
SOX30_HUMAN_Tsuboyama_2023_7JJK
SPA_STAAU_Tsuboyama_2023_1LP1
SPG1_STRSG_Olson_2014
SPG1_STRSG_Wu_2016
SPG2_STRSG_Tsuboyama_2023_5UBS
SPIKE_SARS2_Starr_2020_binding
SPIKE_SARS2_Starr_2020_expression
SPTN1_CHICK_Tsuboyama_2023_1TUD
SQSTM_MOUSE_Tsuboyama_2023_2RRU
SR43C_ARATH_Tsuboyama_2023_2N88
SRBS1_HUMAN_Tsuboyama_2023_2O2W
SRC_HUMAN_Ahler_2019
SRC_HUMAN_Chakraborty_2023_binding-DAS_25uM
SRC_HUMAN_Nguyen_2022
SUMO1_HUMAN_Weile_2017
SYUA_HUMAN_Newberry_2020
TADBP_HUMAN_Bolognesi_2019
TAT_HV1BR_Fernandes_2016
TCRG1_MOUSE_Tsuboyama_2023_1E0L
THO1_YEAST_Tsuboyama_2023_2WQG
TNKS2_HUMAN_Tsuboyama_2023_5JRT
TPK1_HUMAN_Weile_2017
TPMT_HUMAN_Matreyek_2018
TPOR_HUMAN_Bridgford_2020
TRPC_SACS2_Chan_2017
TRPC_THEMA_Chan_2017
UBC9_HUMAN_Weile_2017
UBE4B_HUMAN_Tsuboyama_2023_3L1X
UBE4B_MOUSE_Starita_2013
UBR5_HUMAN_Tsuboyama_2023_1I2T
VG08_BPP22_Tsuboyama_2023_2GP8
VILI_CHICK_Tsuboyama_2023_1YU5
VKOR1_HUMAN_Chiasson_2020_abundance
VKOR1_HUMAN_Chiasson_2020_activity
VRPI_BPT7_Tsuboyama_2023_2WNM
YAIA_ECOLI_Tsuboyama_2023_2KVT
YAP1_HUMAN_Araya_2012
YNZC_BACSU_Tsuboyama_2023_2JVD

In [82]:
print(author_dms_subs_spearman['PoET-2'].mean())
print(author_dms_subs_spearman['PoET-2'])

0.5190723895302114
[0.46544408 0.49937867 0.02947372 0.54323114 0.6006638  0.56372733
 0.40038191 0.38856525 0.73909807 0.52508172 0.27919571 0.55136898
 0.45956223 0.35283168 0.6417437  0.61188734 0.58636293 0.40843302
 0.52595022 0.51549601 0.5506292  0.76282335 0.71493029 0.7588428
 0.57460455 0.43493919 0.47265746 0.24917966 0.57065009 0.34604249
 0.51530985 0.19368972 0.63865908 0.64957522 0.67845375 0.79628003
 0.37571131 0.74028498 0.48387946 0.55863634 0.35201846 0.31293045
 0.66095132 0.71029155 0.61371907 0.62165641 0.68592353 0.72386289
 0.54249975 0.47812616 0.81544373 0.5217904  0.50975557 0.46742387
 0.4043547  0.34179988 0.20233161 0.79983589 0.57160828 0.41815228
 0.57059175 0.4184206  0.57071078 0.40465943 0.53873959 0.21409544
 0.47278544 0.75378995 0.40382541 0.62614044 0.67031513 0.42361934
 0.44987616 0.59104739 0.45783158 0.36429206 0.36746876 0.4463608
 0.50346001 0.43794032 0.38857153 0.58680524 0.47695009 0.35878543
 0.07993494 0.56717038 0.43275332 0.36778351 0.36265035 0.65698084
 0.49860845 0.36759169 0.61905525 0.82227904 0.55228104 0.16126375
 0.37172796 0.40194266 0.67508468 0.31588143 0.50480083 0.46395074
 0.65306382 0.72326572 0.60848694 0.66281749 0.68429432 0.59996363
 0.59674089 0.80581642 0.20194375 0.59311303 0.62907613 0.64543707
 0.38235544 0.38207189 0.47917751 0.44227358 0.46793321 0.71670781
 0.61943156 0.58257689 0.70516257 0.47242586 0.71975115 0.71696456
 0.62152443 0.38361861 0.48079511 0.66687334 0.73465293 0.67393011
 0.61487222 0.63419563 0.86339847 0.71804023 0.60222211 0.50231403
 0.55856972 0.55404377 0.3717698  0.61204503 0.63210261 0.45589376
 0.43952437 0.36951945 0.36877925 0.67120969 0.49473941 0.34071149
 0.51870505 0.33365615 0.69347069 0.36830306 0.53229105 0.66426916
 0.55979845 0.56982557 0.31823918 0.31220385 0.71826577 0.39979915
 0.46668341 0.46690977 0.61543318 0.7791312  0.49657037 0.46840049
 0.48949636 0.64369521 0.5792412  0.59027524 0.49660864 0.57648566
 0.346315   0.10291647 0.58665661 0.56750384 0.34034078 0.43928967
 0.5888593  0.40411136 0.17325794 0.60346297 0.47412682 0.61055358
 0.67311336 0.68335423 0.74878117 0.69766352 0.51311223 0.41540276
 0.40686555 0.54184906 0.09440137 0.10962835 0.36718033 0.79066126
 0.5825762  0.62795276 0.29751072 0.57353694 0.45673299 0.61324935
 0.49108086 0.54336676 0.49177229 0.43786403 0.65005351 0.37434529
 0.65871779 0.52543343 0.43836681 0.52261322 0.62393039 0.44501103
 0.66427628]

In [72]:
df_check = pd.DataFrame()
df_check['is_match'] = (dms_subs_spearman['PoET-2'] - author_dms_subs_spearman['PoET-2']) < 0.001

In [73]:
df_check

     is_match
0        True
1        True
2        True
3        True
4        True
..        ...
212      True
213      True
214      True
215      True
216      True

[217 rows x 1 columns]

In [74]:
df_check.sum()

is_match    216
dtype: int64

In [75]:
df_check[df_check['is_match'] == False]

    is_match
86     False

In [76]:
dms_subs_spearman['PoET-2'][86]

np.float64(0.4341378534463362)

In [77]:
author_dms_subs_spearman['PoET-2'][86]

np.float64(0.43275331883297086)

In [79]:
dms_subs_ref_df['DMS_id'][86]

'KCNH2_HUMAN_Kozek_2020'

**Conclusions:** `KCNH2_HUMAN_Kozek_2020` has assay Spearman difference over 0.001; everything else has Spearman difference less than 0.001

# DMS indels
## Estimate runtime

In [15]:
BLAT_ECOLX_Gonzalez_runtime_min = 7.5
BLAT_ECOLX_Gonzalez_cost = 4751
dms_indel_df = estimate_runtime_dms_indels(BLAT_ECOLX_Gonzalez_cost, BLAT_ECOLX_Gonzalez_runtime_min)

    index                                  DMS_id  estimated_min
7       7  CAPSD_AAV2S_Sinai_2021_designed_indels     356.763839
8       8   CAPSD_AAV2S_Sinai_2021_library_indels      39.320143
23     23       KCNJ2_MOUSE_Macdonald_2022_indels      16.577036
21     21        HIS7_YEAST_Pokusaeva_2019_indels       9.632709
6       6         BLAT_ECOLX_Gonzalez_2019_indels       7.500000
3       3           B1LPA6_ECOSM_Russ_2020_indels       4.852663
0       0              A4_HUMAN_Seuma_2022_indels       3.703431
48     48    S22A1_HUMAN_Yee_2023_activity_indels       0.773521
47     47   S22A1_HUMAN_Yee_2023_abundance_indels       0.678804
33     33            P53_HUMAN_Kotler_2018_indels       0.538308
41     41       Q8EG35_SHEON_Campbell_2022_indels       0.522522
40     40          PTEN_HUMAN_Mighell_2018_indels       0.495685
10     10  CBPA2_HUMAN_Tsuboyama_2023_1O6X_indels       0.323616
9       9   CATR_CHLRE_Tsuboyama_2023_2AMI_indels       0.310987
12     12   CSN4_MOUSE_Tsuboyama_2023_1UFM_indels       0.307830
22     22   ILF3_HUMAN_Tsuboyama_2023_2L33_indels       0.304673
18     18   FECA_ECOLI_Tsuboyama_2023_2D1U_indels       0.304673
28     28   NUSA_ECOLI_Tsuboyama_2023_1WCL_indels       0.301515
36     36   PKN1_HUMAN_Tsuboyama_2023_1URF_indels       0.295201
17     17  EPHB2_HUMAN_Tsuboyama_2023_1F0M_indels       0.292044

In [16]:
dms_indel_df[dms_indel_df['estimated_min'] < 5]["estimated_min"].sum()

np.float64(23.595558829720062)

## Check runs finished

In [45]:
check_runs(dms_indels_ref_df, dms_indels_output_dir)

66
./PR/.cache/ProteinGym/zero_shot_indels_scores/PoET-2/ []
./PR/.cache/ProteinGym/zero_shot_indels_scores/PoET-2/ 66

## Calculate Spearman

In [88]:
dms_indels_spearman = calc_spearman(dms_indels_ref_df, dms_indels_output_dir, dms_indels_dms_dir, "model_list_zero_shot_indels_DMS")

A4_HUMAN_Seuma_2022_indels
AMFR_HUMAN_Tsuboyama_2023_4G3O_indels
ARGR_ECOLI_Tsuboyama_2023_1AOY_indels
B1LPA6_ECOSM_Russ_2020_indels
BBC1_YEAST_Tsuboyama_2023_1TG0_indels
BCHB_CHLTE_Tsuboyama_2023_2KRU_indels
BLAT_ECOLX_Gonzalez_2019_indels
CAPSD_AAV2S_Sinai_2021_designed_indels
CAPSD_AAV2S_Sinai_2021_library_indels
CATR_CHLRE_Tsuboyama_2023_2AMI_indels
CBPA2_HUMAN_Tsuboyama_2023_1O6X_indels
CBX4_HUMAN_Tsuboyama_2023_2K28_indels
CSN4_MOUSE_Tsuboyama_2023_1UFM_indels
CUE1_YEAST_Tsuboyama_2023_2MYX_indels
DN7A_SACS2_Tsuboyama_2023_1JIC_indels
DNJA1_HUMAN_Tsuboyama_2023_2LO1_indels
DOCK1_MOUSE_Tsuboyama_2023_2M0Y_indels
EPHB2_HUMAN_Tsuboyama_2023_1F0M_indels
FECA_ECOLI_Tsuboyama_2023_2D1U_indels
HCP_LAMBD_Tsuboyama_2023_2L6Q_indels
HECD1_HUMAN_Tsuboyama_2023_3DKM_indels
HIS7_YEAST_Pokusaeva_2019_indels
ILF3_HUMAN_Tsuboyama_2023_2L33_indels
KCNJ2_MOUSE_Macdonald_2022_indels
MAFG_MOUSE_Tsuboyama_2023_1K1V_indels
MBD11_ARATH_Tsuboyama_2023_6ACV_indels
MYO3_YEAST_Tsuboyama_2023_2BTT_indels
NKX31_HUMAN_Tsuboyama_2023_2L9R_indels
NUSA_ECOLI_Tsuboyama_2023_1WCL_indels
NUSG_MYCTU_Tsuboyama_2023_2MI6_indels
OBSCN_HUMAN_Tsuboyama_2023_1V1C_indels
ODP2_GEOSE_Tsuboyama_2023_1W4G_indels
OTU7A_HUMAN_Tsuboyama_2023_2L2D_indels
P53_HUMAN_Kotler_2018_indels
PIN1_HUMAN_Tsuboyama_2023_1I6C_indels
PITX2_HUMAN_Tsuboyama_2023_2L7M_indels
PKN1_HUMAN_Tsuboyama_2023_1URF_indels
POLG_PESV_Tsuboyama_2023_2MXD_indels
PR40A_HUMAN_Tsuboyama_2023_1UZC_indels
PSAE_PICP2_Tsuboyama_2023_1PSE_indels
PTEN_HUMAN_Mighell_2018_indels
Q8EG35_SHEON_Campbell_2022_indels
RAD_ANTMA_Tsuboyama_2023_2CJJ_indels
RCD1_ARATH_Tsuboyama_2023_5OAO_indels
RD23A_HUMAN_Tsuboyama_2023_1IFY_indels
RPC1_BP434_Tsuboyama_2023_1R69_indels
RS15_GEOSE_Tsuboyama_2023_1A32_indels
S22A1_HUMAN_Yee_2023_abundance_indels
S22A1_HUMAN_Yee_2023_activity_indels
SAV1_MOUSE_Tsuboyama_2023_2YSB_indels
SDA_BACSU_Tsuboyama_2023_1PV0_indels
SOX30_HUMAN_Tsuboyama_2023_7JJK_indels
SPG2_STRSG_Tsuboyama_2023_5UBS_indels
SPTN1_CHICK_Tsuboyama_2023_1TUD_indels
SQSTM_MOUSE_Tsuboyama_2023_2RRU_indels
SR43C_ARATH_Tsuboyama_2023_2N88_indels
SRBS1_HUMAN_Tsuboyama_2023_2O2W_indels
TCRG1_MOUSE_Tsuboyama_2023_1E0L_indels
THO1_YEAST_Tsuboyama_2023_2WQG_indels
TNKS2_HUMAN_Tsuboyama_2023_5JRT_indels
UBE4B_HUMAN_Tsuboyama_2023_3L1X_indels
UBR5_HUMAN_Tsuboyama_2023_1I2T_indels
VG08_BPP22_Tsuboyama_2023_2GP8_indels
VILI_CHICK_Tsuboyama_2023_1YU5_indels
VRPI_BPT7_Tsuboyama_2023_2WNM_indels
YNZC_BACSU_Tsuboyama_2023_2JVD_indels

In [89]:
dms_indels_spearman['PoET-2'].mean()

np.float64(0.6045118056439708)

In [92]:
dms_indels_perf = build_performance_all_DMS(dms_indels_spearman, dms_indels_ref_df, "model_list_zero_shot_indels_DMS")
dms_indels_leaderboard = average_across_assays(dms_indels_perf).sort_values(ascending=False)
print(dms_indels_leaderboard)

PoET-2    0.573833
dtype: float64

Compare with authors' raw scores

In [93]:
author_dir = './PR/proteingym_v1.3_zero_shot_indels_scores_poet_2_afdb_v6'

author_dms_indels_spearman = calc_spearman(dms_indels_ref_df, author_dir, dms_indels_dms_dir, "model_list_zero_shot_indels_DMS")

A4_HUMAN_Seuma_2022_indels
AMFR_HUMAN_Tsuboyama_2023_4G3O_indels
ARGR_ECOLI_Tsuboyama_2023_1AOY_indels
B1LPA6_ECOSM_Russ_2020_indels
BBC1_YEAST_Tsuboyama_2023_1TG0_indels
BCHB_CHLTE_Tsuboyama_2023_2KRU_indels
BLAT_ECOLX_Gonzalez_2019_indels
CAPSD_AAV2S_Sinai_2021_designed_indels
CAPSD_AAV2S_Sinai_2021_library_indels
CATR_CHLRE_Tsuboyama_2023_2AMI_indels
CBPA2_HUMAN_Tsuboyama_2023_1O6X_indels
CBX4_HUMAN_Tsuboyama_2023_2K28_indels
CSN4_MOUSE_Tsuboyama_2023_1UFM_indels
CUE1_YEAST_Tsuboyama_2023_2MYX_indels
DN7A_SACS2_Tsuboyama_2023_1JIC_indels
DNJA1_HUMAN_Tsuboyama_2023_2LO1_indels
DOCK1_MOUSE_Tsuboyama_2023_2M0Y_indels
EPHB2_HUMAN_Tsuboyama_2023_1F0M_indels
FECA_ECOLI_Tsuboyama_2023_2D1U_indels
HCP_LAMBD_Tsuboyama_2023_2L6Q_indels
HECD1_HUMAN_Tsuboyama_2023_3DKM_indels
HIS7_YEAST_Pokusaeva_2019_indels
ILF3_HUMAN_Tsuboyama_2023_2L33_indels
KCNJ2_MOUSE_Macdonald_2022_indels
MAFG_MOUSE_Tsuboyama_2023_1K1V_indels
MBD11_ARATH_Tsuboyama_2023_6ACV_indels
MYO3_YEAST_Tsuboyama_2023_2BTT_indels
NKX31_HUMAN_Tsuboyama_2023_2L9R_indels
NUSA_ECOLI_Tsuboyama_2023_1WCL_indels
NUSG_MYCTU_Tsuboyama_2023_2MI6_indels
OBSCN_HUMAN_Tsuboyama_2023_1V1C_indels
ODP2_GEOSE_Tsuboyama_2023_1W4G_indels
OTU7A_HUMAN_Tsuboyama_2023_2L2D_indels
P53_HUMAN_Kotler_2018_indels
PIN1_HUMAN_Tsuboyama_2023_1I6C_indels
PITX2_HUMAN_Tsuboyama_2023_2L7M_indels
PKN1_HUMAN_Tsuboyama_2023_1URF_indels
POLG_PESV_Tsuboyama_2023_2MXD_indels
PR40A_HUMAN_Tsuboyama_2023_1UZC_indels
PSAE_PICP2_Tsuboyama_2023_1PSE_indels
PTEN_HUMAN_Mighell_2018_indels
Q8EG35_SHEON_Campbell_2022_indels
RAD_ANTMA_Tsuboyama_2023_2CJJ_indels
RCD1_ARATH_Tsuboyama_2023_5OAO_indels
RD23A_HUMAN_Tsuboyama_2023_1IFY_indels
RPC1_BP434_Tsuboyama_2023_1R69_indels
RS15_GEOSE_Tsuboyama_2023_1A32_indels
S22A1_HUMAN_Yee_2023_abundance_indels
S22A1_HUMAN_Yee_2023_activity_indels
SAV1_MOUSE_Tsuboyama_2023_2YSB_indels
SDA_BACSU_Tsuboyama_2023_1PV0_indels
SOX30_HUMAN_Tsuboyama_2023_7JJK_indels
SPG2_STRSG_Tsuboyama_2023_5UBS_indels
SPTN1_CHICK_Tsuboyama_2023_1TUD_indels
SQSTM_MOUSE_Tsuboyama_2023_2RRU_indels
SR43C_ARATH_Tsuboyama_2023_2N88_indels
SRBS1_HUMAN_Tsuboyama_2023_2O2W_indels
TCRG1_MOUSE_Tsuboyama_2023_1E0L_indels
THO1_YEAST_Tsuboyama_2023_2WQG_indels
TNKS2_HUMAN_Tsuboyama_2023_5JRT_indels
UBE4B_HUMAN_Tsuboyama_2023_3L1X_indels
UBR5_HUMAN_Tsuboyama_2023_1I2T_indels
VG08_BPP22_Tsuboyama_2023_2GP8_indels
VILI_CHICK_Tsuboyama_2023_1YU5_indels
VRPI_BPT7_Tsuboyama_2023_2WNM_indels
YNZC_BACSU_Tsuboyama_2023_2JVD_indels

In [94]:
print(author_dms_indels_spearman['PoET-2'].mean())
print(author_dms_indels_spearman['PoET-2'])

0.6045033947330347
[0.56150762 0.67250371 0.58878433 0.47079534 0.67398596 0.552334
 0.64937529 0.67992963 0.2942418  0.55163256 0.59350476 0.58838327
 0.33550632 0.71003914 0.57251085 0.48090549 0.67834594 0.63335734
 0.56527763 0.71936832 0.64974658 0.7101096  0.68104001 0.49884478
 0.00143612 0.74802221 0.67674637 0.64818194 0.58357674 0.46798231
 0.89577843 0.82308048 0.6206338  0.52770156 0.81645968 0.37778927
 0.83824355 0.77500091 0.71418701 0.41959695 0.78400153 0.4892994
 0.3380365  0.37594335 0.74665602 0.62541591 0.31824345 0.50739422
 0.56398312 0.79568848 0.80709247 0.5707256  0.50752766 0.80244298
 0.69077747 0.69577602 0.84040349 0.75448361 0.79939269 0.26467708
 0.47252718 0.67928119 0.61051835 0.61890281 0.68163171 0.50995412]

In [95]:
df_check = pd.DataFrame()
df_check['is_match'] = (dms_indels_spearman['PoET-2'] - author_dms_indels_spearman['PoET-2']) < 0.001
df_check.sum()

is_match    66
dtype: int64

In [96]:
len(df_check)

66

In [97]:
author_dms_indels_perf = build_performance_all_DMS(author_dms_indels_spearman, dms_indels_ref_df, "model_list_zero_shot_indels_DMS")
author_dms_indels_leaderboard = average_across_assays(author_dms_indels_perf).sort_values(ascending=False)
print(dms_indels_leaderboard)

PoET-2    0.573833
dtype: float64

**Conclusion:** The authors reported 0.573, so update it

# Clinical subs

## Estimate run time

In [32]:
test_runtime_min = 4
test_cost = 26
clinical_subs_df = estimate_runtime_clinical_subs(test_cost, test_runtime_min)

      index          DMS_id  total_number_mutants  estimated_min
634     634  NP_001159435.1                   741     114.000000
318     318     NP_000518.1                   639      98.307692
301     301     NP_000486.1                   508      78.153846
1563   1563     NP_009225.1                   456      70.153846
223     223     NP_000341.2                   448      68.923077
876     876     NP_001835.3                   402      61.846154
178     178     NP_000268.1                   399      61.384615
334     334     NP_000539.2                   376      57.846154
49       49     NP_000080.2                   344      52.923077
48       48     NP_000079.2                   338      52.000000
163     163     NP_000248.2                   301      46.307692
50       50     NP_000081.2                   290      44.615385
157     157     NP_000242.1                   288      44.307692
332     332     NP_000537.3                   271      41.692308
2395   2395     NP_742105.1                   271      41.692308
2110   2110     NP_079033.4                   270      41.538462
1990   1990     NP_066287.2                   270      41.538462
356     356     NP_000712.2                   238      36.615385
1762   1762     NP_056374.2                   212      32.615385
377     377     NP_000825.2                   209      32.153846

In [33]:
len(clinical_subs_df)

2525

In [16]:
clinical_subs_df[["index","DMS_id","total_number_mutants", "estimated_min"]].to_csv("./PR/clinical_subs_estimated_time.csv")

## Check run finished

In [7]:
check_runs(clinical_subs_ref_df, clinical_subs_output_dir)

./PR/.cache/ProteinGym/zero_shot_clinical_substitutions_scores/PoET-2 [] 0 unfinished
./PR/.cache/ProteinGym/zero_shot_clinical_substitutions_scores/PoET-2 2525 finished

## Calculate AUROC

In [49]:
clinical_subs_auroc = calc_auroc(clinical_subs_ref_df, clinical_subs_output_dir, clinical_subs_dms_dir, "model_list_zero_shot_substitutions_clinical")

In [50]:
overall_auroc(clinical_subs_auroc, list(model_dict["model_list_zero_shot_substitutions_clinical"].keys()))

PoET-2    0.932
dtype: float64

# clinical indels
## Estimate runtime

In [40]:
test_runtime_min = 4
test_cost = 26
clinical_indels_df = estimate_runtime_clinical_indels(test_cost, test_runtime_min)

      index          DMS_id  total_number_mutants  estimated_min
178     178     NP_000518.1                    31       4.769231
236     236  NP_001035957.1                    28       4.307692
275     275  NP_001159435.1                    21       3.230769
217     217  NP_001009944.3                    18       2.769231
48       48     NP_000129.3                    16       2.461538
83       83     NP_000240.1                    14       2.153846
265     265  NP_001123910.1                    13       2.000000
369     369     NP_001835.3                    12       1.846154
88       88     NP_000248.2                    12       1.846154
784     784     NP_597677.2                    11       1.692308
191     191     NP_000539.2                    10       1.538462
116     116     NP_000313.2                    10       1.538462
36       36     NP_000086.2                     9       1.384615
811     811     NP_733821.1                     9       1.384615
530     530     NP_005219.2                     9       1.384615
1544   1544   UPI00006BFF57                     8       1.230769
229     229  NP_001027392.1                     8       1.230769
782     782     NP_570854.1                     8       1.230769
193     193     NP_000543.3                     8       1.230769
98       98     NP_000268.1                     8       1.230769

In [41]:
clinical_indels_df["estimated_min"].sum()

np.float64(397.07692307692304)

In [42]:
len(clinical_indels_df)

1555

## Check run finished

In [18]:
check_runs(clinical_indels_ref_df, clinical_indels_output_dir)

./PR/.cache/ProteinGym/zero_shot_clinical_indels_scores/PoET-2 [] 0 unfinished
./PR/.cache/ProteinGym/zero_shot_clinical_indels_scores/PoET-2 1555 finished

In [19]:
clinical_indels_ref_df

,DMS_id,DMS_filename,target_seq,mutated_sequence_column,MSA_start,MSA_end,MSA_filename,weight_file_name,dataset,total_number_mutants,proxy_cost,estimated_min
0,NP_000007.1,NP_000007.1.csv,MAAGFGRCCRVLRSISRFHWRSQHTKANRQREPGLGFSFEFTEQQK...,mutated_sequence,1.0,421.0,NP_000007.1.a2m,NP_000007.1.npy,ClinVar,2,2,4.50
1,NP_000008.1,NP_000008.1.csv,MAAALLARASGPARRALCPRAWRQLHTIYQSVELPETHQMLLQTCR...,mutated_sequence,1.0,412.0,NP_000008.1.a2m,NP_000008.1.npy,ClinVar,1,1,2.25
2,NP_000009.1,NP_000009.1.csv,MQAARMAASLGRQLLRLGGGSSRLTALLGQPRPGPARRPYAGGAAQ...,mutated_sequence,1.0,655.0,NP_000009.1.a2m,NP_000009.1.npy,ClinVar,4,4,9.00
3,NP_000010.1,NP_000010.1.csv,MAVLAALLRSGARSRSPLLRRLVQEIRYVERSYVSKPTLKEVVIVS...,mutated_sequence,1.0,427.0,NP_000010.1.a2m,NP_000010.1.npy,ClinVar,4,4,9.00
4,NP_000011.2,NP_000011.2.csv,MTLGSPRKGLLMLLMALVTQGDPVKPSRGPLVTCTCESPHCKGPTC...,mutated_sequence,1.0,503.0,NP_000011.2.a2m,NP_000011.2.npy,ClinVar,6,6,13.50
...,...,...,...,...,...,...,...,...,...,...,...,...
1550,UPI000008AB1D,UPI000008AB1D.csv,MAVMAPRTLLLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,mutated_sequence,1.0,365.0,UPI000008AB1D.a2m,UPI000008AB1D.npy,gnomAD,1,1,2.25
1551,UPI0000456761,UPI0000456761.csv,MSAPPVLRPPSPLLPVAAAAAAAAAALVPGSGPGPAPFLAPVAAPV...,mutated_sequence,1.0,912.0,UPI0000456761.a2m,UPI0000456761.npy,gnomAD,1,1,2.25
1552,UPI000015FEE1,UPI000015FEE1.csv,MVFESVVVDVLNRFLGDYVVDLDTSQLSLGIWKGAVALKNLQIKEN...,mutated_sequence,1.0,3095.0,UPI000015FEE1.a2m,UPI000015FEE1.npy,gnomAD,1,1,2.25
1553,UPI000012CBC3,UPI000012CBC3.csv,MKALIAALLLITLQYSCAVSPTDCSAVEPEAEKALDLINKRRRDGY...,mutated_sequence,1.0,525.0,UPI000012CBC3.a2m,UPI000012CBC3.npy,gnomAD,1,1,2.25
1554,UPI000019080B,UPI000019080B.csv,MQSDDVIWDTLGNKQFCSFKIRTKTQSFCRNEYSLTGLCNRSSCPL...,mutated_sequence,1.0,300.0,UPI000019080B.a2m,UPI000019080B.npy,gnomAD,1,1,2.25

In [30]:
def calculate_total_number_mutants(DMS_id, clinical_indel_dir=clinical_indels_dms_dir):
    return len(pd.read_csv(f"{clinical_indel_dir}/{DMS_id}.csv", sep=","))
clinical_indels_ref_df["total_number_mutants"] = clinical_indels_ref_df['DMS_id'].map(calculate_total_number_mutants)

In [11]:
clinical_indels_ref_df["total_number_mutants"].iloc[:81].sum()

np.int64(241)

In [14]:
clinical_indels_ref_df["total_number_mutants"].iloc[778:868].sum()

np.int64(160)

In [10]:
test_cost = 160
test_time = 360
clinical_indels_df = estimate_runtime_clinical_indels(test_cost, test_time, unit="min")

      index          DMS_id  total_number_mutants  estimated_min
178     178     NP_000518.1                    31          69.75
236     236  NP_001035957.1                    28          63.00
275     275  NP_001159435.1                    21          47.25
217     217  NP_001009944.3                    18          40.50
48       48     NP_000129.3                    16          36.00
83       83     NP_000240.1                    14          31.50
265     265  NP_001123910.1                    13          29.25
369     369     NP_001835.3                    12          27.00
88       88     NP_000248.2                    12          27.00
784     784     NP_597677.2                    11          24.75
191     191     NP_000539.2                    10          22.50
116     116     NP_000313.2                    10          22.50
36       36     NP_000086.2                     9          20.25
811     811     NP_733821.1                     9          20.25
530     530     NP_005219.2                     9          20.25
1544   1544   UPI00006BFF57                     8          18.00
229     229  NP_001027392.1                     8          18.00
782     782     NP_570854.1                     8          18.00
193     193     NP_000543.3                     8          18.00
98       98     NP_000268.1                     8          18.00

In [16]:
clinical_indels_df[["index","DMS_id","total_number_mutants", "estimated_min"]].to_csv("./PR/clinical_indels_estimated_time.csv")

## Calculate AUROC

In [28]:
author_dir = './PR/proteingym_v1.3_zero_shot_clinical_indels_scores_poet_2'
gene_ids = clinical_indels_ref_df['DMS_id'].tolist()
author_clinical_indels_auroc = compute_pooled_auc(gene_ids, "model_list_zero_shot_indels_clinical", author_dir, clinical_indels_dms_dir)

Pooled 2878 variants across 1555 genes

In [29]:
author_clinical_indels_auroc

PoET-2    0.945
dtype: float64

In [30]:
compute_pooled_auc(gene_ids, "model_list_zero_shot_indels_clinical", clinical_indels_output_dir, clinical_indels_dms_dir)

Pooled 2878 variants across 1555 genes

PoET-2    0.946
dtype: float64

To figure out whether this is correct, apply the function to PoET

In [102]:
def compute_pooled_auc_test(gene_ids, model_dict_key, scores_folder, clinical_folder, label_col="DMS_score_bin"):
    """Pool all variants across genes, then compute a single AUC per model.
    Used for indels where per-gene sample sizes are too small.
    """
    pooled = []
    model_config = model_dict[model_dict_key]
    model_list = model_dict[model_dict_key].keys()
    clin_auroc = dict()
    for gene_id in gene_ids:
        score_file = os.path.join(scores_folder, f"{gene_id}.csv")
        if not os.path.exists(score_file):
            print(f"Missing score file for {gene_id}")
            continue

        score_df = pd.read_csv(score_file)
        if "PoET_score" not in score_df.columns:
            print(f"Missing score column for {gene_id}")
            continue
        
        clinical_file = os.path.join(clinical_folder, f"{gene_id}.csv")
        if not os.path.exists(clinical_file):
            print(f"Missing clinical file for {gene_id}")
            continue

        true_df = pd.read_csv(clinical_file)
        if label_col not in true_df.columns:
            print(f"Missing {label_col} column for {gene_id} in clinical file")
            continue
        
        true_df[label_col] = true_df[label_col].values
        # convert to binary labels if there are strings
        true_df[label_col] = [1 if val == "Pathogenic" else val for val in true_df[label_col]]
        true_df[label_col] = [0 if val == "Benign" else val for val in true_df[label_col]]
        # flip labels (since pathogenic should be less fit)
        true_df[label_col] = np.array(true_df[label_col])
        assert np.all((true_df[label_col] == 1) | (true_df[label_col] == 0)), "Labels contain NaNs"
        true_df[label_col] = 1 - true_df[label_col]
        
        assert len(true_df) == len(score_df), f"length mismatch for {gene_id}"
        merged = pd.concat([true_df[[label_col]].reset_index(drop=True),
                            score_df[['PoET_score']].reset_index(drop=True)], axis=1)
        pooled.append(merged)

    if not pooled:
        print("No data loaded!")
        return pd.Series(dtype=float)
    
    pooled = pd.concat(pooled, ignore_index=True)
    print(f"Pooled {len(pooled)} variants across {len(gene_ids)} genes")
    
    out = dict()
    for model in model_list:
        cfg = model_dict[model_dict_key][model]
        score_name = cfg["input_score_name"]
        if score_name not in pooled.columns:
            print(f"Missing score column '{score_name}' for {model}")
            out[model] = np.nan; continue

        y_true  = pooled[label_col]
        y_score = pooled[score_name] * cfg["directionality"]

        # AUROC is undefined unless both classes are present and scores are finite
        valid = y_score.notna()
        if y_true[valid].nunique() < 2:
            print(f"Only one class in {model}; AUROC undefined")
            out[model] = np.nan
            continue
        try:
            out[model] = round(roc_auc_score(y_true=y_true[valid].values,
                                             y_score=y_score[valid].values), 3)
        except Exception as e:
            print(f"AUROC issue in {model}: {e}")
            out[model] = np.nan
                               
    return pd.Series(out).sort_values(ascending=False)

In [104]:
gene_ids = clinical_indels_ref_df['DMS_id'].tolist()
compute_pooled_auc_test(gene_ids, "model_list_zero_shot_indels_clinical", "PR/.cache/ProteinGym/v1.2/zero_shot_clinical_indels_scores/PoET", clinical_indels_dms_dir)

Pooled 2878 variants across 1555 genes

PoET    0.931
dtype: float64

In [125]:
def compute_pooled_auc_test(gene_ids, model_dict_key, scores_folder, clinical_folder, label_col="DMS_score_bin"):
    """Pool all variants across genes, then compute a single AUC per model.
    Used for indels where per-gene sample sizes are too small.
    """
    pooled = []
    model_config = model_dict[model_dict_key]
    model_list = model_dict[model_dict_key].keys()
    clin_auroc = dict()
    for gene_id in gene_ids:
        score_file = os.path.join(scores_folder, f"{gene_id}.csv")
        if not os.path.exists(score_file):
            print(f"Missing score file for {gene_id}")
            continue

        score_df = pd.read_csv(score_file)
        if "provean_score" not in score_df.columns:
            print(f"Missing score column for {gene_id}")
            continue
        
        clinical_file = os.path.join(clinical_folder, f"{gene_id}.csv")
        if not os.path.exists(clinical_file):
            print(f"Missing clinical file for {gene_id}")
            continue

        true_df = pd.read_csv(clinical_file)
        if label_col not in true_df.columns:
            print(f"Missing {label_col} column for {gene_id} in clinical file")
            continue
        
        true_df[label_col] = true_df[label_col].values
        # convert to binary labels if there are strings
        true_df[label_col] = [1 if val == "Pathogenic" else val for val in true_df[label_col]]
        true_df[label_col] = [0 if val == "Benign" else val for val in true_df[label_col]]
        # flip labels (since pathogenic should be less fit)
        true_df[label_col] = np.array(true_df[label_col])
        assert np.all((true_df[label_col] == 1) | (true_df[label_col] == 0)), "Labels contain NaNs"
        true_df[label_col] = 1 - true_df[label_col]
        
        assert len(true_df) == len(score_df), f"length mismatch for {gene_id}"
#         score_df.drop_duplicates(inplace=True)
        merged = pd.merge(true_df, score_df, on="mutated_sequence")
        merged = merged[["mutated_sequence", label_col, "provean_score"]]
        merged = merged.groupby("mutated_sequence").mean().reset_index()
        pooled.append(merged)

    if not pooled:
        print("No data loaded!")
        return pd.Series(dtype=float)
    
    pooled = pd.concat(pooled, ignore_index=True)
    print(f"Pooled {len(pooled)} variants across {len(gene_ids)} genes")
    
    out = dict()
    for model in model_list:
        cfg = model_dict[model_dict_key][model]
        score_name = cfg["input_score_name"]
        if score_name not in pooled.columns:
            print(f"Missing score column '{score_name}' for {model}")
            out[model] = np.nan; continue

        y_true  = pooled[label_col]
        y_score = pooled[score_name] * cfg["directionality"]

        # AUROC is undefined unless both classes are present and scores are finite
        valid = y_score.notna()
        if y_true[valid].nunique() < 2:
            print(f"Only one class in {model}; AUROC undefined")
            out[model] = np.nan
            continue
        try:
            out[model] = round(roc_auc_score(y_true=y_true[valid].values,
                                             y_score=y_score[valid].values), 3)
        except Exception as e:
            print(f"AUROC issue in {model}: {e}")
            out[model] = np.nan
                               
    return pd.Series(out).sort_values(ascending=False)

In [126]:
# gene_ids = clinical_indels_ref_df['DMS_id'].tolist()
compute_pooled_auc_test(gene_ids, "model_list_zero_shot_indels_clinical", "PR/.cache/ProteinGym/v1.2/zero_shot_clinical_indels_scores/Provean", clinical_indels_dms_dir)

Pooled 2878 variants across 1555 genes

Provean    0.921
dtype: float64

## Test old scripts
Cannot fully replicate the AUROC for substitution indels (tried PoET and Provean). Try running the original old scripts:

In [1]:
!pip install tqdm

Collecting tqdm
  Downloading tqdm-4.68.2-py3-none-any.whl.metadata (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.7/58.7 kB 1.6 MB/s eta 0:00:00
Requirement already satisfied: importlib_metadata in /home/jar2158/.conda/envs/jupyter37/lib/python3.7/site-packages (from tqdm) (6.7.0)
Requirement already satisfied: zipp>=0.5 in /home/jar2158/.conda/envs/jupyter37/lib/python3.7/site-packages (from importlib_metadata->tqdm) (3.15.0)
Requirement already satisfied: typing-extensions>=3.6.4 in /home/jar2158/.conda/envs/jupyter37/lib/python3.7/site-packages (from importlib_metadata->tqdm) (4.7.1)
Downloading tqdm-4.68.2-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.6/78.6 kB 3.3 MB/s eta 0:00:00
Installing collected packages: tqdm
Successfully installed tqdm-4.68.2

In [16]:
!pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.0.2-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (10 kB)
Collecting numpy>=1.14.6 (from scikit-learn)
  Downloading numpy-1.21.6-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (2.1 kB)
Collecting scipy>=1.1.0 (from scikit-learn)
  Downloading scipy-1.7.3-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (2.2 kB)
Collecting joblib>=0.11 (from scikit-learn)
  Downloading joblib-1.3.2-py3-none-any.whl.metadata (5.4 kB)
Collecting threadpoolctl>=2.0.0 (from scikit-learn)
  Downloading threadpoolctl-3.1.0-py3-none-any.whl.metadata (9.2 kB)
Downloading scikit_learn-1.0.2-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (24.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.8/24.8 MB 93.6 MB/s eta 0:00:00:00:0100:01
Downloading joblib-1.3.2-py3-none-any.whl (302 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.2/302.2 kB 13.4 MB/s eta 0:00:00
Downloading numpy-1.21.6-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.7/15.7 MB 110.7 MB/s eta 0:00:0000:0100:01
Downloading scipy-1.7.3-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (38.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.1/38.1 MB 82.3 MB/s eta 0:00:00:00:0100:01
Downloading threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Installing collected packages: threadpoolctl, numpy, joblib, scipy, scikit-learn
Successfully installed joblib-1.3.2 numpy-1.21.6 scikit-learn-1.0.2 scipy-1.7.3 threadpoolctl-3.1.0

In [7]:
!cd /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym2/
!/n/groups/marks/users/aaron/pmhc/envs/dl_binder_design/bin/python PR/ProteinGym/proteingym/merge.py \
    --DMS_assays_location ./PR/.cache/ProteinGym/clinical_ProteinGym_indels \
    --model_scores_location ./PR/.cache/ProteinGym/v1.2/zero_shot_clinical_indels_scores \
    --merged_scores_dir merged_scores \
    --mutation_type indels \
    --dataset clinical \
    --DMS_reference_file ./ProteinGym/reference_files/clinical_indels.csv \
    --config_file ./PR/config.json

Processing DMS assay NP_000007.1:   0%|                | 0/1555 [00:00<?, ?it/s]NP_000007.1: DMS=2, merged=2
Processing DMS assay NP_000008.1:   0%|        | 1/1555 [00:00<03:37,  7.15it/s]NP_000008.1: DMS=1, merged=1
Processing DMS assay NP_000009.1:   0%|        | 2/1555 [00:00<03:11,  8.12it/s]NP_000009.1: DMS=4, merged=4
Processing DMS assay NP_000010.1:   0%|        | 3/1555 [00:00<03:06,  8.32it/s]NP_000010.1: DMS=4, merged=4
Processing DMS assay NP_000011.2:   0%|        | 4/1555 [00:00<03:02,  8.48it/s]NP_000011.2: DMS=6, merged=6
Processing DMS assay NP_000012.1:   0%|        | 5/1555 [00:00<03:01,  8.54it/s]NP_000012.1: DMS=5, merged=5
Processing DMS assay NP_000017.1:   0%|        | 6/1555 [00:00<03:01,  8.52it/s]NP_000017.1: DMS=1, merged=1
Processing DMS assay NP_000018.2:   0%|        | 7/1555 [00:00<03:00,  8.57it/s]NP_000018.2: DMS=1, merged=1
Processing DMS assay NP_000021.1:   1%|        | 8/1555 [00:00<03:08,  8.20it/s]NP_000021.1: DMS=5, merged=5
Processing DMS assay NP_000024.2:   1%|        | 9/1555 [00:01<03:05,  8.34it/s]NP_000024.2: DMS=6, merged=6
Processing DMS assay NP_000026.2:   1%|       | 10/1555 [00:01<03:04,  8.36it/s]NP_000026.2: DMS=3, merged=3
Processing DMS assay NP_000032.1:   1%|       | 11/1555 [00:01<03:01,  8.50it/s]NP_000032.1: DMS=1, merged=1
Processing DMS assay NP_000034.1:   1%|       | 12/1555 [00:01<02:58,  8.64it/s]NP_000034.1: DMS=1, merged=1
Processing DMS assay NP_000035.2:   1%|       | 13/1555 [00:01<03:01,  8.50it/s]Note: HMM scored 4/13 mutants for NP_000035.2; rest left as NaN.
NP_000035.2: DMS=13, merged=13
Processing DMS assay NP_000037.2:   1%|       | 14/1555 [00:01<03:04,  8.33it/s]Note: HMM scored 1/3 mutants for NP_000037.2; rest left as NaN.
NP_000037.2: DMS=3, merged=3
Processing DMS assay NP_000038.2:   1%|       | 15/1555 [00:01<03:04,  8.33it/s]NP_000038.2: DMS=1, merged=1
Processing DMS assay NP_000042.3:   1%|       | 16/1555 [00:01<03:03,  8.39it/s]Note: HMM scored 7/8 mutants for NP_000042.3; rest left as NaN.
NP_000042.3: DMS=8, merged=8
Processing DMS assay NP_000043.4:   1%|       | 17/1555 [00:02<03:07,  8.19it/s]NP_000043.4: DMS=2, merged=2
Processing DMS assay NP_000044.2:   1%|       | 18/1555 [00:02<03:16,  7.82it/s]NP_000044.2: DMS=4, merged=4
Processing DMS assay NP_000045.1:   1%|       | 19/1555 [00:02<03:12,  7.97it/s]NP_000045.1: DMS=3, merged=3
Processing DMS assay NP_000048.1:   1%|       | 20/1555 [00:02<03:11,  8.01it/s]Note: HMM scored 2/3 mutants for NP_000048.1; rest left as NaN.
NP_000048.1: DMS=3, merged=3
Processing DMS assay NP_000050.3:   1%|       | 21/1555 [00:02<03:11,  8.03it/s]Note: HMM scored 3/6 mutants for NP_000050.3; rest left as NaN.
NP_000050.3: DMS=6, merged=6
Processing DMS assay NP_000052.1:   1%|       | 22/1555 [00:02<03:13,  7.94it/s]NP_000052.1: DMS=3, merged=3
Processing DMS assay NP_000053.2:   1%|       | 23/1555 [00:02<03:11,  8.01it/s]NP_000053.2: DMS=3, merged=3
Processing DMS assay NP_000061.1:   2%|       | 24/1555 [00:02<03:10,  8.05it/s]NP_000061.1: DMS=2, merged=2
Processing DMS assay NP_000068.1:   2%|       | 25/1555 [00:03<03:07,  8.16it/s]NP_000068.1: DMS=2, merged=2
Processing DMS assay NP_000071.1:   2%|       | 26/1555 [00:03<03:04,  8.28it/s]NP_000071.1: DMS=3, merged=3
Processing DMS assay NP_000073.1:   2%|       | 27/1555 [00:03<03:07,  8.16it/s]NP_000073.1: DMS=1, merged=1
Processing DMS assay NP_000074.3:   2%|▏      | 28/1555 [00:03<03:15,  7.81it/s]NP_000074.3: DMS=1, merged=1
Processing DMS assay NP_000079.2:   2%|▏      | 29/1555 [00:03<03:10,  8.02it/s]NP_000079.2: DMS=4, merged=4
Processing DMS assay NP_000080.2:   2%|▏      | 30/1555 [00:03<03:11,  7.96it/s]NP_000080.2: DMS=5, merged=5
Processing DMS assay NP_000081.2:   2%|▏      | 31/1555 [00:03<03:12,  7.93it/s]NP_000081.2: DMS=3, merged=3
Processing DMS assay NP_000082.2:   2%|▏      | 32/1555 [00:03<03:12,  7.93it/s]NP_000082.2: DMS=2, merged=2
Processing DMS assay NP_000083.3:   2%|▏      | 33/1555 [00:04<03:10,  8.00it/s]NP_000083.3: DMS=1, merged=1
Processing DMS assay NP_000084.3:   2%|▏      | 34/1555 [00:04<03:08,  8.05it/s]NP_000084.3: DMS=3, merged=3
Processing DMS assay NP_000085.1:   2%|▏      | 35/1555 [00:04<03:08,  8.07it/s]NP_000085.1: DMS=1, merged=1
Processing DMS assay NP_000086.2:   2%|▏      | 36/1555 [00:04<03:05,  8.18it/s]NP_000086.2: DMS=9, merged=9
Processing DMS assay NP_000089.1:   2%|▏      | 37/1555 [00:04<03:05,  8.19it/s]NP_000089.1: DMS=1, merged=1
Processing DMS assay NP_000093.1:   2%|▏      | 38/1555 [00:04<03:02,  8.31it/s]NP_000093.1: DMS=4, merged=4
Processing DMS assay NP_000095.2:   3%|▏      | 39/1555 [00:04<03:11,  7.91it/s]NP_000095.2: DMS=1, merged=1
Processing DMS assay NP_000102.1:   3%|▏      | 40/1555 [00:04<03:08,  8.02it/s]NP_000102.1: DMS=2, merged=2
Processing DMS assay NP_000103.2:   3%|▏      | 41/1555 [00:05<03:08,  8.05it/s]NP_000103.2: DMS=2, merged=2
Processing DMS assay NP_000104.1:   3%|▏      | 42/1555 [00:05<03:06,  8.10it/s]NP_000104.1: DMS=1, merged=1
Processing DMS assay NP_000117.1:   3%|▏      | 43/1555 [00:05<03:02,  8.28it/s]NP_000117.1: DMS=2, merged=2
Processing DMS assay NP_000118.2:   3%|▏      | 44/1555 [00:05<03:01,  8.33it/s]NP_000118.2: DMS=1, merged=1
Processing DMS assay NP_000119.1:   3%|▏      | 45/1555 [00:05<03:00,  8.34it/s]NP_000119.1: DMS=1, merged=1
Processing DMS assay NP_000123.1:   3%|▏      | 46/1555 [00:05<02:58,  8.43it/s]NP_000123.1: DMS=3, merged=3
Processing DMS assay NP_000126.2:   3%|▏      | 47/1555 [00:05<03:02,  8.28it/s]NP_000126.2: DMS=8, merged=8
Processing DMS assay NP_000129.3:   3%|▏      | 48/1555 [00:05<03:05,  8.14it/s]NP_000129.3: DMS=16, merged=16
Processing DMS assay NP_000132.3:   3%|▏      | 49/1555 [00:06<03:10,  7.89it/s]NP_000132.3: DMS=5, merged=5
Processing DMS assay NP_000134.2:   3%|▏      | 50/1555 [00:06<03:13,  7.76it/s]NP_000134.2: DMS=6, merged=6
Processing DMS assay NP_000135.2:   3%|▏      | 51/1555 [00:06<03:10,  7.90it/s]NP_000135.2: DMS=1, merged=1
Processing DMS assay NP_000142.2:   3%|▏      | 52/1555 [00:06<03:04,  8.13it/s]NP_000142.2: DMS=2, merged=2
Processing DMS assay NP_000143.2:   3%|▏      | 53/1555 [00:06<02:59,  8.35it/s]NP_000143.2: DMS=7, merged=7
Processing DMS assay NP_000144.2:   3%|▏      | 54/1555 [00:06<02:59,  8.35it/s]NP_000144.2: DMS=2, merged=2
Processing DMS assay NP_000146.2:   4%|▏      | 55/1555 [00:06<02:59,  8.38it/s]NP_000146.2: DMS=2, merged=2
Processing DMS assay NP_000148.2:   4%|▎      | 56/1555 [00:06<02:56,  8.50it/s]NP_000148.2: DMS=1, merged=1
Processing DMS assay NP_000152.1:   4%|▎      | 57/1555 [00:06<02:54,  8.60it/s]NP_000152.1: DMS=2, merged=2
Processing DMS assay NP_000153.1:   4%|▎      | 58/1555 [00:07<02:52,  8.68it/s]NP_000153.1: DMS=2, merged=2
Processing DMS assay NP_000156.1:   4%|▎      | 59/1555 [00:07<02:52,  8.66it/s]NP_000156.1: DMS=3, merged=3
Processing DMS assay NP_000157.1:   4%|▎      | 60/1555 [00:07<03:03,  8.17it/s]NP_000157.1: DMS=1, merged=1
Processing DMS assay NP_000160.1:   4%|▎      | 61/1555 [00:07<02:58,  8.37it/s]NP_000160.1: DMS=6, merged=6
Processing DMS assay NP_000161.2:   4%|▎      | 62/1555 [00:07<02:58,  8.39it/s]NP_000161.2: DMS=3, merged=3
Processing DMS assay NP_000169.1:   4%|▎      | 63/1555 [00:07<02:54,  8.53it/s]NP_000169.1: DMS=1, merged=1
Processing DMS assay NP_000170.1:   4%|▎      | 64/1555 [00:07<02:51,  8.69it/s]NP_000170.1: DMS=8, merged=8
Processing DMS assay NP_000177.2:   4%|▎      | 65/1555 [00:07<02:53,  8.58it/s]NP_000177.2: DMS=1, merged=1
Processing DMS assay NP_000184.1:   4%|▎      | 66/1555 [00:08<02:50,  8.71it/s]NP_000184.1: DMS=3, merged=3
Processing DMS assay NP_000187.3:   4%|▎      | 67/1555 [00:08<02:50,  8.71it/s]NP_000187.3: DMS=2, merged=2
Processing DMS assay NP_000188.1:   4%|▎      | 68/1555 [00:08<02:50,  8.70it/s]NP_000188.1: DMS=1, merged=1
Processing DMS assay NP_000193.1:   4%|▎      | 69/1555 [00:08<02:49,  8.79it/s]NP_000193.1: DMS=3, merged=3
Processing DMS assay NP_000194.2:   5%|▎      | 70/1555 [00:08<02:51,  8.68it/s]NP_000194.2: DMS=4, merged=4
Processing DMS assay NP_000197.1:   5%|▎      | 71/1555 [00:08<02:58,  8.31it/s]NP_000197.1: DMS=1, merged=1
Processing DMS assay NP_000199.2:   5%|▎      | 72/1555 [00:08<02:56,  8.38it/s]NP_000199.2: DMS=1, merged=1
Processing DMS assay NP_000203.2:   5%|▎      | 73/1555 [00:08<02:53,  8.52it/s]NP_000203.2: DMS=1, merged=1
Processing DMS assay NP_000206.2:   5%|▎      | 74/1555 [00:08<02:52,  8.58it/s]NP_000206.2: DMS=2, merged=2
Processing DMS assay NP_000209.2:   5%|▎      | 75/1555 [00:09<02:51,  8.63it/s]Note: HMM scored 6/8 mutants for NP_000209.2; rest left as NaN.
NP_000209.2: DMS=8, merged=8
Processing DMS assay NP_000213.1:   5%|▎      | 76/1555 [00:09<02:53,  8.51it/s]NP_000213.1: DMS=6, merged=6
Processing DMS assay NP_000220.1:   5%|▎      | 77/1555 [00:09<02:56,  8.35it/s]NP_000220.1: DMS=2, merged=2
Processing DMS assay NP_000223.1:   5%|▎      | 78/1555 [00:09<02:53,  8.51it/s]NP_000223.1: DMS=1, merged=1
Processing DMS assay NP_000224.2:   5%|▎      | 79/1555 [00:09<02:51,  8.62it/s]Note: HMM scored 1/2 mutants for NP_000224.2; rest left as NaN.
NP_000224.2: DMS=2, merged=2
Processing DMS assay NP_000226.2:   5%|▎      | 80/1555 [00:09<02:51,  8.62it/s]NP_000226.2: DMS=2, merged=2
Processing DMS assay NP_000229.1:   5%|▎      | 81/1555 [00:09<02:49,  8.71it/s]NP_000229.1: DMS=3, merged=3
Processing DMS assay NP_000237.2:   5%|▎      | 82/1555 [00:09<02:57,  8.29it/s]NP_000237.2: DMS=1, merged=1
Processing DMS assay NP_000240.1:   5%|▎      | 83/1555 [00:10<02:53,  8.50it/s]NP_000240.1: DMS=14, merged=14
Processing DMS assay NP_000242.1:   5%|▍      | 84/1555 [00:10<02:56,  8.36it/s]Note: HMM scored 6/7 mutants for NP_000242.1; rest left as NaN.
NP_000242.1: DMS=7, merged=7
Processing DMS assay NP_000243.1:   5%|▍      | 85/1555 [00:10<02:55,  8.38it/s]NP_000243.1: DMS=4, merged=4
Processing DMS assay NP_000246.2:   6%|▍      | 86/1555 [00:10<02:54,  8.43it/s]NP_000246.2: DMS=4, merged=4
Processing DMS assay NP_000247.2:   6%|▍      | 87/1555 [00:10<02:53,  8.45it/s]NP_000247.2: DMS=2, merged=2
Processing DMS assay NP_000248.2:   6%|▍      | 88/1555 [00:10<02:51,  8.54it/s]NP_000248.2: DMS=12, merged=12
Processing DMS assay NP_000251.3:   6%|▍      | 89/1555 [00:10<02:55,  8.35it/s]NP_000251.3: DMS=8, merged=8
Processing DMS assay NP_000252.1:   6%|▍      | 90/1555 [00:10<02:55,  8.33it/s]NP_000252.1: DMS=2, merged=2
Processing DMS assay NP_000255.2:   6%|▍      | 91/1555 [00:10<02:52,  8.49it/s]Note: HMM scored 6/8 mutants for NP_000255.2; rest left as NaN.
NP_000255.2: DMS=8, merged=8
Processing DMS assay NP_000257.1:   6%|▍      | 92/1555 [00:11<02:59,  8.15it/s]NP_000257.1: DMS=1, merged=1
Processing DMS assay NP_000259.1:   6%|▍      | 93/1555 [00:11<02:54,  8.38it/s]NP_000259.1: DMS=1, merged=1
Processing DMS assay NP_000262.2:   6%|▍      | 94/1555 [00:11<02:52,  8.46it/s]NP_000262.2: DMS=6, merged=6
Processing DMS assay NP_000265.1:   6%|▍      | 95/1555 [00:11<02:52,  8.48it/s]NP_000265.1: DMS=1, merged=1
Processing DMS assay NP_000266.2:   6%|▍      | 96/1555 [00:11<02:48,  8.65it/s]NP_000266.2: DMS=1, merged=1
Processing DMS assay NP_000267.2:   6%|▍      | 97/1555 [00:11<02:47,  8.73it/s]NP_000267.2: DMS=1, merged=1
Processing DMS assay NP_000268.1:   6%|▍      | 98/1555 [00:11<02:47,  8.72it/s]NP_000268.1: DMS=8, merged=8
Processing DMS assay NP_000269.3:   6%|▍      | 99/1555 [00:11<02:48,  8.62it/s]NP_000269.3: DMS=1, merged=1
Processing DMS assay NP_000273.2:   6%|▍     | 100/1555 [00:12<02:47,  8.71it/s]NP_000273.2: DMS=1, merged=1
Processing DMS assay NP_000275.1:   6%|▍     | 101/1555 [00:12<02:47,  8.68it/s]NP_000275.1: DMS=3, merged=3
Processing DMS assay NP_000276.2:   7%|▍     | 102/1555 [00:12<02:48,  8.63it/s]NP_000276.2: DMS=1, merged=1
Processing DMS assay NP_000277.1:   7%|▍     | 103/1555 [00:12<02:56,  8.24it/s]NP_000277.1: DMS=2, merged=2
Processing DMS assay NP_000282.1:   7%|▍     | 104/1555 [00:12<02:54,  8.32it/s]NP_000282.1: DMS=1, merged=1
Processing DMS assay NP_000283.1:   7%|▍     | 105/1555 [00:12<02:50,  8.48it/s]NP_000283.1: DMS=5, merged=5
Processing DMS assay NP_000286.3:   7%|▍     | 106/1555 [00:12<02:51,  8.46it/s]NP_000286.3: DMS=1, merged=1
Processing DMS assay NP_000288.1:   7%|▍     | 107/1555 [00:12<02:48,  8.60it/s]Note: HMM scored 2/4 mutants for NP_000288.1; rest left as NaN.
NP_000288.1: DMS=4, merged=4
Processing DMS assay NP_000289.1:   7%|▍     | 108/1555 [00:12<02:48,  8.57it/s]NP_000289.1: DMS=1, merged=1
Processing DMS assay NP_000292.1:   7%|▍     | 109/1555 [00:13<02:47,  8.65it/s]NP_000292.1: DMS=1, merged=1
Processing DMS assay NP_000293.2:   7%|▍     | 110/1555 [00:13<02:46,  8.69it/s]NP_000293.2: DMS=1, merged=1
Processing DMS assay NP_000301.1:   7%|▍     | 111/1555 [00:13<02:44,  8.79it/s]NP_000301.1: DMS=1, merged=1
Processing DMS assay NP_000305.3:   7%|▍     | 112/1555 [00:13<02:42,  8.87it/s]NP_000305.3: DMS=5, merged=5
Processing DMS assay NP_000308.1:   7%|▍     | 113/1555 [00:13<02:51,  8.38it/s]NP_000308.1: DMS=1, merged=1
Processing DMS assay NP_000311.2:   7%|▍     | 114/1555 [00:13<02:48,  8.54it/s]NP_000311.2: DMS=1, merged=1
Processing DMS assay NP_000312.2:   7%|▍     | 115/1555 [00:13<02:46,  8.62it/s]Note: HMM scored 1/3 mutants for NP_000312.2; rest left as NaN.
NP_000312.2: DMS=3, merged=3
Processing DMS assay NP_000313.2:   7%|▍     | 116/1555 [00:13<02:47,  8.61it/s]NP_000313.2: DMS=10, merged=10
Processing DMS assay NP_000320.1:   8%|▍     | 117/1555 [00:13<02:49,  8.51it/s]NP_000320.1: DMS=1, merged=1
Processing DMS assay NP_000325.4:   8%|▍     | 118/1555 [00:14<02:47,  8.57it/s]NP_000325.4: DMS=3, merged=3
Processing DMS assay NP_000326.2:   8%|▍     | 119/1555 [00:14<02:48,  8.51it/s]NP_000326.2: DMS=6, merged=6
Processing DMS assay NP_000333.1:   8%|▍     | 120/1555 [00:14<02:49,  8.48it/s]NP_000333.1: DMS=1, merged=1
Processing DMS assay NP_000339.2:   8%|▍     | 121/1555 [00:14<02:45,  8.66it/s]NP_000339.2: DMS=1, merged=1
Processing DMS assay NP_000341.2:   8%|▍     | 122/1555 [00:14<02:42,  8.80it/s]NP_000341.2: DMS=8, merged=8
Processing DMS assay NP_000349.1:   8%|▍     | 123/1555 [00:14<02:45,  8.63it/s]NP_000349.1: DMS=1, merged=1
Processing DMS assay NP_000350.1:   8%|▍     | 124/1555 [00:14<02:50,  8.39it/s]NP_000350.1: DMS=2, merged=2
Processing DMS assay NP_000351.2:   8%|▍     | 125/1555 [00:14<02:47,  8.52it/s]NP_000351.2: DMS=1, merged=1
Processing DMS assay NP_000354.4:   8%|▍     | 126/1555 [00:15<02:45,  8.64it/s]NP_000354.4: DMS=1, merged=1
Processing DMS assay NP_000359.1:   8%|▍     | 127/1555 [00:15<02:43,  8.75it/s]Note: HMM scored 2/6 mutants for NP_000359.1; rest left as NaN.
NP_000359.1: DMS=6, merged=6
Processing DMS assay NP_000362.1:   8%|▍     | 128/1555 [00:15<02:45,  8.62it/s]NP_000362.1: DMS=2, merged=2
Processing DMS assay NP_000363.1:   8%|▍     | 129/1555 [00:15<02:43,  8.73it/s]NP_000363.1: DMS=3, merged=3
Processing DMS assay NP_000371.1:   8%|▌     | 130/1555 [00:15<02:45,  8.59it/s]NP_000371.1: DMS=1, merged=1
Processing DMS assay NP_000372.1:   8%|▌     | 131/1555 [00:15<02:45,  8.61it/s]NP_000372.1: DMS=1, merged=1
Processing DMS assay NP_000373.1:   8%|▌     | 132/1555 [00:15<02:45,  8.62it/s]NP_000373.1: DMS=1, merged=1
Processing DMS assay NP_000375.3:   9%|▌     | 133/1555 [00:15<02:44,  8.63it/s]NP_000375.3: DMS=1, merged=1
Processing DMS assay NP_000381.1:   9%|▌     | 134/1555 [00:15<02:43,  8.71it/s]NP_000381.1: DMS=1, merged=1
Processing DMS assay NP_000382.3:   9%|▌     | 135/1555 [00:16<02:50,  8.33it/s]NP_000382.3: DMS=1, merged=1
Processing DMS assay NP_000388.2:   9%|▌     | 136/1555 [00:16<02:47,  8.46it/s]NP_000388.2: DMS=2, merged=2
Processing DMS assay NP_000389.1:   9%|▌     | 137/1555 [00:16<02:48,  8.42it/s]NP_000389.1: DMS=3, merged=3
Processing DMS assay NP_000391.1:   9%|▌     | 138/1555 [00:16<02:49,  8.36it/s]NP_000391.1: DMS=2, merged=2
Processing DMS assay NP_000395.3:   9%|▌     | 139/1555 [00:16<02:47,  8.47it/s]NP_000395.3: DMS=2, merged=2
Processing DMS assay NP_000396.2:   9%|▌     | 140/1555 [00:16<02:47,  8.43it/s]NP_000396.2: DMS=1, merged=1
Processing DMS assay NP_000401.1:   9%|▌     | 141/1555 [00:16<02:47,  8.45it/s]NP_000401.1: DMS=1, merged=1
Processing DMS assay NP_000410.2:   9%|▌     | 142/1555 [00:16<02:48,  8.40it/s]NP_000410.2: DMS=4, merged=4

Processing DMS assay NP_000413.1:   9%|▌     | 143/1555 [00:17<02:48,  8.40it/s]NP_000413.1: DMS=1, merged=1
Processing DMS assay NP_000417.3:   9%|▌     | 144/1555 [00:17<02:45,  8.54it/s]Note: HMM scored 1/2 mutants for NP_000417.3; rest left as NaN.
NP_000417.3: DMS=2, merged=2
Processing DMS assay NP_000423.2:   9%|▌     | 145/1555 [00:17<02:51,  8.20it/s]NP_000423.2: DMS=1, merged=1
Processing DMS assay NP_000424.2:   9%|▌     | 146/1555 [00:17<02:47,  8.43it/s]NP_000424.2: DMS=1, merged=1
Processing DMS assay NP_000430.3:   9%|▌     | 147/1555 [00:17<02:44,  8.58it/s]NP_000430.3: DMS=1, merged=1
Processing DMS assay NP_000432.1:  10%|▌     | 148/1555 [00:17<02:43,  8.60it/s]NP_000432.1: DMS=2, merged=2
Processing DMS assay NP_000435.3:  10%|▌     | 149/1555 [00:17<02:42,  8.63it/s]NP_000435.3: DMS=3, merged=3
Processing DMS assay NP_000442.1:  10%|▌     | 150/1555 [00:17<02:42,  8.67it/s]NP_000442.1: DMS=1, merged=1
Processing DMS assay NP_000446.1:  10%|▌     | 151/1555 [00:17<02:41,  8.70it/s]NP_000446.1: DMS=2, merged=2
Processing DMS assay NP_000449.1:  10%|▌     | 152/1555 [00:18<02:42,  8.65it/s]NP_000449.1: DMS=1, merged=1
Processing DMS assay NP_000454.1:  10%|▌     | 153/1555 [00:18<02:40,  8.74it/s]NP_000454.1: DMS=1, merged=1
Processing DMS assay NP_000457.1:  10%|▌     | 154/1555 [00:18<02:39,  8.79it/s]NP_000457.1: DMS=1, merged=1
Processing DMS assay NP_000465.1:  10%|▌     | 155/1555 [00:18<02:39,  8.80it/s]Note: HMM scored 1/2 mutants for NP_000465.1; rest left as NaN.
NP_000465.1: DMS=2, merged=2
Processing DMS assay NP_000467.1:  10%|▌     | 156/1555 [00:18<02:48,  8.29it/s]NP_000467.1: DMS=1, merged=1
Processing DMS assay NP_000468.1:  10%|▌     | 157/1555 [00:18<02:44,  8.47it/s]NP_000468.1: DMS=1, merged=1
Processing DMS assay NP_000469.3:  10%|▌     | 158/1555 [00:18<02:43,  8.55it/s]NP_000469.3: DMS=4, merged=4
Processing DMS assay NP_000476.1:  10%|▌     | 159/1555 [00:18<02:45,  8.44it/s]NP_000476.1: DMS=3, merged=3
Processing DMS assay NP_000478.3:  10%|▌     | 160/1555 [00:19<02:43,  8.53it/s]NP_000478.3: DMS=2, merged=2
Processing DMS assay NP_000479.1:  10%|▌     | 161/1555 [00:19<02:42,  8.59it/s]NP_000479.1: DMS=5, merged=5
Processing DMS assay NP_000480.3:  10%|▋     | 162/1555 [00:19<02:42,  8.60it/s]Note: HMM scored 1/6 mutants for NP_000480.3; rest left as NaN.
NP_000480.3: DMS=6, merged=6
Processing DMS assay NP_000481.2:  10%|▋     | 163/1555 [00:19<02:43,  8.50it/s]NP_000481.2: DMS=2, merged=2
Processing DMS assay NP_000483.3:  11%|▋     | 164/1555 [00:19<02:40,  8.66it/s]Note: HMM scored 8/9 mutants for NP_000483.3; rest left as NaN.
NP_000483.3: DMS=9, merged=9
Processing DMS assay NP_000484.2:  11%|▋     | 165/1555 [00:19<02:42,  8.56it/s]NP_000484.2: DMS=1, merged=1
Processing DMS assay NP_000485.3:  11%|▋     | 166/1555 [00:19<02:40,  8.68it/s]NP_000485.3: DMS=1, merged=1
Processing DMS assay NP_000489.3:  11%|▋     | 167/1555 [00:19<02:43,  8.49it/s]NP_000489.3: DMS=3, merged=3
Processing DMS assay NP_000497.1:  11%|▋     | 168/1555 [00:19<02:40,  8.62it/s]NP_000497.1: DMS=1, merged=1
Processing DMS assay NP_000498.2:  11%|▋     | 169/1555 [00:20<02:38,  8.72it/s]NP_000498.2: DMS=1, merged=1
Processing DMS assay NP_000499.1:  11%|▋     | 170/1555 [00:20<02:38,  8.76it/s]NP_000499.1: DMS=1, merged=1
Processing DMS assay NP_000503.1:  11%|▋     | 171/1555 [00:20<02:36,  8.86it/s]NP_000503.1: DMS=1, merged=1
Processing DMS assay NP_000507.1:  11%|▋     | 172/1555 [00:20<02:34,  8.93it/s]Note: HMM scored 5/7 mutants for NP_000507.1; rest left as NaN.
NP_000507.1: DMS=7, merged=7
Processing DMS assay NP_000508.1:  11%|▋     | 173/1555 [00:20<02:36,  8.84it/s]NP_000508.1: DMS=2, merged=2
Processing DMS assay NP_000509.1:  11%|▋     | 174/1555 [00:20<02:37,  8.79it/s]NP_000509.1: DMS=4, merged=4
Processing DMS assay NP_000511.2:  11%|▋     | 175/1555 [00:20<02:40,  8.57it/s]NP_000511.2: DMS=2, merged=2
Processing DMS assay NP_000512.2:  11%|▋     | 176/1555 [00:20<02:42,  8.48it/s]NP_000512.2: DMS=1, merged=1
Processing DMS assay NP_000517.3:  11%|▋     | 177/1555 [00:21<02:50,  8.10it/s]Note: HMM scored 2/3 mutants for NP_000517.3; rest left as NaN.
NP_000517.3: DMS=3, merged=3
Processing DMS assay NP_000518.1:  11%|▋     | 178/1555 [00:21<02:48,  8.19it/s]NP_000518.1: DMS=31, merged=31
Processing DMS assay NP_000521.2:  12%|▋     | 179/1555 [00:21<02:53,  7.92it/s]NP_000521.2: DMS=3, merged=3
Processing DMS assay NP_000522.3:  12%|▋     | 180/1555 [00:21<02:50,  8.07it/s]NP_000522.3: DMS=2, merged=2
Processing DMS assay NP_000523.2:  12%|▋     | 181/1555 [00:21<02:49,  8.11it/s]NP_000523.2: DMS=2, merged=2
Processing DMS assay NP_000524.3:  12%|▋     | 182/1555 [00:21<02:47,  8.18it/s]NP_000524.3: DMS=1, merged=1
Processing DMS assay NP_000526.2:  12%|▋     | 183/1555 [00:21<02:45,  8.27it/s]NP_000526.2: DMS=1, merged=1
Processing DMS assay NP_000527.2:  12%|▋     | 184/1555 [00:21<02:45,  8.29it/s]NP_000527.2: DMS=1, merged=1
Processing DMS assay NP_000528.1:  12%|▋     | 185/1555 [00:21<02:43,  8.39it/s]NP_000528.1: DMS=1, merged=1
Processing DMS assay NP_000530.1:  12%|▋     | 186/1555 [00:22<02:43,  8.37it/s]NP_000530.1: DMS=1, merged=1
Processing DMS assay NP_000531.2:  12%|▋     | 187/1555 [00:22<02:45,  8.27it/s]Note: HMM scored 3/5 mutants for NP_000531.2; rest left as NaN.
NP_000531.2: DMS=5, merged=5
Processing DMS assay NP_000534.3:  12%|▋     | 188/1555 [00:22<02:56,  7.75it/s]NP_000534.3: DMS=1, merged=1
Processing DMS assay NP_000536.6:  12%|▋     | 189/1555 [00:22<02:50,  8.00it/s]NP_000536.6: DMS=3, merged=3
Processing DMS assay NP_000537.3:  12%|▋     | 190/1555 [00:22<02:49,  8.05it/s]NP_000537.3: DMS=7, merged=7
Processing DMS assay NP_000539.2:  12%|▋     | 191/1555 [00:22<02:47,  8.16it/s]Note: HMM scored 10/12 mutants for NP_000539.2; rest left as NaN.
NP_000539.2: DMS=12, merged=12
Processing DMS assay NP_000542.1:  12%|▋     | 192/1555 [00:22<02:47,  8.13it/s]NP_000542.1: DMS=4, merged=4
Processing DMS assay NP_000543.3:  12%|▋     | 193/1555 [00:22<02:44,  8.28it/s]NP_000543.3: DMS=8, merged=8
Processing DMS assay NP_000608.1:  12%|▋     | 194/1555 [00:23<02:44,  8.28it/s]NP_000608.1: DMS=1, merged=1
Processing DMS assay NP_000633.2:  13%|▊     | 195/1555 [00:23<02:40,  8.50it/s]NP_000633.2: DMS=1, merged=1
Processing DMS assay NP_000711.1:  13%|▊     | 196/1555 [00:23<02:39,  8.50it/s]NP_000711.1: DMS=1, merged=1
Processing DMS assay NP_000735.1:  13%|▊     | 197/1555 [00:23<02:37,  8.65it/s]NP_000735.1: DMS=1, merged=1
Processing DMS assay NP_000738.2:  13%|▊     | 198/1555 [00:23<02:35,  8.75it/s]NP_000738.2: DMS=1, merged=1
Processing DMS assay NP_000772.2:  13%|▊     | 199/1555 [00:23<02:39,  8.52it/s]NP_000772.2: DMS=1, merged=1
Processing DMS assay NP_000780.1:  13%|▊     | 200/1555 [00:23<02:35,  8.70it/s]NP_000780.1: DMS=2, merged=2
Processing DMS assay NP_000808.2:  13%|▊     | 201/1555 [00:23<02:35,  8.72it/s]NP_000808.2: DMS=1, merged=1
Processing DMS assay NP_000866.1:  13%|▊     | 202/1555 [00:23<02:34,  8.77it/s]NP_000866.1: DMS=1, merged=1
Processing DMS assay NP_000882.1:  13%|▊     | 203/1555 [00:24<02:34,  8.72it/s]NP_000882.1: DMS=2, merged=2
Processing DMS assay NP_000885.1:  13%|▊     | 204/1555 [00:24<02:35,  8.68it/s]NP_000885.1: DMS=1, merged=1
Processing DMS assay NP_000890.1:  13%|▊     | 205/1555 [00:24<02:34,  8.72it/s]NP_000890.1: DMS=1, merged=1
Processing DMS assay NP_000912.3:  13%|▊     | 206/1555 [00:24<02:33,  8.77it/s]NP_000912.3: DMS=1, merged=1
Processing DMS assay NP_000925.2:  13%|▊     | 207/1555 [00:24<02:33,  8.76it/s]NP_000925.2: DMS=1, merged=1
Processing DMS assay NP_000928.1:  13%|▊     | 208/1555 [00:24<02:35,  8.67it/s]NP_000928.1: DMS=2, merged=2
Processing DMS assay NP_000966.2:  13%|▊     | 209/1555 [00:24<02:46,  8.07it/s]NP_000966.2: DMS=1, merged=1
Processing DMS assay NP_001001344.1:  14%|▍  | 210/1555 [00:24<02:43,  8.23it/s]NP_001001344.1: DMS=2, merged=2
Processing DMS assay NP_001003694.1:  14%|▍  | 211/1555 [00:25<02:45,  8.11it/s]NP_001003694.1: DMS=1, merged=1
Processing DMS assay NP_001003800.1:  14%|▍  | 212/1555 [00:25<02:44,  8.15it/s]NP_001003800.1: DMS=2, merged=2
Processing DMS assay NP_001003891.1:  14%|▍  | 213/1555 [00:25<02:47,  8.02it/s]NP_001003891.1: DMS=6, merged=6
Processing DMS assay NP_001004311.2:  14%|▍  | 214/1555 [00:25<02:49,  7.92it/s]NP_001004311.2: DMS=1, merged=1
Processing DMS assay NP_001005273.1:  14%|▍  | 215/1555 [00:25<02:46,  8.04it/s]NP_001005273.1: DMS=1, merged=1
Processing DMS assay NP_001009899.3:  14%|▍  | 216/1555 [00:25<02:44,  8.12it/s]Note: HMM scored 3/5 mutants for NP_001009899.3; rest left as NaN.
NP_001009899.3: DMS=5, merged=5
Processing DMS assay NP_001009944.3:  14%|▍  | 217/1555 [00:25<02:47,  8.00it/s]NP_001009944.3: DMS=18, merged=18
Processing DMS assay NP_001012632.1:  14%|▍  | 218/1555 [00:25<02:58,  7.51it/s]NP_001012632.1: DMS=1, merged=1
Processing DMS assay NP_001013.1:  14%|▊     | 219/1555 [00:26<02:50,  7.84it/s]NP_001013.1: DMS=1, merged=1
Processing DMS assay NP_001013861.1:  14%|▍  | 220/1555 [00:26<02:52,  7.76it/s]NP_001013861.1: DMS=1, merged=1
Processing DMS assay NP_001015877.1:  14%|▍  | 221/1555 [00:26<02:45,  8.06it/s]NP_001015877.1: DMS=1, merged=1
Processing DMS assay NP_001015880.1:  14%|▍  | 222/1555 [00:26<02:43,  8.14it/s]NP_001015880.1: DMS=1, merged=1
Processing DMS assay NP_001018005.1:  14%|▍  | 223/1555 [00:26<02:44,  8.09it/s]NP_001018005.1: DMS=1, merged=1
Processing DMS assay NP_001018125.1:  14%|▍  | 224/1555 [00:26<02:42,  8.19it/s]NP_001018125.1: DMS=1, merged=1
Processing DMS assay NP_001019801.3:  14%|▍  | 225/1555 [00:26<02:42,  8.18it/s]NP_001019801.3: DMS=1, merged=1
Processing DMS assay NP_001025067.1:  15%|▍  | 226/1555 [00:26<02:40,  8.28it/s]NP_001025067.1: DMS=3, merged=3
Processing DMS assay NP_001026.2:  15%|▉     | 227/1555 [00:27<02:39,  8.32it/s]NP_001026.2: DMS=5, merged=5
Processing DMS assay NP_001026895.2:  15%|▍  | 228/1555 [00:27<02:41,  8.21it/s]NP_001026895.2: DMS=1, merged=1
Processing DMS assay NP_001027392.1:  15%|▍  | 229/1555 [00:27<02:39,  8.32it/s]NP_001027392.1: DMS=8, merged=8
Processing DMS assay NP_001027554.1:  15%|▍  | 230/1555 [00:27<02:46,  7.95it/s]NP_001027554.1: DMS=1, merged=1
Processing DMS assay NP_001034680.2:  15%|▍  | 231/1555 [00:27<02:43,  8.08it/s]NP_001034680.2: DMS=2, merged=2
Processing DMS assay NP_001035232.1:  15%|▍  | 232/1555 [00:27<02:41,  8.19it/s]NP_001035232.1: DMS=7, merged=7
Processing DMS assay NP_001035526.1:  15%|▍  | 233/1555 [00:27<02:41,  8.17it/s]NP_001035526.1: DMS=1, merged=1
Processing DMS assay NP_001035806.1:  15%|▍  | 234/1555 [00:27<02:38,  8.34it/s]NP_001035806.1: DMS=1, merged=1
Processing DMS assay NP_001035937.1:  15%|▍  | 235/1555 [00:28<02:36,  8.45it/s]NP_001035937.1: DMS=1, merged=1
Processing DMS assay NP_001035957.1:  15%|▍  | 236/1555 [00:28<02:34,  8.52it/s]Note: HMM scored 28/29 mutants for NP_001035957.1; rest left as NaN.
NP_001035957.1: DMS=29, merged=29
Processing DMS assay NP_001036167.1:  15%|▍  | 237/1555 [00:28<02:48,  7.84it/s]NP_001036167.1: DMS=1, merged=1
Processing DMS assay NP_001041639.1:  15%|▍  | 238/1555 [00:28<02:42,  8.12it/s]NP_001041639.1: DMS=4, merged=4
Processing DMS assay NP_001070833.1:  15%|▍  | 239/1555 [00:28<02:40,  8.21it/s]NP_001070833.1: DMS=2, merged=2
Processing DMS assay NP_001071.1:  15%|▉     | 240/1555 [00:28<02:37,  8.36it/s]NP_001071.1: DMS=3, merged=3
Processing DMS assay NP_001073911.1:  15%|▍  | 241/1555 [00:28<02:42,  8.09it/s]NP_001073911.1: DMS=1, merged=1
Processing DMS assay NP_001073936.1:  16%|▍  | 242/1555 [00:28<02:37,  8.32it/s]Note: HMM scored 1/2 mutants for NP_001073936.1; rest left as NaN.
NP_001073936.1: DMS=2, merged=2
Processing DMS assay NP_001076585.1:  16%|▍  | 243/1555 [00:28<02:34,  8.47it/s]NP_001076585.1: DMS=1, merged=1
Processing DMS assay NP_001077083.1:  16%|▍  | 244/1555 [00:29<02:32,  8.58it/s]NP_001077083.1: DMS=1, merged=1
Processing DMS assay NP_001077431.1:  16%|▍  | 245/1555 [00:29<02:35,  8.43it/s]NP_001077431.1: DMS=3, merged=3
Processing DMS assay NP_001091.1:  16%|▉     | 246/1555 [00:29<02:59,  7.31it/s]NP_001091.1: DMS=2, merged=2
Processing DMS assay NP_001092.1:  16%|▉     | 247/1555 [00:29<02:56,  7.41it/s]NP_001092.1: DMS=2, merged=2
Processing DMS assay NP_001093327.1:  16%|▍  | 248/1555 [00:29<02:50,  7.68it/s]NP_001093327.1: DMS=2, merged=2
Processing DMS assay NP_001094896.1:  16%|▍  | 249/1555 [00:29<02:44,  7.92it/s]NP_001094896.1: DMS=1, merged=1
Processing DMS assay NP_001096034.1:  16%|▍  | 250/1555 [00:29<02:39,  8.19it/s]NP_001096034.1: DMS=1, merged=1
Processing DMS assay NP_001098101.1:  16%|▍  | 251/1555 [00:30<02:42,  8.01it/s]NP_001098101.1: DMS=1, merged=1
Processing DMS assay NP_001103348.1:  16%|▍  | 252/1555 [00:30<02:39,  8.19it/s]NP_001103348.1: DMS=1, merged=1
Processing DMS assay NP_001103824.1:  16%|▍  | 253/1555 [00:30<02:35,  8.37it/s]NP_001103824.1: DMS=1, merged=1
Processing DMS assay NP_001104026.1:  16%|▍  | 254/1555 [00:30<02:32,  8.56it/s]Note: HMM scored 3/4 mutants for NP_001104026.1; rest left as NaN.
NP_001104026.1: DMS=4, merged=4
Processing DMS assay NP_001104262.1:  16%|▍  | 255/1555 [00:30<02:32,  8.55it/s]Note: HMM scored 5/15 mutants for NP_001104262.1; rest left as NaN.
NP_001104262.1: DMS=15, merged=15
Processing DMS assay NP_001108225.1:  16%|▍  | 256/1555 [00:30<02:33,  8.49it/s]NP_001108225.1: DMS=4, merged=4
Processing DMS assay NP_001116102.1:  17%|▍  | 257/1555 [00:30<02:33,  8.46it/s]Note: HMM scored 1/10 mutants for NP_001116102.1; rest left as NaN.
NP_001116102.1: DMS=10, merged=10
Processing DMS assay NP_001116427.1:  17%|▍  | 258/1555 [00:30<02:34,  8.42it/s]NP_001116427.1: DMS=1, merged=1
Processing DMS assay NP_001116857.1:  17%|▍  | 259/1555 [00:30<02:32,  8.52it/s]Note: HMM scored 1/2 mutants for NP_001116857.1; rest left as NaN.
NP_001116857.1: DMS=2, merged=2
Processing DMS assay NP_001119580.2:  17%|▌  | 260/1555 [00:31<02:33,  8.45it/s]NP_001119580.2: DMS=1, merged=1
Processing DMS assay NP_001120694.1:  17%|▌  | 261/1555 [00:31<02:31,  8.54it/s]Note: HMM scored 4/10 mutants for NP_001120694.1; rest left as NaN.
NP_001120694.1: DMS=10, merged=10
Processing DMS assay NP_001120864.1:  17%|▌  | 262/1555 [00:31<02:44,  7.87it/s]NP_001120864.1: DMS=1, merged=1
Processing DMS assay NP_001121636.1:  17%|▌  | 263/1555 [00:31<02:40,  8.07it/s]Note: HMM scored 4/6 mutants for NP_001121636.1; rest left as NaN.
NP_001121636.1: DMS=6, merged=6
Processing DMS assay NP_001121697.2:  17%|▌  | 264/1555 [00:31<02:39,  8.11it/s]NP_001121697.2: DMS=1, merged=1
Processing DMS assay NP_001123910.1:  17%|▌  | 265/1555 [00:31<02:36,  8.27it/s]NP_001123910.1: DMS=13, merged=13
Processing DMS assay NP_001127879.1:  17%|▌  | 266/1555 [00:31<02:39,  8.08it/s]Note: HMM scored 2/3 mutants for NP_001127879.1; rest left as NaN.
NP_001127879.1: DMS=3, merged=3
Processing DMS assay NP_001128145.1:  17%|▌  | 267/1555 [00:31<02:38,  8.14it/s]NP_001128145.1: DMS=1, merged=1
Processing DMS assay NP_001130.1:  17%|█     | 268/1555 [00:32<02:35,  8.30it/s]NP_001130.1: DMS=3, merged=3
Processing DMS assay NP_001133.1:  17%|█     | 269/1555 [00:32<02:33,  8.40it/s]NP_001133.1: DMS=1, merged=1
Processing DMS assay NP_001136256.1:  17%|▌  | 270/1555 [00:32<02:31,  8.47it/s]NP_001136256.1: DMS=1, merged=1
Processing DMS assay NP_001136272.1:  17%|▌  | 271/1555 [00:32<02:32,  8.44it/s]NP_001136272.1: DMS=2, merged=2
Processing DMS assay NP_001138830.1:  17%|▌  | 272/1555 [00:32<02:31,  8.49it/s]NP_001138830.1: DMS=1, merged=1
Processing DMS assay NP_001153171.1:  18%|▌  | 273/1555 [00:32<02:34,  8.29it/s]NP_001153171.1: DMS=2, merged=2
Processing DMS assay NP_001157749.1:  18%|▌  | 274/1555 [00:32<02:31,  8.43it/s]NP_001157749.1: DMS=1, merged=1
Processing DMS assay NP_001159435.1:  18%|▌  | 275/1555 [00:32<02:30,  8.49it/s]NP_001159435.1: DMS=21, merged=21
Processing DMS assay NP_001162.5:  18%|█     | 276/1555 [00:33<02:36,  8.18it/s]NP_001162.5: DMS=3, merged=3
Processing DMS assay NP_001167560.1:  18%|▌  | 277/1555 [00:33<02:34,  8.25it/s]NP_001167560.1: DMS=1, merged=1
Processing DMS assay NP_001167618.1:  18%|▌  | 278/1555 [00:33<02:33,  8.32it/s]NP_001167618.1: DMS=2, merged=2
Processing DMS assay NP_001171809.1:  18%|▌  | 279/1555 [00:33<02:32,  8.39it/s]Note: HMM scored 1/2 mutants for NP_001171809.1; rest left as NaN.

NP_001171809.1: DMS=2, merged=2
Processing DMS assay NP_001174.2:  18%|█     | 280/1555 [00:33<02:34,  8.27it/s]Note: HMM scored 2/4 mutants for NP_001174.2; rest left as NaN.
NP_001174.2: DMS=4, merged=4
Processing DMS assay NP_001177203.1:  18%|▌  | 281/1555 [00:33<02:32,  8.33it/s]Note: HMM scored 3/12 mutants for NP_001177203.1; rest left as NaN.
NP_001177203.1: DMS=12, merged=12
Processing DMS assay NP_001182482.1:  18%|▌  | 282/1555 [00:33<02:33,  8.31it/s]NP_001182482.1: DMS=4, merged=4
Processing DMS assay NP_001184033.1:  18%|▌  | 283/1555 [00:33<02:39,  7.96it/s]Note: HMM scored 2/5 mutants for NP_001184033.1; rest left as NaN.
NP_001184033.1: DMS=5, merged=5
Processing DMS assay NP_001193908.1:  18%|▌  | 284/1555 [00:33<02:39,  7.96it/s]NP_001193908.1: DMS=1, merged=1
Processing DMS assay NP_001193927.1:  18%|▌  | 285/1555 [00:34<02:36,  8.12it/s]NP_001193927.1: DMS=1, merged=1
Processing DMS assay NP_001194.1:  18%|█     | 286/1555 [00:34<02:33,  8.28it/s]NP_001194.1: DMS=1, merged=1
Processing DMS assay NP_001195.2:  18%|█     | 287/1555 [00:34<02:31,  8.39it/s]NP_001195.2: DMS=2, merged=2
Processing DMS assay NP_001203.1:  19%|█     | 288/1555 [00:34<02:32,  8.32it/s]NP_001203.1: DMS=1, merged=1
Processing DMS assay NP_001229825.1:  19%|▌  | 289/1555 [00:34<02:30,  8.42it/s]NP_001229825.1: DMS=2, merged=2
Processing DMS assay NP_001230937.1:  19%|▌  | 290/1555 [00:34<02:31,  8.34it/s]Note: HMM scored 4/7 mutants for NP_001230937.1; rest left as NaN.
NP_001230937.1: DMS=7, merged=7
Processing DMS assay NP_001241.1:  19%|█     | 291/1555 [00:34<02:32,  8.28it/s]NP_001241.1: DMS=1, merged=1
Processing DMS assay NP_001243.1:  19%|█▏    | 292/1555 [00:34<02:30,  8.39it/s]NP_001243.1: DMS=1, merged=1
Processing DMS assay NP_001243000.2:  19%|▌  | 293/1555 [00:35<02:30,  8.41it/s]NP_001243000.2: DMS=2, merged=2
Processing DMS assay NP_001243718.1:  19%|▌  | 294/1555 [00:35<02:50,  7.41it/s]Note: HMM scored 1/3 mutants for NP_001243718.1; rest left as NaN.
NP_001243718.1: DMS=3, merged=3
Processing DMS assay NP_001244025.1:  19%|▌  | 295/1555 [00:35<02:53,  7.25it/s]NP_001244025.1: DMS=1, merged=1
Processing DMS assay NP_001245321.1:  19%|▌  | 296/1555 [00:35<02:46,  7.57it/s]NP_001245321.1: DMS=1, merged=1
Processing DMS assay NP_001258822.1:  19%|▌  | 297/1555 [00:35<02:38,  7.92it/s]NP_001258822.1: DMS=1, merged=1
Processing DMS assay NP_001258867.1:  19%|▌  | 298/1555 [00:35<02:36,  8.05it/s]NP_001258867.1: DMS=1, merged=1
Processing DMS assay NP_001262.3:  19%|█▏    | 299/1555 [00:35<02:32,  8.25it/s]Note: HMM scored 3/4 mutants for NP_001262.3; rest left as NaN.
NP_001262.3: DMS=4, merged=4
Processing DMS assay NP_001263274.1:  19%|▌  | 300/1555 [00:35<02:31,  8.26it/s]NP_001263274.1: DMS=3, merged=3
Processing DMS assay NP_001264044.1:  19%|▌  | 301/1555 [00:36<02:33,  8.15it/s]Note: HMM scored 1/2 mutants for NP_001264044.1; rest left as NaN.
NP_001264044.1: DMS=2, merged=2
Processing DMS assay NP_001265441.1:  19%|▌  | 302/1555 [00:36<02:34,  8.11it/s]NP_001265441.1: DMS=1, merged=1
Processing DMS assay NP_001265645.1:  19%|▌  | 303/1555 [00:36<02:30,  8.34it/s]NP_001265645.1: DMS=1, merged=1
Processing DMS assay NP_001268669.1:  20%|▌  | 304/1555 [00:36<02:33,  8.13it/s]NP_001268669.1: DMS=1, merged=1
Processing DMS assay NP_001269154.1:  20%|▌  | 305/1555 [00:36<02:30,  8.31it/s]NP_001269154.1: DMS=1, merged=1
Processing DMS assay NP_001269646.1:  20%|▌  | 306/1555 [00:36<02:30,  8.30it/s]NP_001269646.1: DMS=1, merged=1
Processing DMS assay NP_001269938.1:  20%|▌  | 307/1555 [00:36<02:27,  8.48it/s]Note: HMM scored 1/2 mutants for NP_001269938.1; rest left as NaN.
NP_001269938.1: DMS=2, merged=2
Processing DMS assay NP_001278344.1:  20%|▌  | 308/1555 [00:36<02:26,  8.50it/s]Note: HMM scored 1/3 mutants for NP_001278344.1; rest left as NaN.
NP_001278344.1: DMS=3, merged=3
Processing DMS assay NP_001289.1:  20%|█▏    | 309/1555 [00:37<02:25,  8.57it/s]NP_001289.1: DMS=1, merged=1
Processing DMS assay NP_001299838.1:  20%|▌  | 310/1555 [00:37<02:24,  8.63it/s]Note: HMM scored 1/2 mutants for NP_001299838.1; rest left as NaN.
NP_001299838.1: DMS=2, merged=2
Processing DMS assay NP_001308049.1:  20%|▌  | 311/1555 [00:37<02:24,  8.62it/s]NP_001308049.1: DMS=1, merged=1
Processing DMS assay NP_001310218.1:  20%|▌  | 312/1555 [00:37<02:22,  8.71it/s]Note: HMM scored 2/4 mutants for NP_001310218.1; rest left as NaN.
NP_001310218.1: DMS=4, merged=4
Processing DMS assay NP_001317217.1:  20%|▌  | 313/1555 [00:37<02:24,  8.60it/s]NP_001317217.1: DMS=1, merged=1
Processing DMS assay NP_001317629.1:  20%|▌  | 314/1555 [00:37<02:23,  8.64it/s]NP_001317629.1: DMS=1, merged=1
Processing DMS assay NP_001334650.1:  20%|▌  | 315/1555 [00:37<02:30,  8.26it/s]Note: HMM scored 3/4 mutants for NP_001334650.1; rest left as NaN.
NP_001334650.1: DMS=4, merged=4
Processing DMS assay NP_001336813.1:  20%|▌  | 316/1555 [00:37<02:28,  8.34it/s]NP_001336813.1: DMS=2, merged=2
Processing DMS assay NP_001340274.1:  20%|▌  | 317/1555 [00:37<02:25,  8.52it/s]NP_001340274.1: DMS=1, merged=1
Processing DMS assay NP_001341533.1:  20%|▌  | 318/1555 [00:38<02:23,  8.63it/s]NP_001341533.1: DMS=1, merged=1
Processing DMS assay NP_001341569.1:  21%|▌  | 319/1555 [00:38<02:21,  8.71it/s]NP_001341569.1: DMS=1, merged=1
Processing DMS assay NP_001341641.1:  21%|▌  | 320/1555 [00:38<02:21,  8.74it/s]NP_001341641.1: DMS=2, merged=2
Processing DMS assay NP_001346945.1:  21%|▌  | 321/1555 [00:38<02:21,  8.69it/s]NP_001346945.1: DMS=6, merged=6
Processing DMS assay NP_001347.3:  21%|█▏    | 322/1555 [00:38<02:23,  8.57it/s]NP_001347.3: DMS=7, merged=7
Processing DMS assay NP_001350047.1:  21%|▌  | 323/1555 [00:38<02:25,  8.47it/s]NP_001350047.1: DMS=1, merged=1
Processing DMS assay NP_001351.2:  21%|█▎    | 324/1555 [00:38<02:23,  8.58it/s]NP_001351.2: DMS=1, merged=1
Processing DMS assay NP_001352017.1:  21%|▋  | 325/1555 [00:38<02:27,  8.32it/s]NP_001352017.1: DMS=1, merged=1
Processing DMS assay NP_001352465.1:  21%|▋  | 326/1555 [00:39<02:25,  8.47it/s]NP_001352465.1: DMS=1, merged=1
Processing DMS assay NP_001352928.1:  21%|▋  | 327/1555 [00:39<02:23,  8.58it/s]NP_001352928.1: DMS=1, merged=1
Processing DMS assay NP_001353314.1:  21%|▋  | 328/1555 [00:39<02:21,  8.66it/s]NP_001353314.1: DMS=1, merged=1
Processing DMS assay NP_001354.1:  21%|█▎    | 329/1555 [00:39<02:20,  8.75it/s]Note: HMM scored 1/6 mutants for NP_001354.1; rest left as NaN.
NP_001354.1: DMS=6, merged=6
Processing DMS assay NP_001354650.1:  21%|▋  | 330/1555 [00:39<02:21,  8.64it/s]NP_001354650.1: DMS=2, merged=2
Processing DMS assay NP_001355823.1:  21%|▋  | 331/1555 [00:39<02:22,  8.61it/s]NP_001355823.1: DMS=2, merged=2
Processing DMS assay NP_001357029.1:  21%|▋  | 332/1555 [00:39<02:22,  8.59it/s]Note: HMM scored 1/2 mutants for NP_001357029.1; rest left as NaN.
NP_001357029.1: DMS=2, merged=2
Processing DMS assay NP_001357188.2:  21%|▋  | 333/1555 [00:39<02:23,  8.50it/s]NP_001357188.2: DMS=4, merged=4
Processing DMS assay NP_001357524.1:  21%|▋  | 334/1555 [00:39<02:22,  8.60it/s]NP_001357524.1: DMS=1, merged=1
Processing DMS assay NP_001357587.1:  22%|▋  | 335/1555 [00:40<02:20,  8.67it/s]NP_001357587.1: DMS=1, merged=1
Processing DMS assay NP_001360.1:  22%|█▎    | 336/1555 [00:40<02:25,  8.39it/s]NP_001360.1: DMS=1, merged=1
Processing DMS assay NP_001361282.1:  22%|▋  | 337/1555 [00:40<02:22,  8.53it/s]NP_001361282.1: DMS=1, merged=1
Processing DMS assay NP_001361314.1:  22%|▋  | 338/1555 [00:40<02:21,  8.62it/s]NP_001361314.1: DMS=2, merged=2
Processing DMS assay NP_001361433.1:  22%|▋  | 339/1555 [00:40<02:20,  8.68it/s]NP_001361433.1: DMS=1, merged=1
Processing DMS assay NP_001361552.1:  22%|▋  | 340/1555 [00:40<02:18,  8.76it/s]NP_001361552.1: DMS=1, merged=1
Processing DMS assay NP_001361757.1:  22%|▋  | 341/1555 [00:40<02:18,  8.74it/s]Note: HMM scored 1/24 mutants for NP_001361757.1; rest left as NaN.
NP_001361757.1: DMS=24, merged=24
Processing DMS assay NP_001362309.1:  22%|▋  | 342/1555 [00:40<02:26,  8.27it/s]NP_001362309.1: DMS=3, merged=3
Processing DMS assay NP_001364194.1:  22%|▋  | 343/1555 [00:41<02:25,  8.33it/s]NP_001364194.1: DMS=1, merged=1
Processing DMS assay NP_001365112.1:  22%|▋  | 344/1555 [00:41<02:22,  8.50it/s]NP_001365112.1: DMS=1, merged=1
Processing DMS assay NP_001365381.1:  22%|▋  | 345/1555 [00:41<02:20,  8.61it/s]NP_001365381.1: DMS=2, merged=2
Processing DMS assay NP_001365383.1:  22%|▋  | 346/1555 [00:41<02:25,  8.29it/s]Note: HMM scored 1/7 mutants for NP_001365383.1; rest left as NaN.
NP_001365383.1: DMS=7, merged=7
Processing DMS assay NP_001365544.1:  22%|▋  | 347/1555 [00:41<02:26,  8.26it/s]Note: HMM scored 1/2 mutants for NP_001365544.1; rest left as NaN.
NP_001365544.1: DMS=2, merged=2
Processing DMS assay NP_001365898.1:  22%|▋  | 348/1555 [00:41<02:24,  8.37it/s]NP_001365898.1: DMS=1, merged=1
Processing DMS assay NP_001365958.1:  22%|▋  | 349/1555 [00:41<02:21,  8.55it/s]NP_001365958.1: DMS=1, merged=1
Processing DMS assay NP_001366039.1:  23%|▋  | 350/1555 [00:41<02:20,  8.58it/s]NP_001366039.1: DMS=3, merged=3
Processing DMS assay NP_001366220.1:  23%|▋  | 351/1555 [00:41<02:21,  8.53it/s]NP_001366220.1: DMS=1, merged=1
Processing DMS assay NP_001366332.1:  23%|▋  | 352/1555 [00:42<02:20,  8.57it/s]NP_001366332.1: DMS=1, merged=1
Processing DMS assay NP_001366539.1:  23%|▋  | 353/1555 [00:42<02:19,  8.63it/s]NP_001366539.1: DMS=1, merged=1
Processing DMS assay NP_001367.2:  23%|█▎    | 354/1555 [00:42<02:18,  8.67it/s]NP_001367.2: DMS=1, merged=1
Processing DMS assay NP_001368.2:  23%|█▎    | 355/1555 [00:42<02:17,  8.70it/s]NP_001368.2: DMS=3, merged=3
Processing DMS assay NP_001371839.1:  23%|▋  | 356/1555 [00:42<02:19,  8.57it/s]NP_001371839.1: DMS=2, merged=2
Processing DMS assay NP_001373322.1:  23%|▋  | 357/1555 [00:42<02:25,  8.25it/s]NP_001373322.1: DMS=2, merged=2
Processing DMS assay NP_001405.1:  23%|█▍    | 358/1555 [00:42<02:23,  8.36it/s]NP_001405.1: DMS=1, merged=1
Processing DMS assay NP_001420.2:  23%|█▍    | 359/1555 [00:42<02:19,  8.58it/s]Note: HMM scored 3/4 mutants for NP_001420.2; rest left as NaN.
NP_001420.2: DMS=4, merged=4
Processing DMS assay NP_001444.2:  23%|█▍    | 360/1555 [00:43<02:20,  8.48it/s]Note: HMM scored 5/20 mutants for NP_001444.2; rest left as NaN.
NP_001444.2: DMS=20, merged=20
Processing DMS assay NP_001483.3:  23%|█▍    | 361/1555 [00:43<02:23,  8.32it/s]Note: HMM scored 1/3 mutants for NP_001483.3; rest left as NaN.
NP_001483.3: DMS=3, merged=3
Processing DMS assay NP_001646.2:  23%|█▍    | 362/1555 [00:43<02:22,  8.38it/s]NP_001646.2: DMS=1, merged=1
Processing DMS assay NP_001664.3:  23%|█▍    | 363/1555 [00:43<02:18,  8.59it/s]NP_001664.3: DMS=1, merged=1
Processing DMS assay NP_001684.2:  23%|█▍    | 364/1555 [00:43<02:16,  8.73it/s]NP_001684.2: DMS=1, merged=1
Processing DMS assay NP_001724.4:  23%|█▍    | 365/1555 [00:43<02:15,  8.81it/s]NP_001724.4: DMS=2, merged=2
Processing DMS assay NP_001725.1:  24%|█▍    | 366/1555 [00:43<02:14,  8.82it/s]NP_001725.1: DMS=1, merged=1
Processing DMS assay NP_001796.2:  24%|█▍    | 367/1555 [00:43<02:15,  8.79it/s]NP_001796.2: DMS=1, merged=1
Processing DMS assay NP_001805.4:  24%|█▍    | 368/1555 [00:43<02:18,  8.57it/s]NP_001805.4: DMS=1, merged=1
Processing DMS assay NP_001835.3:  24%|█▍    | 369/1555 [00:44<02:16,  8.68it/s]NP_001835.3: DMS=12, merged=12
Processing DMS assay NP_001839.2:  24%|█▍    | 370/1555 [00:44<02:19,  8.52it/s]NP_001839.2: DMS=3, merged=3
Processing DMS assay NP_001840.3:  24%|█▍    | 371/1555 [00:44<02:18,  8.52it/s]NP_001840.3: DMS=1, merged=1
Processing DMS assay NP_001845.3:  24%|█▍    | 372/1555 [00:44<02:16,  8.67it/s]NP_001845.3: DMS=3, merged=3
Processing DMS assay NP_001866.2:  24%|█▍    | 373/1555 [00:44<02:16,  8.65it/s]NP_001866.2: DMS=2, merged=2
Processing DMS assay NP_001867.2:  24%|█▍    | 374/1555 [00:44<02:16,  8.67it/s]NP_001867.2: DMS=1, merged=1
Processing DMS assay NP_001877.1:  24%|█▍    | 375/1555 [00:44<02:14,  8.78it/s]NP_001877.1: DMS=1, merged=1
Processing DMS assay NP_001895.1:  24%|█▍    | 376/1555 [00:44<02:12,  8.87it/s]NP_001895.1: DMS=1, merged=1
Processing DMS assay NP_001900.1:  24%|█▍    | 377/1555 [00:44<02:11,  8.93it/s]NP_001900.1: DMS=1, merged=1
Processing DMS assay NP_001918.3:  24%|█▍    | 378/1555 [00:45<02:18,  8.50it/s]NP_001918.3: DMS=5, merged=5
Processing DMS assay NP_001922.2:  24%|█▍    | 379/1555 [00:45<02:18,  8.50it/s]NP_001922.2: DMS=1, merged=1
Processing DMS assay NP_001944.1:  24%|█▍    | 380/1555 [00:45<02:16,  8.60it/s]NP_001944.1: DMS=3, merged=3
Processing DMS assay NP_001963.1:  25%|█▍    | 381/1555 [00:45<02:16,  8.57it/s]NP_001963.1: DMS=1, merged=1
Processing DMS assay NP_001978.1:  25%|█▍    | 382/1555 [00:45<02:17,  8.54it/s]NP_001978.1: DMS=1, merged=1
Processing DMS assay NP_001990.2:  25%|█▍    | 383/1555 [00:45<02:17,  8.52it/s]NP_001990.2: DMS=1, merged=1
Processing DMS assay NP_002026.1:  25%|█▍    | 384/1555 [00:45<02:17,  8.49it/s]NP_002026.1: DMS=1, merged=1
Processing DMS assay NP_002058.2:  25%|█▍    | 385/1555 [00:45<02:17,  8.54it/s]NP_002058.2: DMS=1, merged=1
Processing DMS assay NP_002060.4:  25%|█▍    | 386/1555 [00:46<02:17,  8.51it/s]NP_002060.4: DMS=1, merged=1
Processing DMS assay NP_002065.1:  25%|█▍    | 387/1555 [00:46<02:16,  8.55it/s]NP_002065.1: DMS=1, merged=1
Processing DMS assay NP_002066.1:  25%|█▍    | 388/1555 [00:46<02:15,  8.59it/s]NP_002066.1: DMS=1, merged=1
Processing DMS assay NP_002070.1:  25%|█▌    | 389/1555 [00:46<02:21,  8.24it/s]NP_002070.1: DMS=1, merged=1
Processing DMS assay NP_002071.2:  25%|█▌    | 390/1555 [00:46<02:20,  8.30it/s]NP_002071.2: DMS=1, merged=1
Processing DMS assay NP_002100.2:  25%|█▌    | 391/1555 [00:46<02:18,  8.42it/s]NP_002100.2: DMS=2, merged=2
Processing DMS assay NP_002172.2:  25%|█▌    | 392/1555 [00:46<02:16,  8.50it/s]NP_002172.2: DMS=2, merged=2
Processing DMS assay NP_002221.1:  25%|█▌    | 393/1555 [00:46<02:16,  8.51it/s]NP_002221.1: DMS=1, merged=1
Processing DMS assay NP_002231.1:  25%|█▌    | 394/1555 [00:46<02:15,  8.58it/s]NP_002231.1: DMS=1, merged=1
Processing DMS assay NP_002263.3:  25%|█▌    | 395/1555 [00:47<02:12,  8.72it/s]NP_002263.3: DMS=2, merged=2
Processing DMS assay NP_002372.1:  25%|█▌    | 396/1555 [00:47<02:12,  8.75it/s]NP_002372.1: DMS=1, merged=1
Processing DMS assay NP_002428.1:  26%|█▌    | 397/1555 [00:47<02:10,  8.86it/s]NP_002428.1: DMS=1, merged=1
Processing DMS assay NP_002440.2:  26%|█▌    | 398/1555 [00:47<02:10,  8.89it/s]NP_002440.2: DMS=1, merged=1
Processing DMS assay NP_002445.2:  26%|█▌    | 399/1555 [00:47<02:10,  8.89it/s]NP_002445.2: DMS=1, merged=1
Processing DMS assay NP_002459.3:  26%|█▌    | 400/1555 [00:47<02:15,  8.52it/s]NP_002459.3: DMS=1, merged=1
Processing DMS assay NP_002461.2:  26%|█▌    | 401/1555 [00:47<02:14,  8.57it/s]NP_002461.2: DMS=4, merged=4
Processing DMS assay NP_002464.1:  26%|█▌    | 402/1555 [00:47<02:15,  8.48it/s]NP_002464.1: DMS=1, merged=1
Processing DMS assay NP_002476.2:  26%|█▌    | 403/1555 [00:48<02:15,  8.52it/s]NP_002476.2: DMS=1, merged=1
Processing DMS assay NP_002523.2:  26%|█▌    | 404/1555 [00:48<02:14,  8.57it/s]NP_002523.2: DMS=1, merged=1
Processing DMS assay NP_002537.3:  26%|█▌    | 405/1555 [00:48<02:13,  8.61it/s]NP_002537.3: DMS=1, merged=1
Processing DMS assay NP_002600.1:  26%|█▌    | 406/1555 [00:48<02:12,  8.66it/s]NP_002600.1: DMS=3, merged=3
Processing DMS assay NP_002606.3:  26%|█▌    | 407/1555 [00:48<02:14,  8.51it/s]NP_002606.3: DMS=1, merged=1
Processing DMS assay NP_002626.1:  26%|█▌    | 408/1555 [00:48<02:13,  8.61it/s]NP_002626.1: DMS=1, merged=1
Processing DMS assay NP_002632.1:  26%|█▌    | 409/1555 [00:48<02:11,  8.69it/s]NP_002632.1: DMS=1, merged=1
Processing DMS assay NP_002668.1:  26%|█▌    | 410/1555 [00:48<02:11,  8.68it/s]NP_002668.1: DMS=1, merged=1
Processing DMS assay NP_002682.2:  26%|█▌    | 411/1555 [00:48<02:18,  8.28it/s]NP_002682.2: DMS=1, merged=1
Processing DMS assay NP_002684.1:  26%|█▌    | 412/1555 [00:49<02:15,  8.42it/s]Note: HMM scored 3/13 mutants for NP_002684.1; rest left as NaN.
NP_002684.1: DMS=13, merged=13
Processing DMS assay NP_002706.1:  27%|█▌    | 413/1555 [00:49<02:17,  8.29it/s]NP_002706.1: DMS=1, merged=1
Processing DMS assay NP_002721.1:  27%|█▌    | 414/1555 [00:49<02:16,  8.34it/s]NP_002721.1: DMS=1, merged=1

Processing DMS assay NP_002730.1:  27%|█▌    | 415/1555 [00:49<02:14,  8.50it/s]NP_002730.1: DMS=1, merged=1
Processing DMS assay NP_002736.3:  27%|█▌    | 416/1555 [00:49<02:12,  8.62it/s]NP_002736.3: DMS=1, merged=1
Processing DMS assay NP_002746.1:  27%|█▌    | 417/1555 [00:49<02:10,  8.74it/s]NP_002746.1: DMS=2, merged=2
Processing DMS assay NP_002769.1:  27%|█▌    | 418/1555 [00:49<02:10,  8.68it/s]NP_002769.1: DMS=2, merged=2
Processing DMS assay NP_002779.1:  27%|█▌    | 419/1555 [00:49<02:12,  8.60it/s]NP_002779.1: DMS=1, merged=1
Processing DMS assay NP_002787.2:  27%|█▌    | 420/1555 [00:49<02:12,  8.55it/s]NP_002787.2: DMS=1, merged=1
Processing DMS assay NP_002825.3:  27%|█▌    | 421/1555 [00:50<02:11,  8.61it/s]NP_002825.3: DMS=3, merged=3
Processing DMS assay NP_002829.3:  27%|█▋    | 422/1555 [00:50<02:17,  8.24it/s]NP_002829.3: DMS=1, merged=1
Processing DMS assay NP_002878.2:  27%|█▋    | 423/1555 [00:50<02:14,  8.43it/s]NP_002878.2: DMS=1, merged=1
Processing DMS assay NP_002896.2:  27%|█▋    | 424/1555 [00:50<02:12,  8.52it/s]NP_002896.2: DMS=1, merged=1
Processing DMS assay NP_002991.2:  27%|█▋    | 425/1555 [00:50<02:10,  8.67it/s]NP_002991.2: DMS=1, merged=1
Processing DMS assay NP_002993.1:  27%|█▋    | 426/1555 [00:50<02:09,  8.74it/s]NP_002993.1: DMS=4, merged=4
Processing DMS assay NP_003033.3:  27%|█▋    | 427/1555 [00:50<02:09,  8.68it/s]NP_003033.3: DMS=2, merged=2
Processing DMS assay NP_003051.1:  28%|█▋    | 428/1555 [00:50<02:09,  8.68it/s]NP_003051.1: DMS=2, merged=2
Processing DMS assay NP_003063.2:  28%|█▋    | 429/1555 [00:51<02:09,  8.67it/s]NP_003063.2: DMS=3, merged=3
Processing DMS assay NP_003064.2:  28%|█▋    | 430/1555 [00:51<02:10,  8.59it/s]NP_003064.2: DMS=2, merged=2
Processing DMS assay NP_003065.3:  28%|█▋    | 431/1555 [00:51<02:11,  8.54it/s]NP_003065.3: DMS=1, merged=1
Processing DMS assay NP_003110.1:  28%|█▋    | 432/1555 [00:51<02:10,  8.61it/s]NP_003110.1: DMS=2, merged=2
Processing DMS assay NP_003117.2:  28%|█▋    | 433/1555 [00:51<02:17,  8.18it/s]NP_003117.2: DMS=2, merged=2
Processing DMS assay NP_003127.1:  28%|█▋    | 434/1555 [00:51<02:16,  8.21it/s]NP_003127.1: DMS=1, merged=1
Processing DMS assay NP_003163.1:  28%|█▋    | 435/1555 [00:51<02:14,  8.31it/s]NP_003163.1: DMS=2, merged=2
Processing DMS assay NP_003273.1:  28%|█▋    | 436/1555 [00:51<02:14,  8.30it/s]NP_003273.1: DMS=2, merged=2
Processing DMS assay NP_003280.2:  28%|█▋    | 437/1555 [00:52<02:15,  8.28it/s]NP_003280.2: DMS=5, merged=5
Processing DMS assay NP_003292.1:  28%|█▋    | 438/1555 [00:52<02:14,  8.34it/s]NP_003292.1: DMS=1, merged=1
Processing DMS assay NP_003313.3:  28%|█▋    | 439/1555 [00:52<02:11,  8.48it/s]NP_003313.3: DMS=1, merged=1
Processing DMS assay NP_003327.2:  28%|█▋    | 440/1555 [00:52<02:09,  8.60it/s]NP_003327.2: DMS=1, merged=1
Processing DMS assay NP_003352.2:  28%|█▋    | 441/1555 [00:52<02:08,  8.64it/s]NP_003352.2: DMS=2, merged=2
Processing DMS assay NP_003385.2:  28%|█▋    | 442/1555 [00:52<02:09,  8.61it/s]NP_003385.2: DMS=1, merged=1
Processing DMS assay NP_003403.2:  28%|█▋    | 443/1555 [00:52<02:08,  8.66it/s]NP_003403.2: DMS=1, merged=1
Processing DMS assay NP_003404.1:  29%|█▋    | 444/1555 [00:52<02:14,  8.25it/s]Note: HMM scored 1/2 mutants for NP_003404.1; rest left as NaN.
NP_003404.1: DMS=2, merged=2
Processing DMS assay NP_003459.2:  29%|█▋    | 445/1555 [00:52<02:12,  8.39it/s]NP_003459.2: DMS=1, merged=1
Processing DMS assay NP_003473.3:  29%|█▋    | 446/1555 [00:53<02:10,  8.50it/s]Note: HMM scored 3/8 mutants for NP_003473.3; rest left as NaN.
NP_003473.3: DMS=8, merged=8
Processing DMS assay NP_003551.2:  29%|█▋    | 447/1555 [00:53<02:14,  8.22it/s]NP_003551.2: DMS=1, merged=1
Processing DMS assay NP_003562.1:  29%|█▋    | 448/1555 [00:53<02:13,  8.30it/s]NP_003562.1: DMS=1, merged=1
Processing DMS assay NP_003592.3:  29%|█▋    | 449/1555 [00:53<02:11,  8.43it/s]NP_003592.3: DMS=1, merged=1
Processing DMS assay NP_003602.1:  29%|█▋    | 450/1555 [00:53<02:09,  8.56it/s]NP_003602.1: DMS=1, merged=1
Processing DMS assay NP_003713.3:  29%|█▋    | 451/1555 [00:53<02:07,  8.63it/s]NP_003713.3: DMS=5, merged=5
Processing DMS assay NP_003733.2:  29%|█▋    | 452/1555 [00:53<02:09,  8.54it/s]NP_003733.2: DMS=1, merged=1
Processing DMS assay NP_003784.2:  29%|█▋    | 453/1555 [00:53<02:12,  8.34it/s]NP_003784.2: DMS=1, merged=1
Processing DMS assay NP_003892.2:  29%|█▊    | 454/1555 [00:54<02:16,  8.06it/s]NP_003892.2: DMS=1, merged=1
Processing DMS assay NP_003910.1:  29%|█▊    | 455/1555 [00:54<02:12,  8.28it/s]NP_003910.1: DMS=1, merged=1
Processing DMS assay NP_003912.1:  29%|█▊    | 456/1555 [00:54<02:10,  8.45it/s]NP_003912.1: DMS=1, merged=1
Processing DMS assay NP_003928.1:  29%|█▊    | 457/1555 [00:54<02:07,  8.60it/s]NP_003928.1: DMS=1, merged=1
Processing DMS assay NP_003968.3:  29%|█▊    | 458/1555 [00:54<02:06,  8.64it/s]NP_003968.3: DMS=1, merged=1
Processing DMS assay NP_003973.3:  30%|█▊    | 459/1555 [00:54<02:05,  8.76it/s]NP_003973.3: DMS=1, merged=1
Processing DMS assay NP_003986.2:  30%|█▊    | 460/1555 [00:54<02:03,  8.87it/s]NP_003986.2: DMS=1, merged=1
Processing DMS assay NP_003995.2:  30%|█▊    | 461/1555 [00:54<02:03,  8.88it/s]NP_003995.2: DMS=4, merged=4
Processing DMS assay NP_003997.2:  30%|█▊    | 462/1555 [00:54<02:03,  8.87it/s]NP_003997.2: DMS=4, merged=4
Processing DMS assay NP_004077.1:  30%|█▊    | 463/1555 [00:55<02:06,  8.60it/s]NP_004077.1: DMS=1, merged=1
Processing DMS assay NP_004110.2:  30%|█▊    | 464/1555 [00:55<02:05,  8.69it/s]NP_004110.2: DMS=4, merged=4
Processing DMS assay NP_004125.3:  30%|█▊    | 465/1555 [00:55<02:10,  8.34it/s]NP_004125.3: DMS=1, merged=1
Processing DMS assay NP_004161.4:  30%|█▊    | 466/1555 [00:55<02:07,  8.51it/s]NP_004161.4: DMS=1, merged=1
Processing DMS assay NP_004165.2:  30%|█▊    | 467/1555 [00:55<02:07,  8.54it/s]NP_004165.2: DMS=1, merged=1
Processing DMS assay NP_004167.3:  30%|█▊    | 468/1555 [00:55<02:05,  8.63it/s]NP_004167.3: DMS=1, merged=1
Processing DMS assay NP_004174.1:  30%|█▊    | 469/1555 [00:55<02:05,  8.66it/s]NP_004174.1: DMS=2, merged=2
Processing DMS assay NP_004195.2:  30%|█▊    | 470/1555 [00:55<02:05,  8.65it/s]NP_004195.2: DMS=1, merged=1
Processing DMS assay NP_004199.1:  30%|█▊    | 471/1555 [00:55<02:04,  8.70it/s]NP_004199.1: DMS=1, merged=1
Processing DMS assay NP_004205.2:  30%|█▊    | 472/1555 [00:56<02:03,  8.77it/s]NP_004205.2: DMS=1, merged=1
Processing DMS assay NP_004251.4:  30%|█▊    | 473/1555 [00:56<02:02,  8.84it/s]NP_004251.4: DMS=2, merged=2
Processing DMS assay NP_004278.2:  30%|█▊    | 474/1555 [00:56<02:02,  8.83it/s]NP_004278.2: DMS=1, merged=1
Processing DMS assay NP_004300.1:  31%|█▊    | 475/1555 [00:56<02:01,  8.88it/s]NP_004300.1: DMS=1, merged=1
Processing DMS assay NP_004320.2:  31%|█▊    | 476/1555 [00:56<02:06,  8.54it/s]NP_004320.2: DMS=1, merged=1
Processing DMS assay NP_004324.2:  31%|█▊    | 477/1555 [00:56<02:04,  8.65it/s]Note: HMM scored 6/7 mutants for NP_004324.2; rest left as NaN.
NP_004324.2: DMS=7, merged=7
Processing DMS assay NP_004351.1:  31%|█▊    | 478/1555 [00:56<02:05,  8.56it/s]Note: HMM scored 1/3 mutants for NP_004351.1; rest left as NaN.
NP_004351.1: DMS=3, merged=3
Processing DMS assay NP_004355.2:  31%|█▊    | 479/1555 [00:56<02:06,  8.49it/s]NP_004355.2: DMS=2, merged=2
Processing DMS assay NP_004357.3:  31%|█▊    | 480/1555 [00:57<02:06,  8.49it/s]Note: HMM scored 1/2 mutants for NP_004357.3; rest left as NaN.
NP_004357.3: DMS=2, merged=2
Processing DMS assay NP_004360.2:  31%|█▊    | 481/1555 [00:57<02:05,  8.57it/s]Note: HMM scored 2/3 mutants for NP_004360.2; rest left as NaN.
NP_004360.2: DMS=3, merged=3
Processing DMS assay NP_004371.2:  31%|█▊    | 482/1555 [00:57<02:06,  8.50it/s]Note: HMM scored 5/10 mutants for NP_004371.2; rest left as NaN.
NP_004371.2: DMS=10, merged=10
Processing DMS assay NP_004399.2:  31%|█▊    | 483/1555 [00:57<02:09,  8.27it/s]NP_004399.2: DMS=3, merged=3
Processing DMS assay NP_004406.2:  31%|█▊    | 484/1555 [00:57<02:10,  8.22it/s]Note: HMM scored 1/2 mutants for NP_004406.2; rest left as NaN.
NP_004406.2: DMS=2, merged=2
Processing DMS assay NP_004420.1:  31%|█▊    | 485/1555 [00:57<02:11,  8.17it/s]NP_004420.1: DMS=1, merged=1
Processing DMS assay NP_004439.2:  31%|█▉    | 486/1555 [00:57<02:15,  7.89it/s]NP_004439.2: DMS=5, merged=5
Processing DMS assay NP_004444.2:  31%|█▉    | 487/1555 [00:57<02:14,  7.92it/s]NP_004444.2: DMS=2, merged=2
Processing DMS assay NP_004447.2:  31%|█▉    | 488/1555 [00:58<02:12,  8.05it/s]NP_004447.2: DMS=2, merged=2
Processing DMS assay NP_004454.2:  31%|█▉    | 489/1555 [00:58<02:11,  8.12it/s]NP_004454.2: DMS=1, merged=1
Processing DMS assay NP_004513.1:  32%|█▉    | 490/1555 [00:58<02:08,  8.32it/s]NP_004513.1: DMS=1, merged=1
Processing DMS assay NP_004514.2:  32%|█▉    | 491/1555 [00:58<02:07,  8.36it/s]NP_004514.2: DMS=1, merged=1
Processing DMS assay NP_004521.1:  32%|█▉    | 492/1555 [00:58<02:05,  8.49it/s]NP_004521.1: DMS=2, merged=2
Processing DMS assay NP_004535.1:  32%|█▉    | 493/1555 [00:58<02:04,  8.56it/s]NP_004535.1: DMS=1, merged=1
Processing DMS assay NP_004553.2:  32%|█▉    | 494/1555 [00:58<02:04,  8.55it/s]NP_004553.2: DMS=1, merged=1
Processing DMS assay NP_004577.1:  32%|█▉    | 495/1555 [00:58<02:03,  8.56it/s]NP_004577.1: DMS=6, merged=6
Processing DMS assay NP_004585.1:  32%|█▉    | 496/1555 [00:58<02:05,  8.44it/s]NP_004585.1: DMS=3, merged=3
Processing DMS assay NP_004594.1:  32%|█▉    | 497/1555 [00:59<02:13,  7.94it/s]NP_004594.1: DMS=2, merged=2
Processing DMS assay NP_004599.2:  32%|█▉    | 498/1555 [00:59<02:10,  8.07it/s]NP_004599.2: DMS=1, merged=1
Processing DMS assay NP_004603.1:  32%|█▉    | 499/1555 [00:59<02:09,  8.18it/s]Note: HMM scored 4/8 mutants for NP_004603.1; rest left as NaN.
NP_004603.1: DMS=8, merged=8
Processing DMS assay NP_004605.4:  32%|█▉    | 500/1555 [00:59<02:09,  8.16it/s]NP_004605.4: DMS=1, merged=1
Processing DMS assay NP_004620.1:  32%|█▉    | 501/1555 [00:59<02:06,  8.32it/s]NP_004620.1: DMS=1, merged=1
Processing DMS assay NP_004634.1:  32%|█▉    | 502/1555 [00:59<02:04,  8.48it/s]NP_004634.1: DMS=3, merged=3
Processing DMS assay NP_004637.1:  32%|█▉    | 503/1555 [00:59<02:04,  8.43it/s]NP_004637.1: DMS=2, merged=2
Processing DMS assay NP_004691.2:  32%|█▉    | 504/1555 [00:59<02:05,  8.39it/s]NP_004691.2: DMS=2, merged=2
Processing DMS assay NP_004718.1:  32%|█▉    | 505/1555 [01:00<02:05,  8.38it/s]NP_004718.1: DMS=1, merged=1
Processing DMS assay NP_004735.2:  33%|█▉    | 506/1555 [01:00<02:12,  7.90it/s]NP_004735.2: DMS=1, merged=1
Processing DMS assay NP_004804.2:  33%|█▉    | 507/1555 [01:00<02:15,  7.74it/s]NP_004804.2: DMS=2, merged=2
Processing DMS assay NP_004809.2:  33%|█▉    | 508/1555 [01:00<02:15,  7.75it/s]NP_004809.2: DMS=1, merged=1
Processing DMS assay NP_004813.2:  33%|█▉    | 509/1555 [01:00<02:14,  7.80it/s]NP_004813.2: DMS=1, merged=1
Processing DMS assay NP_004850.1:  33%|█▉    | 510/1555 [01:00<02:12,  7.89it/s]NP_004850.1: DMS=2, merged=2
Processing DMS assay NP_004874.1:  33%|█▉    | 511/1555 [01:00<02:10,  8.00it/s]NP_004874.1: DMS=2, merged=2
Processing DMS assay NP_004915.2:  33%|█▉    | 512/1555 [01:00<02:08,  8.13it/s]NP_004915.2: DMS=1, merged=1
Processing DMS assay NP_004928.2:  33%|█▉    | 513/1555 [01:01<02:05,  8.32it/s]NP_004928.2: DMS=2, merged=2
Processing DMS assay NP_004950.2:  33%|█▉    | 514/1555 [01:01<02:05,  8.33it/s]NP_004950.2: DMS=1, merged=1
Processing DMS assay NP_004961.1:  33%|█▉    | 515/1555 [01:01<02:03,  8.39it/s]NP_004961.1: DMS=1, merged=1
Processing DMS assay NP_004965.1:  33%|█▉    | 516/1555 [01:01<02:02,  8.46it/s]NP_004965.1: DMS=1, merged=1
Processing DMS assay NP_004975.2:  33%|█▉    | 517/1555 [01:01<02:01,  8.54it/s]NP_004975.2: DMS=1, merged=1
Processing DMS assay NP_004976.2:  33%|█▉    | 518/1555 [01:01<02:05,  8.28it/s]Note: HMM scored 3/4 mutants for NP_004976.2; rest left as NaN.
NP_004976.2: DMS=4, merged=4
Processing DMS assay NP_004981.2:  33%|██    | 519/1555 [01:01<02:03,  8.38it/s]NP_004981.2: DMS=1, merged=1
Processing DMS assay NP_004997.4:  33%|██    | 520/1555 [01:01<02:00,  8.57it/s]NP_004997.4: DMS=2, merged=2
Processing DMS assay NP_005043.1:  34%|██    | 521/1555 [01:01<02:00,  8.55it/s]NP_005043.1: DMS=1, merged=1
Processing DMS assay NP_005046.2:  34%|██    | 522/1555 [01:02<01:59,  8.63it/s]NP_005046.2: DMS=1, merged=1
Processing DMS assay NP_005145.3:  34%|██    | 523/1555 [01:02<02:00,  8.55it/s]NP_005145.3: DMS=1, merged=1
Processing DMS assay NP_005148.2:  34%|██    | 524/1555 [01:02<01:59,  8.62it/s]NP_005148.2: DMS=1, merged=1
Processing DMS assay NP_005150.1:  34%|██    | 525/1555 [01:02<02:00,  8.51it/s]NP_005150.1: DMS=1, merged=1
Processing DMS assay NP_005177.2:  34%|██    | 526/1555 [01:02<01:59,  8.65it/s]NP_005177.2: DMS=1, merged=1
Processing DMS assay NP_005179.2:  34%|██    | 527/1555 [01:02<01:57,  8.75it/s]Note: HMM scored 2/5 mutants for NP_005179.2; rest left as NaN.
NP_005179.2: DMS=5, merged=5
Processing DMS assay NP_005190.4:  34%|██    | 528/1555 [01:02<01:57,  8.71it/s]NP_005190.4: DMS=2, merged=2
Processing DMS assay NP_005199.2:  34%|██    | 529/1555 [01:02<02:02,  8.37it/s]NP_005199.2: DMS=2, merged=2
Processing DMS assay NP_005219.2:  34%|██    | 530/1555 [01:03<02:00,  8.52it/s]NP_005219.2: DMS=9, merged=9
Processing DMS assay NP_005240.3:  34%|██    | 531/1555 [01:03<02:01,  8.40it/s]Note: HMM scored 1/18 mutants for NP_005240.3; rest left as NaN.
NP_005240.3: DMS=18, merged=18
Processing DMS assay NP_005324.3:  34%|██    | 532/1555 [01:03<02:03,  8.29it/s]NP_005324.3: DMS=1, merged=1
Processing DMS assay NP_005334.1:  34%|██    | 533/1555 [01:03<02:00,  8.46it/s]NP_005334.1: DMS=1, merged=1
Processing DMS assay NP_005339.3:  34%|██    | 534/1555 [01:03<01:59,  8.56it/s]NP_005339.3: DMS=1, merged=1
Processing DMS assay NP_005350.1:  34%|██    | 535/1555 [01:03<01:58,  8.62it/s]NP_005350.1: DMS=1, merged=1
Processing DMS assay NP_005369.2:  34%|██    | 536/1555 [01:03<01:58,  8.57it/s]NP_005369.2: DMS=1, merged=1
Processing DMS assay NP_005436.1:  35%|██    | 537/1555 [01:03<01:57,  8.65it/s]Note: HMM scored 7/8 mutants for NP_005436.1; rest left as NaN.
NP_005436.1: DMS=8, merged=8
Processing DMS assay NP_005467.1:  35%|██    | 538/1555 [01:03<01:59,  8.52it/s]NP_005467.1: DMS=2, merged=2
Processing DMS assay NP_005493.2:  35%|██    | 539/1555 [01:04<02:03,  8.19it/s]NP_005493.2: DMS=1, merged=1
Processing DMS assay NP_005525.2:  35%|██    | 540/1555 [01:04<02:01,  8.36it/s]NP_005525.2: DMS=1, merged=1
Processing DMS assay NP_005526.1:  35%|██    | 541/1555 [01:04<01:58,  8.57it/s]NP_005526.1: DMS=1, merged=1
Processing DMS assay NP_005535.1:  35%|██    | 542/1555 [01:04<01:57,  8.62it/s]Note: HMM scored 1/2 mutants for NP_005535.1; rest left as NaN.
NP_005535.1: DMS=2, merged=2
Processing DMS assay NP_005545.1:  35%|██    | 543/1555 [01:04<01:57,  8.64it/s]NP_005545.1: DMS=2, merged=2
Processing DMS assay NP_005546.2:  35%|██    | 544/1555 [01:04<01:56,  8.64it/s]NP_005546.2: DMS=1, merged=1
Processing DMS assay NP_005548.2:  35%|██    | 545/1555 [01:04<01:56,  8.70it/s]NP_005548.2: DMS=1, merged=1
Processing DMS assay NP_005576.3:  35%|██    | 546/1555 [01:04<01:55,  8.77it/s]NP_005576.3: DMS=1, merged=1
Processing DMS assay NP_005600.1:  35%|██    | 547/1555 [01:05<01:55,  8.70it/s]NP_005600.1: DMS=4, merged=4
Processing DMS assay NP_005620.1:  35%|██    | 548/1555 [01:05<01:57,  8.59it/s]Note: HMM scored 4/5 mutants for NP_005620.1; rest left as NaN.
NP_005620.1: DMS=5, merged=5
Processing DMS assay NP_005624.2:  35%|██    | 549/1555 [01:05<01:58,  8.50it/s]NP_005624.2: DMS=1, merged=1
Processing DMS assay NP_005630.1:  35%|██    | 550/1555 [01:05<02:03,  8.17it/s]NP_005630.1: DMS=2, merged=2
Processing DMS assay NP_005645.1:  35%|██▏   | 551/1555 [01:05<02:00,  8.33it/s]NP_005645.1: DMS=2, merged=2
Processing DMS assay NP_005651.1:  35%|██▏   | 552/1555 [01:05<02:04,  8.09it/s]NP_005651.1: DMS=4, merged=4
Processing DMS assay NP_005786.1:  36%|██▏   | 553/1555 [01:05<02:13,  7.51it/s]NP_005786.1: DMS=1, merged=1
Processing DMS assay NP_005850.1:  36%|██▏   | 554/1555 [01:05<02:19,  7.17it/s]Note: HMM scored 5/9 mutants for NP_005850.1; rest left as NaN.
NP_005850.1: DMS=9, merged=9

Processing DMS assay NP_005852.2:  36%|██▏   | 555/1555 [01:06<02:22,  7.02it/s]NP_005852.2: DMS=2, merged=2
Processing DMS assay NP_005893.1:  36%|██▏   | 556/1555 [01:06<02:27,  6.77it/s]NP_005893.1: DMS=1, merged=1
Processing DMS assay NP_005948.3:  36%|██▏   | 557/1555 [01:06<02:27,  6.78it/s]NP_005948.3: DMS=1, merged=1
Processing DMS assay NP_005951.1:  36%|██▏   | 558/1555 [01:06<02:28,  6.71it/s]NP_005951.1: DMS=1, merged=1
Processing DMS assay NP_005952.2:  36%|██▏   | 559/1555 [01:06<02:27,  6.74it/s]Note: HMM scored 1/2 mutants for NP_005952.2; rest left as NaN.
NP_005952.2: DMS=2, merged=2
Processing DMS assay NP_005973.1:  36%|██▏   | 560/1555 [01:06<02:32,  6.53it/s]NP_005973.1: DMS=1, merged=1
Processing DMS assay NP_005975.1:  36%|██▏   | 561/1555 [01:07<02:29,  6.66it/s]NP_005975.1: DMS=1, merged=1
Processing DMS assay NP_005996.2:  36%|██▏   | 562/1555 [01:07<02:17,  7.20it/s]Note: HMM scored 8/9 mutants for NP_005996.2; rest left as NaN.
NP_005996.2: DMS=9, merged=9
Processing DMS assay NP_006000.2:  36%|██▏   | 563/1555 [01:07<02:13,  7.44it/s]NP_006000.2: DMS=1, merged=1
Processing DMS assay NP_006006.3:  36%|██▏   | 564/1555 [01:07<02:07,  7.78it/s]Note: HMM scored 1/11 mutants for NP_006006.3; rest left as NaN.
NP_006006.3: DMS=11, merged=11
Processing DMS assay NP_006010.2:  36%|██▏   | 565/1555 [01:07<02:07,  7.75it/s]NP_006010.2: DMS=3, merged=3
Processing DMS assay NP_006022.3:  36%|██▏   | 566/1555 [01:07<02:04,  7.95it/s]NP_006022.3: DMS=1, merged=1
Processing DMS assay NP_006054.2:  36%|██▏   | 567/1555 [01:07<02:00,  8.18it/s]NP_006054.2: DMS=2, merged=2
Processing DMS assay NP_006197.1:  37%|██▏   | 568/1555 [01:07<01:59,  8.25it/s]NP_006197.1: DMS=3, merged=3
Processing DMS assay NP_006205.1:  37%|██▏   | 569/1555 [01:07<01:57,  8.38it/s]NP_006205.1: DMS=1, merged=1
Processing DMS assay NP_006209.2:  37%|██▏   | 570/1555 [01:08<01:55,  8.50it/s]NP_006209.2: DMS=3, merged=3
Processing DMS assay NP_006227.1:  37%|██▏   | 571/1555 [01:08<02:01,  8.10it/s]NP_006227.1: DMS=1, merged=1
Processing DMS assay NP_006236.1:  37%|██▏   | 572/1555 [01:08<01:59,  8.24it/s]NP_006236.1: DMS=1, merged=1
Processing DMS assay NP_006256.1:  37%|██▏   | 573/1555 [01:08<01:56,  8.40it/s]NP_006256.1: DMS=1, merged=1
Processing DMS assay NP_006261.1:  37%|██▏   | 574/1555 [01:08<01:55,  8.46it/s]NP_006261.1: DMS=1, merged=1
Processing DMS assay NP_006297.2:  37%|██▏   | 575/1555 [01:08<01:54,  8.57it/s]NP_006297.2: DMS=5, merged=5
Processing DMS assay NP_006336.3:  37%|██▏   | 576/1555 [01:08<01:55,  8.46it/s]NP_006336.3: DMS=1, merged=1
Processing DMS assay NP_006339.4:  37%|██▏   | 577/1555 [01:08<01:55,  8.48it/s]NP_006339.4: DMS=2, merged=2
Processing DMS assay NP_006403.2:  37%|██▏   | 578/1555 [01:09<01:55,  8.46it/s]Note: HMM scored 1/2 mutants for NP_006403.2; rest left as NaN.
NP_006403.2: DMS=2, merged=2
Processing DMS assay NP_006406.1:  37%|██▏   | 579/1555 [01:09<01:56,  8.40it/s]NP_006406.1: DMS=1, merged=1
Processing DMS assay NP_006436.3:  37%|██▏   | 580/1555 [01:09<01:54,  8.51it/s]NP_006436.3: DMS=1, merged=1
Processing DMS assay NP_006493.1:  37%|██▏   | 581/1555 [01:09<01:53,  8.61it/s]NP_006493.1: DMS=1, merged=1
Processing DMS assay NP_006505.4:  37%|██▏   | 582/1555 [01:09<01:59,  8.17it/s]Note: HMM scored 1/2 mutants for NP_006505.4; rest left as NaN.
NP_006505.4: DMS=2, merged=2
Processing DMS assay NP_006507.2:  37%|██▏   | 583/1555 [01:09<01:57,  8.27it/s]NP_006507.2: DMS=8, merged=8
Processing DMS assay NP_006508.2:  38%|██▎   | 584/1555 [01:09<01:57,  8.25it/s]NP_006508.2: DMS=1, merged=1
Processing DMS assay NP_006556.1:  38%|██▎   | 585/1555 [01:09<01:56,  8.34it/s]NP_006556.1: DMS=1, merged=1
Processing DMS assay NP_006570.1:  38%|██▎   | 586/1555 [01:09<01:53,  8.51it/s]NP_006570.1: DMS=3, merged=3
Processing DMS assay NP_006584.1:  38%|██▎   | 587/1555 [01:10<01:53,  8.52it/s]Note: HMM scored 1/2 mutants for NP_006584.1; rest left as NaN.
NP_006584.1: DMS=2, merged=2
Processing DMS assay NP_006746.1:  38%|██▎   | 588/1555 [01:10<01:52,  8.60it/s]NP_006746.1: DMS=1, merged=1
Processing DMS assay NP_006763.2:  38%|██▎   | 589/1555 [01:10<01:50,  8.73it/s]Note: HMM scored 2/6 mutants for NP_006763.2; rest left as NaN.
NP_006763.2: DMS=6, merged=6
Processing DMS assay NP_006867.1:  38%|██▎   | 590/1555 [01:10<01:50,  8.71it/s]NP_006867.1: DMS=1, merged=1
Processing DMS assay NP_008816.3:  38%|██▎   | 591/1555 [01:10<01:49,  8.79it/s]NP_008816.3: DMS=5, merged=5
Processing DMS assay NP_008818.3:  38%|██▎   | 592/1555 [01:10<01:51,  8.64it/s]NP_008818.3: DMS=1, merged=1
Processing DMS assay NP_008846.2:  38%|██▎   | 593/1555 [01:10<01:54,  8.37it/s]NP_008846.2: DMS=3, merged=3
Processing DMS assay NP_008853.3:  38%|██▎   | 594/1555 [01:10<01:54,  8.39it/s]Note: HMM scored 1/2 mutants for NP_008853.3; rest left as NaN.
NP_008853.3: DMS=2, merged=2
Processing DMS assay NP_008872.1:  38%|██▎   | 595/1555 [01:11<01:54,  8.40it/s]NP_008872.1: DMS=1, merged=1
Processing DMS assay NP_008877.2:  38%|██▎   | 596/1555 [01:11<01:52,  8.54it/s]NP_008877.2: DMS=2, merged=2
Processing DMS assay NP_008880.2:  38%|██▎   | 597/1555 [01:11<01:51,  8.61it/s]NP_008880.2: DMS=1, merged=1
Processing DMS assay NP_009060.2:  38%|██▎   | 598/1555 [01:11<01:49,  8.71it/s]Note: HMM scored 2/4 mutants for NP_009060.2; rest left as NaN.
NP_009060.2: DMS=4, merged=4
Processing DMS assay NP_009167.1:  39%|██▎   | 599/1555 [01:11<01:49,  8.72it/s]NP_009167.1: DMS=1, merged=1
Processing DMS assay NP_009185.2:  39%|██▎   | 600/1555 [01:11<01:48,  8.81it/s]NP_009185.2: DMS=1, merged=1
Processing DMS assay NP_009193.2:  39%|██▎   | 601/1555 [01:11<01:48,  8.81it/s]NP_009193.2: DMS=1, merged=1
Processing DMS assay NP_009225.1:  39%|██▎   | 602/1555 [01:11<01:47,  8.83it/s]Note: HMM scored 7/10 mutants for NP_009225.1; rest left as NaN.
NP_009225.1: DMS=10, merged=10
Processing DMS assay NP_015564.5:  39%|██▎   | 603/1555 [01:11<01:55,  8.26it/s]NP_015564.5: DMS=2, merged=2
Processing DMS assay NP_015566.1:  39%|██▎   | 604/1555 [01:12<01:54,  8.34it/s]Note: HMM scored 2/4 mutants for NP_015566.1; rest left as NaN.
NP_015566.1: DMS=4, merged=4
Processing DMS assay NP_036192.2:  39%|██▎   | 605/1555 [01:12<01:52,  8.42it/s]NP_036192.2: DMS=1, merged=1
Processing DMS assay NP_036286.2:  39%|██▎   | 606/1555 [01:12<01:51,  8.52it/s]NP_036286.2: DMS=1, merged=1
Processing DMS assay NP_036325.2:  39%|██▎   | 607/1555 [01:12<01:49,  8.67it/s]NP_036325.2: DMS=2, merged=2
Processing DMS assay NP_036345.2:  39%|██▎   | 608/1555 [01:12<01:49,  8.67it/s]NP_036345.2: DMS=1, merged=1
Processing DMS assay NP_036382.2:  39%|██▎   | 609/1555 [01:12<01:47,  8.80it/s]NP_036382.2: DMS=2, merged=2
Processing DMS assay NP_036470.1:  39%|██▎   | 610/1555 [01:12<01:47,  8.77it/s]NP_036470.1: DMS=1, merged=1
Processing DMS assay NP_036546.2:  39%|██▎   | 611/1555 [01:12<01:58,  7.96it/s]NP_036546.2: DMS=2, merged=2
Processing DMS assay NP_036601.2:  39%|██▎   | 612/1555 [01:13<02:08,  7.32it/s]NP_036601.2: DMS=1, merged=1
Processing DMS assay NP_037379.1:  39%|██▎   | 613/1555 [01:13<02:15,  6.93it/s]NP_037379.1: DMS=1, merged=1
Processing DMS assay NP_037386.1:  39%|██▎   | 614/1555 [01:13<02:26,  6.43it/s]Note: HMM scored 1/2 mutants for NP_037386.1; rest left as NaN.
NP_037386.1: DMS=2, merged=2
Processing DMS assay NP_037397.2:  40%|██▎   | 615/1555 [01:13<02:28,  6.32it/s]NP_037397.2: DMS=1, merged=1
Processing DMS assay NP_037398.2:  40%|██▍   | 616/1555 [01:13<02:27,  6.36it/s]NP_037398.2: DMS=1, merged=1
Processing DMS assay NP_037407.4:  40%|██▍   | 617/1555 [01:13<02:29,  6.29it/s]Note: HMM scored 1/2 mutants for NP_037407.4; rest left as NaN.
NP_037407.4: DMS=2, merged=2
Processing DMS assay NP_037471.2:  40%|██▍   | 618/1555 [01:14<02:18,  6.78it/s]NP_037471.2: DMS=1, merged=1
Processing DMS assay NP_054728.2:  40%|██▍   | 619/1555 [01:14<02:08,  7.27it/s]NP_054728.2: DMS=2, merged=2
Processing DMS assay NP_054859.2:  40%|██▍   | 620/1555 [01:14<02:03,  7.60it/s]NP_054859.2: DMS=1, merged=1
Processing DMS assay NP_054860.1:  40%|██▍   | 621/1555 [01:14<01:58,  7.90it/s]NP_054860.1: DMS=1, merged=1
Processing DMS assay NP_055023.2:  40%|██▍   | 622/1555 [01:14<01:54,  8.14it/s]Note: HMM scored 4/11 mutants for NP_055023.2; rest left as NaN.

NP_055023.2: DMS=11, merged=11
Processing DMS assay NP_055047.2:  40%|██▍   | 623/1555 [01:14<01:55,  8.09it/s]NP_055047.2: DMS=1, merged=1
Processing DMS assay NP_055064.1:  40%|██▍   | 624/1555 [01:14<01:52,  8.30it/s]NP_055064.1: DMS=2, merged=2
Processing DMS assay NP_055067.1:  40%|██▍   | 625/1555 [01:14<01:55,  8.05it/s]NP_055067.1: DMS=1, merged=1
Processing DMS assay NP_055085.1:  40%|██▍   | 626/1555 [01:14<01:52,  8.25it/s]NP_055085.1: DMS=1, merged=1
Processing DMS assay NP_055086.1:  40%|██▍   | 627/1555 [01:15<01:50,  8.40it/s]NP_055086.1: DMS=1, merged=1
Processing DMS assay NP_055105.2:  40%|██▍   | 628/1555 [01:15<01:48,  8.54it/s]NP_055105.2: DMS=1, merged=1
Processing DMS assay NP_055149.3:  40%|██▍   | 629/1555 [01:15<01:47,  8.61it/s]NP_055149.3: DMS=1, merged=1
Processing DMS assay NP_055177.2:  41%|██▍   | 630/1555 [01:15<01:46,  8.66it/s]NP_055177.2: DMS=1, merged=1
Processing DMS assay NP_055178.3:  41%|██▍   | 631/1555 [01:15<01:46,  8.67it/s]NP_055178.3: DMS=1, merged=1
Processing DMS assay NP_055331.1:  41%|██▍   | 632/1555 [01:15<01:48,  8.53it/s]NP_055331.1: DMS=2, merged=2
Processing DMS assay NP_055400.1:  41%|██▍   | 633/1555 [01:15<01:47,  8.54it/s]Note: HMM scored 1/2 mutants for NP_055400.1; rest left as NaN.
NP_055400.1: DMS=2, merged=2
Processing DMS assay NP_055440.1:  41%|██▍   | 634/1555 [01:15<01:50,  8.32it/s]NP_055440.1: DMS=2, merged=2
Processing DMS assay NP_055542.1:  41%|██▍   | 635/1555 [01:16<01:52,  8.18it/s]Note: HMM scored 1/4 mutants for NP_055542.1; rest left as NaN.
NP_055542.1: DMS=4, merged=4
Processing DMS assay NP_055595.2:  41%|██▍   | 636/1555 [01:16<01:58,  7.73it/s]Note: HMM scored 1/2 mutants for NP_055595.2; rest left as NaN.
NP_055595.2: DMS=2, merged=2
Processing DMS assay NP_055637.2:  41%|██▍   | 637/1555 [01:16<01:56,  7.90it/s]NP_055637.2: DMS=1, merged=1
Processing DMS assay NP_055690.1:  41%|██▍   | 638/1555 [01:16<01:53,  8.09it/s]NP_055690.1: DMS=1, merged=1
Processing DMS assay NP_055761.2:  41%|██▍   | 639/1555 [01:16<01:50,  8.26it/s]NP_055761.2: DMS=7, merged=7
Processing DMS assay NP_055790.1:  41%|██▍   | 640/1555 [01:16<01:50,  8.25it/s]NP_055790.1: DMS=2, merged=2
Processing DMS assay NP_055861.3:  41%|██▍   | 641/1555 [01:16<01:50,  8.26it/s]Note: HMM scored 1/3 mutants for NP_055861.3; rest left as NaN.
NP_055861.3: DMS=3, merged=3
Processing DMS assay NP_055907.3:  41%|██▍   | 642/1555 [01:16<01:49,  8.30it/s]NP_055907.3: DMS=1, merged=1
Processing DMS assay NP_056110.2:  41%|██▍   | 643/1555 [01:17<01:50,  8.23it/s]NP_056110.2: DMS=1, merged=1
Processing DMS assay NP_056145.5:  41%|██▍   | 644/1555 [01:17<01:51,  8.17it/s]NP_056145.5: DMS=2, merged=2
Processing DMS assay NP_056161.2:  41%|██▍   | 645/1555 [01:17<01:51,  8.13it/s]NP_056161.2: DMS=1, merged=1
Processing DMS assay NP_056183.2:  42%|██▍   | 646/1555 [01:17<01:56,  7.83it/s]NP_056183.2: DMS=1, merged=1
Processing DMS assay NP_056280.2:  42%|██▍   | 647/1555 [01:17<01:53,  7.97it/s]NP_056280.2: DMS=1, merged=1
Processing DMS assay NP_056321.2:  42%|██▌   | 648/1555 [01:17<01:51,  8.15it/s]NP_056321.2: DMS=2, merged=2
Processing DMS assay NP_056414.1:  42%|██▌   | 649/1555 [01:17<01:53,  7.99it/s]NP_056414.1: DMS=1, merged=1
Processing DMS assay NP_056444.3:  42%|██▌   | 650/1555 [01:17<01:50,  8.18it/s]NP_056444.3: DMS=2, merged=2
Processing DMS assay NP_056477.1:  42%|██▌   | 651/1555 [01:18<01:50,  8.21it/s]NP_056477.1: DMS=1, merged=1
Processing DMS assay NP_056496.1:  42%|██▌   | 652/1555 [01:18<01:55,  7.80it/s]NP_056496.1: DMS=1, merged=1
Processing DMS assay NP_056528.2:  42%|██▌   | 653/1555 [01:18<01:55,  7.80it/s]NP_056528.2: DMS=2, merged=2
Processing DMS assay NP_056993.2:  42%|██▌   | 654/1555 [01:18<01:55,  7.80it/s]NP_056993.2: DMS=2, merged=2
Processing DMS assay NP_056999.2:  42%|██▌   | 655/1555 [01:18<01:52,  7.99it/s]NP_056999.2: DMS=2, merged=2
Processing DMS assay NP_057006.1:  42%|██▌   | 656/1555 [01:18<01:51,  8.06it/s]NP_057006.1: DMS=1, merged=1
Processing DMS assay NP_057088.2:  42%|██▌   | 657/1555 [01:18<01:52,  7.98it/s]NP_057088.2: DMS=1, merged=1
Processing DMS assay NP_057119.3:  42%|██▌   | 658/1555 [01:18<01:49,  8.18it/s]NP_057119.3: DMS=1, merged=1
Processing DMS assay NP_057122.2:  42%|██▌   | 659/1555 [01:19<01:48,  8.24it/s]NP_057122.2: DMS=1, merged=1
Processing DMS assay NP_057206.2:  42%|██▌   | 660/1555 [01:19<01:47,  8.36it/s]NP_057206.2: DMS=1, merged=1
Processing DMS assay NP_057264.4:  43%|██▌   | 661/1555 [01:19<01:46,  8.38it/s]NP_057264.4: DMS=1, merged=1
Processing DMS assay NP_057287.2:  43%|██▌   | 662/1555 [01:19<01:45,  8.49it/s]NP_057287.2: DMS=1, merged=1
Processing DMS assay NP_057323.3:  43%|██▌   | 663/1555 [01:19<01:43,  8.61it/s]NP_057323.3: DMS=1, merged=1
Processing DMS assay NP_057353.1:  43%|██▌   | 664/1555 [01:19<01:42,  8.68it/s]NP_057353.1: DMS=2, merged=2
Processing DMS assay NP_057425.3:  43%|██▌   | 665/1555 [01:19<01:42,  8.71it/s]NP_057425.3: DMS=1, merged=1
Processing DMS assay NP_057490.2:  43%|██▌   | 666/1555 [01:19<01:42,  8.70it/s]NP_057490.2: DMS=1, merged=1
Processing DMS assay NP_057501.2:  43%|██▌   | 667/1555 [01:19<01:42,  8.69it/s]NP_057501.2: DMS=1, merged=1
Processing DMS assay NP_057688.3:  43%|██▌   | 668/1555 [01:20<01:47,  8.24it/s]NP_057688.3: DMS=1, merged=1
Processing DMS assay NP_057737.2:  43%|██▌   | 669/1555 [01:20<01:47,  8.24it/s]NP_057737.2: DMS=1, merged=1
Processing DMS assay NP_059830.1:  43%|██▌   | 670/1555 [01:20<01:45,  8.36it/s]NP_059830.1: DMS=1, merged=1
Processing DMS assay NP_060083.1:  43%|██▌   | 671/1555 [01:20<01:44,  8.44it/s]NP_060083.1: DMS=1, merged=1
Processing DMS assay NP_060087.3:  43%|██▌   | 672/1555 [01:20<01:43,  8.51it/s]Note: HMM scored 2/3 mutants for NP_060087.3; rest left as NaN.
NP_060087.3: DMS=3, merged=3
Processing DMS assay NP_060119.3:  43%|██▌   | 673/1555 [01:20<01:44,  8.47it/s]NP_060119.3: DMS=2, merged=2
Processing DMS assay NP_060137.2:  43%|██▌   | 674/1555 [01:20<01:44,  8.44it/s]NP_060137.2: DMS=1, merged=1
Processing DMS assay NP_060141.3:  43%|██▌   | 675/1555 [01:20<01:43,  8.48it/s]NP_060141.3: DMS=1, merged=1
Processing DMS assay NP_060206.2:  43%|██▌   | 676/1555 [01:21<01:42,  8.60it/s]NP_060206.2: DMS=1, merged=1
Processing DMS assay NP_060227.2:  44%|██▌   | 677/1555 [01:21<01:41,  8.66it/s]NP_060227.2: DMS=1, merged=1
Processing DMS assay NP_060247.2:  44%|██▌   | 678/1555 [01:21<01:41,  8.66it/s]NP_060247.2: DMS=2, merged=2
Processing DMS assay NP_060295.1:  44%|██▌   | 679/1555 [01:21<01:45,  8.29it/s]NP_060295.1: DMS=1, merged=1
Processing DMS assay NP_060334.2:  44%|██▌   | 680/1555 [01:21<01:43,  8.41it/s]NP_060334.2: DMS=1, merged=1
Processing DMS assay NP_060352.1:  44%|██▋   | 681/1555 [01:21<01:44,  8.37it/s]NP_060352.1: DMS=3, merged=3
Processing DMS assay NP_060387.2:  44%|██▋   | 682/1555 [01:21<01:43,  8.41it/s]NP_060387.2: DMS=2, merged=2
Processing DMS assay NP_060416.1:  44%|██▋   | 683/1555 [01:21<01:44,  8.34it/s]Note: HMM scored 1/2 mutants for NP_060416.1; rest left as NaN.
NP_060416.1: DMS=2, merged=2
Processing DMS assay NP_060420.2:  44%|██▋   | 684/1555 [01:21<01:46,  8.20it/s]NP_060420.2: DMS=1, merged=1
Processing DMS assay NP_060476.2:  44%|██▋   | 685/1555 [01:22<01:47,  8.08it/s]NP_060476.2: DMS=1, merged=1
Processing DMS assay NP_060521.4:  44%|██▋   | 686/1555 [01:22<02:26,  5.93it/s]Note: HMM scored 1/2 mutants for NP_060521.4; rest left as NaN.
NP_060521.4: DMS=2, merged=2
Processing DMS assay NP_060533.2:  44%|██▋   | 687/1555 [01:22<02:14,  6.43it/s]NP_060533.2: DMS=1, merged=1
Processing DMS assay NP_060552.4:  44%|██▋   | 688/1555 [01:22<02:07,  6.78it/s]NP_060552.4: DMS=1, merged=1
Processing DMS assay NP_060575.1:  44%|██▋   | 689/1555 [01:22<02:07,  6.79it/s]NP_060575.1: DMS=1, merged=1
Processing DMS assay NP_060597.4:  44%|██▋   | 690/1555 [01:22<02:01,  7.11it/s]NP_060597.4: DMS=1, merged=1
Processing DMS assay NP_060767.2:  44%|██▋   | 691/1555 [01:23<01:57,  7.38it/s]NP_060767.2: DMS=1, merged=1
Processing DMS assay NP_060876.5:  45%|██▋   | 692/1555 [01:23<01:53,  7.62it/s]NP_060876.5: DMS=2, merged=2
Processing DMS assay NP_060914.2:  45%|██▋   | 693/1555 [01:23<01:51,  7.73it/s]NP_060914.2: DMS=1, merged=1

Processing DMS assay NP_060921.3:  45%|██▋   | 694/1555 [01:23<01:51,  7.72it/s]NP_060921.3: DMS=1, merged=1
Processing DMS assay NP_060956.1:  45%|██▋   | 695/1555 [01:23<01:52,  7.62it/s]NP_060956.1: DMS=1, merged=1
Processing DMS assay NP_061154.1:  45%|██▋   | 696/1555 [01:23<01:50,  7.74it/s]NP_061154.1: DMS=1, merged=1
Processing DMS assay NP_061183.2:  45%|██▋   | 697/1555 [01:23<01:48,  7.91it/s]NP_061183.2: DMS=1, merged=1
Processing DMS assay NP_061193.2:  45%|██▋   | 698/1555 [01:23<01:45,  8.10it/s]NP_061193.2: DMS=1, merged=1
Processing DMS assay NP_061496.2:  45%|██▋   | 699/1555 [01:24<01:43,  8.29it/s]NP_061496.2: DMS=1, merged=1
Processing DMS assay NP_061764.2:  45%|██▋   | 700/1555 [01:24<01:44,  8.15it/s]NP_061764.2: DMS=1, merged=1
Processing DMS assay NP_061820.1:  45%|██▋   | 701/1555 [01:24<01:42,  8.31it/s]NP_061820.1: DMS=1, merged=1
Processing DMS assay NP_061971.3:  45%|██▋   | 702/1555 [01:24<01:41,  8.39it/s]NP_061971.3: DMS=1, merged=1
Processing DMS assay NP_063945.2:  45%|██▋   | 703/1555 [01:24<01:39,  8.55it/s]Note: HMM scored 1/2 mutants for NP_063945.2; rest left as NaN.
NP_063945.2: DMS=2, merged=2
Processing DMS assay NP_065175.4:  45%|██▋   | 704/1555 [01:24<01:39,  8.53it/s]NP_065175.4: DMS=1, merged=1
Processing DMS assay NP_065184.2:  45%|██▋   | 705/1555 [01:24<01:39,  8.52it/s]NP_065184.2: DMS=2, merged=2
Processing DMS assay NP_065394.1:  45%|██▋   | 706/1555 [01:24<01:40,  8.45it/s]NP_065394.1: DMS=1, merged=1
Processing DMS assay NP_065712.1:  45%|██▋   | 707/1555 [01:24<01:39,  8.51it/s]NP_065712.1: DMS=1, merged=1
Processing DMS assay NP_065789.1:  46%|██▋   | 708/1555 [01:25<01:38,  8.56it/s]NP_065789.1: DMS=1, merged=1
Processing DMS assay NP_065796.2:  46%|██▋   | 709/1555 [01:25<01:38,  8.62it/s]NP_065796.2: DMS=1, merged=1
Processing DMS assay NP_065822.2:  46%|██▋   | 710/1555 [01:25<01:37,  8.63it/s]NP_065822.2: DMS=1, merged=1
Processing DMS assay NP_065851.1:  46%|██▋   | 711/1555 [01:25<01:42,  8.25it/s]NP_065851.1: DMS=1, merged=1
Processing DMS assay NP_066124.1:  46%|██▋   | 712/1555 [01:25<01:41,  8.32it/s]NP_066124.1: DMS=3, merged=3
Processing DMS assay NP_066192.1:  46%|██▊   | 713/1555 [01:25<01:40,  8.36it/s]NP_066192.1: DMS=1, merged=1
Processing DMS assay NP_066268.1:  46%|██▊   | 714/1555 [01:25<01:38,  8.53it/s]Note: HMM scored 2/3 mutants for NP_066268.1; rest left as NaN.
NP_066268.1: DMS=3, merged=3
Processing DMS assay NP_066285.1:  46%|██▊   | 715/1555 [01:25<01:39,  8.46it/s]NP_066285.1: DMS=1, merged=1
Processing DMS assay NP_066288.2:  46%|██▊   | 716/1555 [01:26<01:38,  8.52it/s]NP_066288.2: DMS=1, merged=1
Processing DMS assay NP_067075.1:  46%|██▊   | 717/1555 [01:26<01:37,  8.59it/s]NP_067075.1: DMS=1, merged=1
Processing DMS assay NP_067627.3:  46%|██▊   | 718/1555 [01:26<01:37,  8.61it/s]Note: HMM scored 1/2 mutants for NP_067627.3; rest left as NaN.
NP_067627.3: DMS=2, merged=2
Processing DMS assay NP_067638.3:  46%|██▊   | 719/1555 [01:26<01:36,  8.65it/s]NP_067638.3: DMS=1, merged=1
Processing DMS assay NP_067641.2:  46%|██▊   | 720/1555 [01:26<01:35,  8.76it/s]NP_067641.2: DMS=1, merged=1
Processing DMS assay NP_068741.1:  46%|██▊   | 721/1555 [01:26<01:39,  8.38it/s]Note: HMM scored 1/2 mutants for NP_068741.1; rest left as NaN.
NP_068741.1: DMS=2, merged=2
Processing DMS assay NP_068758.3:  46%|██▊   | 722/1555 [01:26<01:38,  8.48it/s]NP_068758.3: DMS=1, merged=1
Processing DMS assay NP_071372.1:  46%|██▊   | 723/1555 [01:26<01:37,  8.54it/s]NP_071372.1: DMS=1, merged=1
Processing DMS assay NP_071384.1:  47%|██▊   | 724/1555 [01:26<01:36,  8.59it/s]NP_071384.1: DMS=1, merged=1
Processing DMS assay NP_071407.4:  47%|██▊   | 725/1555 [01:27<01:35,  8.65it/s]NP_071407.4: DMS=2, merged=2
Processing DMS assay NP_071415.1:  47%|██▊   | 726/1555 [01:27<01:36,  8.55it/s]NP_071415.1: DMS=1, merged=1
Processing DMS assay NP_071900.2:  47%|██▊   | 727/1555 [01:27<01:35,  8.64it/s]NP_071900.2: DMS=4, merged=4
Processing DMS assay NP_071908.2:  47%|██▊   | 728/1555 [01:27<01:36,  8.56it/s]NP_071908.2: DMS=1, merged=1
Processing DMS assay NP_071934.3:  47%|██▊   | 729/1555 [01:27<01:35,  8.64it/s]Note: HMM scored 2/3 mutants for NP_071934.3; rest left as NaN.
NP_071934.3: DMS=3, merged=3
Processing DMS assay NP_072046.2:  47%|██▊   | 730/1555 [01:27<01:35,  8.63it/s]NP_072046.2: DMS=1, merged=1
Processing DMS assay NP_075044.2:  47%|██▊   | 731/1555 [01:27<01:35,  8.59it/s]NP_075044.2: DMS=1, merged=1
Processing DMS assay NP_075555.1:  47%|██▊   | 732/1555 [01:27<01:40,  8.20it/s]NP_075555.1: DMS=1, merged=1
Processing DMS assay NP_075598.2:  47%|██▊   | 733/1555 [01:28<01:39,  8.29it/s]Note: HMM scored 1/2 mutants for NP_075598.2; rest left as NaN.
NP_075598.2: DMS=2, merged=2
Processing DMS assay NP_076872.1:  47%|██▊   | 734/1555 [01:28<01:38,  8.31it/s]NP_076872.1: DMS=1, merged=1
Processing DMS assay NP_076932.1:  47%|██▊   | 735/1555 [01:28<01:39,  8.27it/s]NP_076932.1: DMS=1, merged=1
Processing DMS assay NP_077277.1:  47%|██▊   | 736/1555 [01:28<01:37,  8.36it/s]NP_077277.1: DMS=1, merged=1
Processing DMS assay NP_077288.2:  47%|██▊   | 737/1555 [01:28<01:37,  8.35it/s]NP_077288.2: DMS=1, merged=1
Processing DMS assay NP_077744.4:  47%|██▊   | 738/1555 [01:28<01:36,  8.46it/s]NP_077744.4: DMS=1, merged=1
Processing DMS assay NP_078853.2:  48%|██▊   | 739/1555 [01:28<01:35,  8.53it/s]NP_078853.2: DMS=1, merged=1
Processing DMS assay NP_078916.3:  48%|██▊   | 740/1555 [01:28<01:34,  8.63it/s]NP_078916.3: DMS=1, merged=1
Processing DMS assay NP_078941.2:  48%|██▊   | 741/1555 [01:28<01:33,  8.67it/s]NP_078941.2: DMS=4, merged=4
Processing DMS assay NP_078961.3:  48%|██▊   | 742/1555 [01:29<01:35,  8.54it/s]NP_078961.3: DMS=2, merged=2
Processing DMS assay NP_079033.4:  48%|██▊   | 743/1555 [01:29<01:39,  8.18it/s]Note: HMM scored 2/4 mutants for NP_079033.4; rest left as NaN.
NP_079033.4: DMS=4, merged=4
Processing DMS assay NP_079093.2:  48%|██▊   | 744/1555 [01:29<01:37,  8.28it/s]NP_079093.2: DMS=1, merged=1
Processing DMS assay NP_079130.2:  48%|██▊   | 745/1555 [01:29<01:36,  8.42it/s]NP_079130.2: DMS=1, merged=1
Processing DMS assay NP_079265.2:  48%|██▉   | 746/1555 [01:29<01:35,  8.51it/s]NP_079265.2: DMS=2, merged=2
Processing DMS assay NP_079375.3:  48%|██▉   | 747/1555 [01:29<01:35,  8.44it/s]NP_079375.3: DMS=1, merged=1
Processing DMS assay NP_079483.3:  48%|██▉   | 748/1555 [01:29<01:35,  8.44it/s]NP_079483.3: DMS=1, merged=1
Processing DMS assay NP_079495.1:  48%|██▉   | 749/1555 [01:29<01:34,  8.57it/s]NP_079495.1: DMS=1, merged=1
Processing DMS assay NP_079519.1:  48%|██▉   | 750/1555 [01:30<01:33,  8.65it/s]NP_079519.1: DMS=1, merged=1
Processing DMS assay NP_079541.1:  48%|██▉   | 751/1555 [01:30<01:32,  8.71it/s]NP_079541.1: DMS=1, merged=1
Processing DMS assay NP_085911.2:  48%|██▉   | 752/1555 [01:30<01:31,  8.77it/s]NP_085911.2: DMS=1, merged=1
Processing DMS assay NP_109587.1:  48%|██▉   | 753/1555 [01:30<01:31,  8.73it/s]NP_109587.1: DMS=1, merged=1
Processing DMS assay NP_110426.4:  48%|██▉   | 754/1555 [01:30<01:35,  8.40it/s]NP_110426.4: DMS=1, merged=1
Processing DMS assay NP_112506.2:  49%|██▉   | 755/1555 [01:30<01:34,  8.50it/s]NP_112506.2: DMS=1, merged=1
Processing DMS assay NP_112553.1:  49%|██▉   | 756/1555 [01:30<01:33,  8.56it/s]NP_112553.1: DMS=1, merged=1
Processing DMS assay NP_112586.1:  49%|██▉   | 757/1555 [01:30<01:33,  8.52it/s]NP_112586.1: DMS=1, merged=1
Processing DMS assay NP_113584.3:  49%|██▉   | 758/1555 [01:30<01:33,  8.52it/s]Note: HMM scored 1/5 mutants for NP_113584.3; rest left as NaN.
NP_113584.3: DMS=5, merged=5
Processing DMS assay NP_113663.2:  49%|██▉   | 759/1555 [01:31<01:36,  8.21it/s]Note: HMM scored 1/2 mutants for NP_113663.2; rest left as NaN.
NP_113663.2: DMS=2, merged=2
Processing DMS assay NP_114032.2:  49%|██▉   | 760/1555 [01:31<01:38,  8.09it/s]Note: HMM scored 2/6 mutants for NP_114032.2; rest left as NaN.
NP_114032.2: DMS=6, merged=6
Processing DMS assay NP_115501.2:  49%|██▉   | 761/1555 [01:31<01:40,  7.90it/s]NP_115501.2: DMS=1, merged=1
Processing DMS assay NP_115785.1:  49%|██▉   | 762/1555 [01:31<01:39,  7.98it/s]NP_115785.1: DMS=1, merged=1
Processing DMS assay NP_115791.3:  49%|██▉   | 763/1555 [01:31<01:38,  8.06it/s]NP_115791.3: DMS=1, merged=1
Processing DMS assay NP_115909.1:  49%|██▉   | 764/1555 [01:31<01:41,  7.79it/s]NP_115909.1: DMS=1, merged=1
Processing DMS assay NP_116027.2:  49%|██▉   | 765/1555 [01:31<01:38,  8.02it/s]NP_116027.2: DMS=2, merged=2
Processing DMS assay NP_116250.3:  49%|██▉   | 766/1555 [01:31<01:36,  8.21it/s]Note: HMM scored 2/3 mutants for NP_116250.3; rest left as NaN.
NP_116250.3: DMS=3, merged=3
Processing DMS assay NP_149078.1:  49%|██▉   | 767/1555 [01:32<01:36,  8.13it/s]NP_149078.1: DMS=1, merged=1
Processing DMS assay NP_203123.1:  49%|██▉   | 768/1555 [01:32<01:35,  8.22it/s]NP_203123.1: DMS=1, merged=1
Processing DMS assay NP_203524.1:  49%|██▉   | 769/1555 [01:32<01:34,  8.36it/s]NP_203524.1: DMS=2, merged=2
Processing DMS assay NP_203699.1:  50%|██▉   | 770/1555 [01:32<01:34,  8.29it/s]NP_203699.1: DMS=4, merged=4
Processing DMS assay NP_338599.1:  50%|██▉   | 771/1555 [01:32<01:34,  8.25it/s]NP_338599.1: DMS=2, merged=2
Processing DMS assay NP_443077.1:  50%|██▉   | 772/1555 [01:32<01:34,  8.27it/s]NP_443077.1: DMS=2, merged=2
Processing DMS assay NP_443106.1:  50%|██▉   | 773/1555 [01:32<01:35,  8.22it/s]NP_443106.1: DMS=2, merged=2
Processing DMS assay NP_443715.1:  50%|██▉   | 774/1555 [01:32<01:34,  8.28it/s]NP_443715.1: DMS=1, merged=1
Processing DMS assay NP_444504.1:  50%|██▉   | 775/1555 [01:33<01:37,  7.99it/s]NP_444504.1: DMS=1, merged=1
Processing DMS assay NP_473368.1:  50%|██▉   | 776/1555 [01:33<01:35,  8.12it/s]NP_473368.1: DMS=3, merged=3
Processing DMS assay NP_477352.3:  50%|██▉   | 777/1555 [01:33<01:34,  8.21it/s]NP_477352.3: DMS=1, merged=1
Processing DMS assay NP_510965.1:  50%|███   | 778/1555 [01:33<01:32,  8.37it/s]Note: HMM scored 1/3 mutants for NP_510965.1; rest left as NaN.
NP_510965.1: DMS=3, merged=3
Processing DMS assay NP_542172.2:  50%|███   | 779/1555 [01:33<01:33,  8.33it/s]NP_542172.2: DMS=1, merged=1
Processing DMS assay NP_542411.2:  50%|███   | 780/1555 [01:33<01:31,  8.46it/s]NP_542411.2: DMS=1, merged=1
Processing DMS assay NP_570850.2:  50%|███   | 781/1555 [01:33<01:32,  8.38it/s]NP_570850.2: DMS=1, merged=1
Processing DMS assay NP_570854.1:  50%|███   | 782/1555 [01:33<01:31,  8.44it/s]NP_570854.1: DMS=8, merged=8
Processing DMS assay NP_573566.2:  50%|███   | 783/1555 [01:34<01:32,  8.36it/s]NP_573566.2: DMS=2, merged=2
Processing DMS assay NP_597677.2:  50%|███   | 784/1555 [01:34<01:32,  8.30it/s]Note: HMM scored 11/12 mutants for NP_597677.2; rest left as NaN.
NP_597677.2: DMS=12, merged=12
Processing DMS assay NP_598004.1:  50%|███   | 785/1555 [01:34<01:35,  8.07it/s]NP_598004.1: DMS=1, merged=1
Processing DMS assay NP_612396.1:  51%|███   | 786/1555 [01:34<01:37,  7.85it/s]NP_612396.1: DMS=1, merged=1
Processing DMS assay NP_612422.2:  51%|███   | 787/1555 [01:34<01:36,  7.94it/s]NP_612422.2: DMS=2, merged=2
Processing DMS assay NP_612486.2:  51%|███   | 788/1555 [01:34<01:40,  7.66it/s]NP_612486.2: DMS=1, merged=1
Processing DMS assay NP_620130.2:  51%|███   | 789/1555 [01:34<01:42,  7.45it/s]NP_620130.2: DMS=1, merged=1
Processing DMS assay NP_620596.2:  51%|███   | 790/1555 [01:34<01:39,  7.71it/s]NP_620596.2: DMS=1, merged=1
Processing DMS assay NP_644805.1:  51%|███   | 791/1555 [01:35<01:36,  7.95it/s]NP_644805.1: DMS=1, merged=1
Processing DMS assay NP_653197.2:  51%|███   | 792/1555 [01:35<01:34,  8.04it/s]NP_653197.2: DMS=1, merged=1
Processing DMS assay NP_658985.2:  51%|███   | 793/1555 [01:35<01:33,  8.17it/s]NP_658985.2: DMS=1, merged=1
Processing DMS assay NP_659434.2:  51%|███   | 794/1555 [01:35<01:32,  8.25it/s]NP_659434.2: DMS=4, merged=4
Processing DMS assay NP_660208.2:  51%|███   | 795/1555 [01:35<01:31,  8.31it/s]NP_660208.2: DMS=2, merged=2
Processing DMS assay NP_660289.2:  51%|███   | 796/1555 [01:35<01:31,  8.29it/s]NP_660289.2: DMS=1, merged=1
Processing DMS assay NP_663304.1:  51%|███   | 797/1555 [01:35<01:33,  8.09it/s]NP_663304.1: DMS=4, merged=4
Processing DMS assay NP_689476.2:  51%|███   | 798/1555 [01:35<01:32,  8.16it/s]NP_689476.2: DMS=2, merged=2
Processing DMS assay NP_689509.1:  51%|███   | 799/1555 [01:36<01:32,  8.20it/s]NP_689509.1: DMS=5, merged=5
Processing DMS assay NP_689777.3:  51%|███   | 800/1555 [01:36<01:33,  8.04it/s]NP_689777.3: DMS=1, merged=1
Processing DMS assay NP_689831.2:  52%|███   | 801/1555 [01:36<01:32,  8.14it/s]NP_689831.2: DMS=1, merged=1
Processing DMS assay NP_689945.2:  52%|███   | 802/1555 [01:36<01:30,  8.29it/s]NP_689945.2: DMS=1, merged=1
Processing DMS assay NP_694950.2:  52%|███   | 803/1555 [01:36<01:29,  8.39it/s]NP_694950.2: DMS=1, merged=1
Processing DMS assay NP_694972.3:  52%|███   | 804/1555 [01:36<01:29,  8.43it/s]NP_694972.3: DMS=3, merged=3
Processing DMS assay NP_710156.3:  52%|███   | 805/1555 [01:36<01:29,  8.41it/s]NP_710156.3: DMS=1, merged=1
Processing DMS assay NP_714915.3:  52%|███   | 806/1555 [01:36<01:27,  8.54it/s]NP_714915.3: DMS=1, merged=1
Processing DMS assay NP_714928.1:  52%|███   | 807/1555 [01:36<01:31,  8.19it/s]NP_714928.1: DMS=1, merged=1
Processing DMS assay NP_733751.2:  52%|███   | 808/1555 [01:37<01:29,  8.31it/s]Note: HMM scored 1/2 mutants for NP_733751.2; rest left as NaN.
NP_733751.2: DMS=2, merged=2
Processing DMS assay NP_733765.1:  52%|███   | 809/1555 [01:37<01:33,  8.00it/s]NP_733765.1: DMS=1, merged=1
Processing DMS assay NP_733775.1:  52%|███▏  | 810/1555 [01:37<01:31,  8.13it/s]NP_733775.1: DMS=1, merged=1
Processing DMS assay NP_733821.1:  52%|███▏  | 811/1555 [01:37<01:30,  8.26it/s]NP_733821.1: DMS=9, merged=9
Processing DMS assay NP_742105.1:  52%|███▏  | 812/1555 [01:37<01:30,  8.21it/s]NP_742105.1: DMS=8, merged=8
Processing DMS assay NP_758440.1:  52%|███▏  | 813/1555 [01:37<01:32,  8.06it/s]NP_758440.1: DMS=1, merged=1
Processing DMS assay NP_775109.2:  52%|███▏  | 814/1555 [01:37<01:29,  8.26it/s]NP_775109.2: DMS=1, merged=1
Processing DMS assay NP_775931.3:  52%|███▏  | 815/1555 [01:37<01:27,  8.47it/s]NP_775931.3: DMS=1, merged=1
Processing DMS assay NP_777367.1:  52%|███▏  | 816/1555 [01:38<01:27,  8.49it/s]NP_777367.1: DMS=1, merged=1
Processing DMS assay NP_787110.2:  53%|███▏  | 817/1555 [01:38<01:25,  8.60it/s]NP_787110.2: DMS=2, merged=2
Processing DMS assay NP_789794.1:  53%|███▏  | 818/1555 [01:38<01:29,  8.21it/s]NP_789794.1: DMS=2, merged=2
Processing DMS assay NP_796376.2:  53%|███▏  | 819/1555 [01:38<01:28,  8.33it/s]NP_796376.2: DMS=1, merged=1
Processing DMS assay NP_803187.1:  53%|███▏  | 820/1555 [01:38<01:26,  8.50it/s]NP_803187.1: DMS=3, merged=3
Processing DMS assay NP_808592.2:  53%|███▏  | 821/1555 [01:38<01:26,  8.50it/s]NP_808592.2: DMS=2, merged=2
Processing DMS assay NP_835361.1:  53%|███▏  | 822/1555 [01:38<01:26,  8.51it/s]NP_835361.1: DMS=1, merged=1
Processing DMS assay NP_835464.1:  53%|███▏  | 823/1555 [01:38<01:25,  8.55it/s]NP_835464.1: DMS=1, merged=1
Processing DMS assay NP_849191.3:  53%|███▏  | 824/1555 [01:38<01:26,  8.47it/s]NP_849191.3: DMS=1, merged=1
Processing DMS assay NP_851564.1:  53%|███▏  | 825/1555 [01:39<01:25,  8.54it/s]NP_851564.1: DMS=1, merged=1
Processing DMS assay NP_852091.1:  53%|███▏  | 826/1555 [01:39<01:25,  8.49it/s]NP_852091.1: DMS=1, merged=1
Processing DMS assay NP_852259.1:  53%|███▏  | 827/1555 [01:39<01:29,  8.11it/s]NP_852259.1: DMS=1, merged=1
Processing DMS assay NP_852608.1:  53%|███▏  | 828/1555 [01:39<01:37,  7.45it/s]NP_852608.1: DMS=1, merged=1
Processing DMS assay NP_852664.1:  53%|███▏  | 829/1555 [01:39<01:39,  7.30it/s]NP_852664.1: DMS=6, merged=6
Processing DMS assay NP_859056.2:  53%|███▏  | 830/1555 [01:39<01:37,  7.44it/s]NP_859056.2: DMS=1, merged=1
Processing DMS assay NP_872282.1:  53%|███▏  | 831/1555 [01:39<01:35,  7.60it/s]NP_872282.1: DMS=1, merged=1
Processing DMS assay NP_877435.3:  54%|███▏  | 832/1555 [01:40<01:31,  7.86it/s]NP_877435.3: DMS=1, merged=1
Processing DMS assay NP_891555.2:  54%|███▏  | 833/1555 [01:40<01:32,  7.81it/s]NP_891555.2: DMS=1, merged=1
Processing DMS assay NP_898888.1:  54%|███▏  | 834/1555 [01:40<01:29,  8.05it/s]NP_898888.1: DMS=1, merged=1
Processing DMS assay NP_899058.1:  54%|███▏  | 835/1555 [01:40<01:27,  8.26it/s]NP_899058.1: DMS=1, merged=1
Processing DMS assay NP_899200.1:  54%|███▏  | 836/1555 [01:40<01:26,  8.30it/s]Note: HMM scored 1/2 mutants for NP_899200.1; rest left as NaN.

NP_899200.1: DMS=2, merged=2
Processing DMS assay NP_919224.1:  54%|███▏  | 837/1555 [01:40<01:26,  8.31it/s]NP_919224.1: DMS=2, merged=2
Processing DMS assay NP_919231.1:  54%|███▏  | 838/1555 [01:40<01:25,  8.34it/s]NP_919231.1: DMS=1, merged=1
Processing DMS assay NP_919253.1:  54%|███▏  | 839/1555 [01:40<01:27,  8.15it/s]NP_919253.1: DMS=2, merged=2
Processing DMS assay NP_938148.1:  54%|███▏  | 840/1555 [01:40<01:26,  8.31it/s]NP_938148.1: DMS=1, merged=1
Processing DMS assay NP_940908.3:  54%|███▏  | 841/1555 [01:41<01:24,  8.49it/s]Note: HMM scored 1/2 mutants for NP_940908.3; rest left as NaN.
NP_940908.3: DMS=2, merged=2
Processing DMS assay NP_940927.2:  54%|███▏  | 842/1555 [01:41<01:22,  8.62it/s]Note: HMM scored 1/3 mutants for NP_940927.2; rest left as NaN.
NP_940927.2: DMS=3, merged=3
Processing DMS assay NP_944494.1:  54%|███▎  | 843/1555 [01:41<01:22,  8.60it/s]NP_944494.1: DMS=1, merged=1
Processing DMS assay NP_945345.2:  54%|███▎  | 844/1555 [01:41<01:21,  8.71it/s]Note: HMM scored 1/2 mutants for NP_945345.2; rest left as NaN.
NP_945345.2: DMS=2, merged=2
Processing DMS assay NP_954712.1:  54%|███▎  | 845/1555 [01:41<01:21,  8.72it/s]NP_954712.1: DMS=1, merged=1
Processing DMS assay NP_955631.1:  54%|███▎  | 846/1555 [01:41<01:20,  8.79it/s]Note: HMM scored 1/2 mutants for NP_955631.1; rest left as NaN.
NP_955631.1: DMS=2, merged=2
Processing DMS assay NP_957705.1:  54%|███▎  | 847/1555 [01:41<01:20,  8.79it/s]Note: HMM scored 4/5 mutants for NP_957705.1; rest left as NaN.
NP_957705.1: DMS=5, merged=5
Processing DMS assay NP_958780.1:  55%|███▎  | 848/1555 [01:41<01:21,  8.64it/s]NP_958780.1: DMS=1, merged=1
Processing DMS assay NP_958786.1:  55%|███▎  | 849/1555 [01:42<01:22,  8.61it/s]NP_958786.1: DMS=1, merged=1
Processing DMS assay NP_976035.1:  55%|███▎  | 850/1555 [01:42<01:24,  8.31it/s]NP_976035.1: DMS=1, merged=1
Processing DMS assay NP_981932.1:  55%|███▎  | 851/1555 [01:42<01:24,  8.38it/s]NP_981932.1: DMS=1, merged=1
Processing DMS assay NP_982301.1:  55%|███▎  | 852/1555 [01:42<01:22,  8.54it/s]NP_982301.1: DMS=1, merged=1
Processing DMS assay NP_991331.1:  55%|███▎  | 853/1555 [01:42<01:24,  8.34it/s]NP_991331.1: DMS=1, merged=1
Processing DMS assay NP_996816.3:  55%|███▎  | 854/1555 [01:42<01:26,  8.08it/s]NP_996816.3: DMS=7, merged=7
Processing DMS assay NP_996820.1:  55%|███▎  | 855/1555 [01:42<01:29,  7.79it/s]NP_996820.1: DMS=1, merged=1
Processing DMS assay NP_997244.4:  55%|███▎  | 856/1555 [01:42<01:27,  8.02it/s]Note: HMM scored 1/2 mutants for NP_997244.4; rest left as NaN.
NP_997244.4: DMS=2, merged=2
Processing DMS assay NP_997717.2:  55%|███▎  | 857/1555 [01:43<01:25,  8.20it/s]NP_997717.2: DMS=1, merged=1
Processing DMS assay UPI0000125CAE:  55%|██▏ | 858/1555 [01:43<01:23,  8.36it/s]UPI0000125CAE: DMS=1, merged=1
Processing DMS assay UPI000013C672:  55%|██▏ | 859/1555 [01:43<01:19,  8.78it/s]UPI000013C672: DMS=1, merged=1
Processing DMS assay UPI000035AA82:  55%|██▏ | 859/1555 [01:43<01:19,  8.78it/s]UPI000035AA82: DMS=1, merged=1
Processing DMS assay UPI00001D7B55:  55%|██▏ | 861/1555 [01:43<01:13,  9.39it/s]UPI00001D7B55: DMS=1, merged=1
Processing DMS assay UPI000059D713:  55%|██▏ | 862/1555 [01:43<01:12,  9.52it/s]UPI000059D713: DMS=1, merged=1
Processing DMS assay UPI0000246EE9:  55%|██▏ | 862/1555 [01:43<01:12,  9.52it/s]UPI0000246EE9: DMS=2, merged=2
Processing DMS assay UPI000003C716:  56%|██▏ | 864/1555 [01:43<01:11,  9.70it/s]UPI000003C716: DMS=1, merged=1
Processing DMS assay UPI0001D3B05C:  56%|██▏ | 864/1555 [01:43<01:11,  9.70it/s]UPI0001D3B05C: DMS=1, merged=1
Processing DMS assay UPI000003C48A:  56%|██▏ | 866/1555 [01:43<01:09,  9.89it/s]UPI000003C48A: DMS=1, merged=1
Processing DMS assay UPI0000206D91:  56%|██▏ | 866/1555 [01:44<01:09,  9.89it/s]UPI0000206D91: DMS=1, merged=1
Processing DMS assay UPI00000721F7:  56%|██▏ | 868/1555 [01:44<01:08,  9.97it/s]UPI00000721F7: DMS=1, merged=1
Processing DMS assay UPI000192952A:  56%|██▏ | 868/1555 [01:44<01:08,  9.97it/s]UPI000192952A: DMS=2, merged=2
Processing DMS assay UPI000006EC9A:  56%|██▏ | 870/1555 [01:44<01:08, 10.01it/s]UPI000006EC9A: DMS=1, merged=1
Processing DMS assay UPI00000726A9:  56%|██▏ | 870/1555 [01:44<01:08, 10.01it/s]UPI00000726A9: DMS=1, merged=1
Processing DMS assay UPI000173A2B0:  56%|██▏ | 872/1555 [01:44<01:09,  9.80it/s]UPI000173A2B0: DMS=1, merged=1
Processing DMS assay UPI0000D62424:  56%|██▏ | 872/1555 [01:44<01:09,  9.80it/s]UPI0000D62424: DMS=1, merged=1
Processing DMS assay UPI000022DC3D:  56%|██▏ | 874/1555 [01:44<01:08,  9.95it/s]UPI000022DC3D: DMS=1, merged=1
Processing DMS assay UPI000006DE38:  56%|██▏ | 874/1555 [01:44<01:08,  9.95it/s]UPI000006DE38: DMS=1, merged=1
Processing DMS assay UPI0000033466:  56%|██▎ | 876/1555 [01:44<01:08,  9.98it/s]UPI0000033466: DMS=1, merged=1
Processing DMS assay UPI000020E761:  56%|██▎ | 876/1555 [01:45<01:08,  9.98it/s]UPI000020E761: DMS=1, merged=1
Processing DMS assay UPI000013F0A1:  56%|██▎ | 878/1555 [01:45<01:07, 10.05it/s]UPI000013F0A1: DMS=1, merged=1
Processing DMS assay UPI0000129A56:  56%|██▎ | 878/1555 [01:45<01:07, 10.05it/s]UPI0000129A56: DMS=1, merged=1
Processing DMS assay UPI000013E95E:  57%|██▎ | 880/1555 [01:45<01:06, 10.11it/s]UPI000013E95E: DMS=1, merged=1
Processing DMS assay UPI0000EA87E6:  57%|██▎ | 880/1555 [01:45<01:06, 10.11it/s]UPI0000EA87E6: DMS=3, merged=3
Processing DMS assay UPI000020E4D9:  57%|██▎ | 882/1555 [01:45<01:06, 10.11it/s]UPI000020E4D9: DMS=1, merged=1
Processing DMS assay UPI0000072D37:  57%|██▎ | 882/1555 [01:45<01:06, 10.11it/s]UPI0000072D37: DMS=1, merged=1
Processing DMS assay UPI000059D6C5:  57%|██▎ | 884/1555 [01:45<01:06, 10.16it/s]UPI000059D6C5: DMS=1, merged=1
Processing DMS assay UPI00001D7B9E:  57%|██▎ | 884/1555 [01:45<01:06, 10.16it/s]UPI00001D7B9E: DMS=1, merged=1
Processing DMS assay UPI0000D61A6B:  57%|██▎ | 886/1555 [01:45<01:06, 10.04it/s]UPI0000D61A6B: DMS=1, merged=1
Processing DMS assay UPI000041A715:  57%|██▎ | 886/1555 [01:46<01:06, 10.04it/s]UPI000041A715: DMS=1, merged=1
Processing DMS assay UPI0000001BCE:  57%|██▎ | 888/1555 [01:46<01:06, 10.08it/s]UPI0000001BCE: DMS=1, merged=1
Processing DMS assay UPI0001B79057:  57%|██▎ | 888/1555 [01:46<01:06, 10.08it/s]UPI0001B79057: DMS=1, merged=1
Processing DMS assay UPI000006D1F4:  57%|██▎ | 890/1555 [01:46<01:06, 10.04it/s]UPI000006D1F4: DMS=1, merged=1
Processing DMS assay UPI00015FA087:  57%|██▎ | 890/1555 [01:46<01:06, 10.04it/s]UPI00015FA087: DMS=2, merged=2
Processing DMS assay UPI000047099D:  57%|██▎ | 892/1555 [01:46<01:06,  9.98it/s]UPI000047099D: DMS=2, merged=2
Processing DMS assay UPI000000D866:  57%|██▎ | 893/1555 [01:46<01:06,  9.94it/s]UPI000000D866: DMS=1, merged=1
Processing DMS assay UPI0000DBEE85:  57%|██▎ | 893/1555 [01:46<01:06,  9.94it/s]UPI0000DBEE85: DMS=2, merged=2
Processing DMS assay UPI000000DCCB:  58%|██▎ | 895/1555 [01:46<01:06,  9.99it/s]UPI000000DCCB: DMS=1, merged=1
Processing DMS assay UPI000013C495:  58%|██▎ | 895/1555 [01:46<01:06,  9.99it/s]UPI000013C495: DMS=1, merged=1
Processing DMS assay UPI000016A402:  58%|██▎ | 897/1555 [01:47<01:05, 10.06it/s]UPI000016A402: DMS=1, merged=1
Processing DMS assay UPI00001AE452:  58%|██▎ | 897/1555 [01:47<01:05, 10.06it/s]UPI00001AE452: DMS=1, merged=1
Processing DMS assay UPI0000070A05:  58%|██▎ | 899/1555 [01:47<01:04, 10.09it/s]UPI0000070A05: DMS=1, merged=1
Processing DMS assay UPI000013C9CD:  58%|██▎ | 899/1555 [01:47<01:04, 10.09it/s]UPI000013C9CD: DMS=2, merged=2
Processing DMS assay UPI000004F239:  58%|██▎ | 901/1555 [01:47<01:05, 10.00it/s]UPI000004F239: DMS=1, merged=1
Processing DMS assay UPI0000129FBA:  58%|██▎ | 901/1555 [01:47<01:05, 10.00it/s]UPI0000129FBA: DMS=1, merged=1
Processing DMS assay UPI0000141B94:  58%|██▎ | 903/1555 [01:47<01:04, 10.06it/s]UPI0000141B94: DMS=1, merged=1
Processing DMS assay UPI000046D388:  58%|██▎ | 903/1555 [01:47<01:04, 10.06it/s]UPI000046D388: DMS=1, merged=1
Processing DMS assay UPI00001AEF8F:  58%|██▎ | 905/1555 [01:47<01:04, 10.10it/s]UPI00001AEF8F: DMS=1, merged=1
Processing DMS assay UPI000013ECF6:  58%|██▎ | 905/1555 [01:47<01:04, 10.10it/s]UPI000013ECF6: DMS=1, merged=1
Processing DMS assay UPI0000061E6E:  58%|██▎ | 907/1555 [01:48<01:04, 10.11it/s]UPI0000061E6E: DMS=1, merged=1
Processing DMS assay UPI00001FD815:  58%|██▎ | 907/1555 [01:48<01:04, 10.11it/s]UPI00001FD815: DMS=1, merged=1
Processing DMS assay UPI0000236D8A:  58%|██▎ | 909/1555 [01:48<01:03, 10.14it/s]UPI0000236D8A: DMS=1, merged=1
Processing DMS assay UPI0000237947:  58%|██▎ | 909/1555 [01:48<01:03, 10.14it/s]UPI0000237947: DMS=1, merged=1
Processing DMS assay UPI0000367804:  59%|██▎ | 911/1555 [01:48<01:03, 10.13it/s]UPI0000367804: DMS=1, merged=1
Processing DMS assay UPI00006C069B:  59%|██▎ | 911/1555 [01:48<01:03, 10.13it/s]UPI00006C069B: DMS=1, merged=1
Processing DMS assay UPI000013DBF5:  59%|██▎ | 913/1555 [01:48<01:03, 10.12it/s]UPI000013DBF5: DMS=1, merged=1
Processing DMS assay UPI00015CE746:  59%|██▎ | 913/1555 [01:48<01:03, 10.12it/s]UPI00015CE746: DMS=1, merged=1
Processing DMS assay UPI0000EE57E0:  59%|██▎ | 915/1555 [01:48<01:03, 10.07it/s]UPI0000EE57E0: DMS=1, merged=1
Processing DMS assay UPI000013E9AB:  59%|██▎ | 915/1555 [01:48<01:03, 10.07it/s]UPI000013E9AB: DMS=2, merged=2
Processing DMS assay UPI0000070847:  59%|██▎ | 917/1555 [01:48<01:03, 10.06it/s]UPI0000070847: DMS=1, merged=1
Processing DMS assay UPI000044CC1A:  59%|██▎ | 917/1555 [01:49<01:03, 10.06it/s]UPI000044CC1A: DMS=1, merged=1
Processing DMS assay UPI0000036166:  59%|██▎ | 919/1555 [01:49<01:03, 10.03it/s]UPI0000036166: DMS=1, merged=1
Processing DMS assay UPI000015FC7D:  59%|██▎ | 919/1555 [01:49<01:03, 10.03it/s]UPI000015FC7D: DMS=1, merged=1
Processing DMS assay UPI0000061EA8:  59%|██▎ | 921/1555 [01:49<01:03, 10.01it/s]UPI0000061EA8: DMS=1, merged=1
Processing DMS assay UPI000014083E:  59%|██▎ | 921/1555 [01:49<01:03, 10.01it/s]UPI000014083E: DMS=1, merged=1
Processing DMS assay UPI000012CF7F:  59%|██▎ | 923/1555 [01:49<01:02, 10.06it/s]UPI000012CF7F: DMS=1, merged=1
Processing DMS assay UPI000006EEBC:  59%|██▎ | 923/1555 [01:49<01:02, 10.06it/s]UPI000006EEBC: DMS=1, merged=1
Processing DMS assay UPI000003117A:  59%|██▍ | 925/1555 [01:49<01:02, 10.07it/s]UPI000003117A: DMS=1, merged=1
Processing DMS assay UPI0000D61701:  59%|██▍ | 925/1555 [01:49<01:02, 10.07it/s]UPI0000D61701: DMS=2, merged=2
Processing DMS assay UPI000003777D:  60%|██▍ | 927/1555 [01:49<01:02, 10.03it/s]UPI000003777D: DMS=1, merged=1
Processing DMS assay UPI000000165C:  60%|██▍ | 927/1555 [01:50<01:02, 10.03it/s]UPI000000165C: DMS=1, merged=1
Processing DMS assay UPI000013D46D:  60%|██▍ | 929/1555 [01:50<01:02, 10.05it/s]UPI000013D46D: DMS=1, merged=1
Processing DMS assay UPI0000132189:  60%|██▍ | 929/1555 [01:50<01:02, 10.05it/s]UPI0000132189: DMS=1, merged=1
Processing DMS assay UPI000012ADCB:  60%|██▍ | 931/1555 [01:50<01:02, 10.05it/s]UPI000012ADCB: DMS=1, merged=1
Processing DMS assay UPI000013E315:  60%|██▍ | 931/1555 [01:50<01:02, 10.05it/s]UPI000013E315: DMS=1, merged=1
Processing DMS assay UPI00001402C1:  60%|██▍ | 933/1555 [01:50<01:01, 10.06it/s]UPI00001402C1: DMS=1, merged=1
Processing DMS assay UPI0000237200:  60%|██▍ | 933/1555 [01:50<01:01, 10.06it/s]UPI0000237200: DMS=1, merged=1
Processing DMS assay UPI000013E1E1:  60%|██▍ | 935/1555 [01:50<01:01, 10.04it/s]UPI000013E1E1: DMS=1, merged=1
Processing DMS assay UPI0000186945:  60%|██▍ | 935/1555 [01:50<01:01, 10.04it/s]UPI0000186945: DMS=1, merged=1
Processing DMS assay UPI000013D6EF:  60%|██▍ | 937/1555 [01:50<01:01, 10.02it/s]UPI000013D6EF: DMS=1, merged=1
Processing DMS assay UPI00015DF949:  60%|██▍ | 937/1555 [01:51<01:01, 10.02it/s]UPI00015DF949: DMS=2, merged=2
Processing DMS assay UPI0000072854:  60%|██▍ | 939/1555 [01:51<01:02,  9.83it/s]UPI0000072854: DMS=1, merged=1
Processing DMS assay UPI00003E5903:  60%|██▍ | 940/1555 [01:51<01:02,  9.83it/s]UPI00003E5903: DMS=1, merged=1
Processing DMS assay UPI000015D1F5:  60%|██▍ | 940/1555 [01:51<01:02,  9.83it/s]UPI000015D1F5: DMS=1, merged=1
Processing DMS assay UPI000013EA48:  61%|██▍ | 942/1555 [01:51<01:01,  9.93it/s]UPI000013EA48: DMS=1, merged=1
Processing DMS assay UPI0000137929:  61%|██▍ | 942/1555 [01:51<01:01,  9.93it/s]UPI0000137929: DMS=1, merged=1
Processing DMS assay UPI00001983C7:  61%|██▍ | 944/1555 [01:51<01:00, 10.03it/s]UPI00001983C7: DMS=1, merged=1
Processing DMS assay UPI000022AA0A:  61%|██▍ | 944/1555 [01:51<01:00, 10.03it/s]UPI000022AA0A: DMS=1, merged=1
Processing DMS assay UPI000013D193:  61%|██▍ | 946/1555 [01:51<01:00, 10.07it/s]UPI000013D193: DMS=1, merged=1
Processing DMS assay UPI000006CD59:  61%|██▍ | 946/1555 [01:51<01:00, 10.07it/s]UPI000006CD59: DMS=1, merged=1
Processing DMS assay UPI000006DC1A:  61%|██▍ | 948/1555 [01:52<01:00, 10.11it/s]UPI000006DC1A: DMS=2, merged=2
Processing DMS assay UPI00001AEEF8:  61%|██▍ | 948/1555 [01:52<01:00, 10.11it/s]UPI00001AEEF8: DMS=1, merged=1
Processing DMS assay UPI0000D61944:  61%|██▍ | 950/1555 [01:52<01:00, 10.06it/s]UPI0000D61944: DMS=1, merged=1
Processing DMS assay UPI0000127786:  61%|██▍ | 950/1555 [01:52<01:00, 10.06it/s]UPI0000127786: DMS=1, merged=1
Processing DMS assay UPI0000458963:  61%|██▍ | 952/1555 [01:52<01:01,  9.87it/s]UPI0000458963: DMS=1, merged=1
Processing DMS assay UPI0000458979:  61%|██▍ | 953/1555 [01:52<01:00,  9.87it/s]UPI0000458979: DMS=1, merged=1
Processing DMS assay UPI000041EA63:  61%|██▍ | 954/1555 [01:52<01:00,  9.86it/s]UPI000041EA63: DMS=1, merged=1
Processing DMS assay UPI0000D4C11A:  61%|██▍ | 955/1555 [01:52<01:01,  9.80it/s]UPI0000D4C11A: DMS=2, merged=2
Processing DMS assay UPI0000135F21:  61%|██▍ | 956/1555 [01:52<01:01,  9.74it/s]UPI0000135F21: DMS=5, merged=5
Processing DMS assay UPI00006EB135:  62%|██▍ | 957/1555 [01:53<01:01,  9.75it/s]UPI00006EB135: DMS=1, merged=1
Processing DMS assay UPI00003667EB:  62%|██▍ | 957/1555 [01:53<01:01,  9.75it/s]UPI00003667EB: DMS=3, merged=3
Processing DMS assay UPI000020198E:  62%|██▍ | 959/1555 [01:53<01:00,  9.80it/s]UPI000020198E: DMS=1, merged=1
Processing DMS assay UPI00001C1FC7:  62%|██▍ | 960/1555 [01:53<01:00,  9.78it/s]UPI00001C1FC7: DMS=1, merged=1
Processing DMS assay UPI00005C3036:  62%|██▍ | 961/1555 [01:53<01:00,  9.81it/s]UPI00005C3036: DMS=1, merged=1
Processing DMS assay UPI0001E92A31:  62%|██▍ | 961/1555 [01:53<01:00,  9.81it/s]UPI0001E92A31: DMS=1, merged=1
Processing DMS assay UPI00001D7CA5:  62%|██▍ | 963/1555 [01:53<00:59, 10.02it/s]UPI00001D7CA5: DMS=1, merged=1
Processing DMS assay UPI00004DDA7C:  62%|██▍ | 963/1555 [01:53<00:59, 10.02it/s]UPI00004DDA7C: DMS=1, merged=1
Processing DMS assay UPI000013C519:  62%|██▍ | 965/1555 [01:53<00:58, 10.09it/s]UPI000013C519: DMS=1, merged=1
Processing DMS assay UPI000015FEF2:  62%|██▍ | 965/1555 [01:53<00:58, 10.09it/s]UPI000015FEF2: DMS=1, merged=1
Processing DMS assay UPI000012500C:  62%|██▍ | 967/1555 [01:54<01:01,  9.58it/s]UPI000012500C: DMS=1, merged=1
Processing DMS assay UPI000204AD4D:  62%|██▍ | 968/1555 [01:54<01:01,  9.54it/s]UPI000204AD4D: DMS=1, merged=1
Processing DMS assay UPI000013D247:  62%|██▍ | 969/1555 [01:54<01:01,  9.50it/s]UPI000013D247: DMS=1, merged=1
Processing DMS assay UPI000012ECF8:  62%|██▍ | 970/1555 [01:54<01:01,  9.59it/s]UPI000012ECF8: DMS=1, merged=1
Processing DMS assay UPI0000167B81:  62%|██▍ | 970/1555 [01:54<01:01,  9.59it/s]UPI0000167B81: DMS=1, merged=1
Processing DMS assay UPI000013EF3A:  63%|██▌ | 972/1555 [01:54<00:59,  9.83it/s]UPI000013EF3A: DMS=1, merged=1
Processing DMS assay UPI000046FEDB:  63%|██▌ | 972/1555 [01:54<00:59,  9.83it/s]UPI000046FEDB: DMS=1, merged=1
Processing DMS assay UPI000007007F:  63%|██▌ | 974/1555 [01:54<00:58,  9.90it/s]UPI000007007F: DMS=3, merged=3
Processing DMS assay UPI0001D3B409:  63%|██▌ | 975/1555 [01:54<00:58,  9.83it/s]UPI0001D3B409: DMS=1, merged=1
Processing DMS assay UPI00001BD8AE:  63%|██▌ | 976/1555 [01:54<00:58,  9.86it/s]UPI00001BD8AE: DMS=1, merged=1
Processing DMS assay UPI00015ADD19:  63%|██▌ | 977/1555 [01:55<00:58,  9.87it/s]UPI00015ADD19: DMS=1, merged=1
Processing DMS assay UPI00001604C8:  63%|██▌ | 977/1555 [01:55<00:58,  9.87it/s]UPI00001604C8: DMS=1, merged=1
Processing DMS assay UPI00005956CD:  63%|██▌ | 979/1555 [01:55<00:57,  9.96it/s]UPI00005956CD: DMS=1, merged=1
Processing DMS assay UPI0000071CBA:  63%|██▌ | 980/1555 [01:55<00:57,  9.93it/s]UPI0000071CBA: DMS=1, merged=1

Processing DMS assay UPI000013E29D:  63%|██▌ | 980/1555 [01:55<00:57,  9.93it/s]UPI000013E29D: DMS=1, merged=1
Processing DMS assay UPI000003F57A:  63%|██▌ | 982/1555 [01:55<00:57,  9.99it/s]UPI000003F57A: DMS=1, merged=1
Processing DMS assay UPI0000160243:  63%|██▌ | 983/1555 [01:55<00:57,  9.99it/s]UPI0000160243: DMS=1, merged=1
Processing DMS assay UPI0001F784C6:  63%|██▌ | 984/1555 [01:55<00:57,  9.97it/s]UPI0001F784C6: DMS=2, merged=2
Processing DMS assay UPI00004708E6:  63%|██▌ | 985/1555 [01:55<00:57,  9.96it/s]UPI00004708E6: DMS=2, merged=2
Processing DMS assay UPI00001AE6F8:  63%|██▌ | 985/1555 [01:55<00:57,  9.96it/s]UPI00001AE6F8: DMS=3, merged=3
Processing DMS assay UPI000013F990:  63%|██▌ | 987/1555 [01:56<00:57,  9.96it/s]UPI000013F990: DMS=1, merged=1
Processing DMS assay UPI000156FA8B:  64%|██▌ | 988/1555 [01:56<00:57,  9.93it/s]UPI000156FA8B: DMS=1, merged=1
Processing DMS assay UPI00001FF5EB:  64%|██▌ | 989/1555 [01:56<00:57,  9.88it/s]UPI00001FF5EB: DMS=2, merged=2
Processing DMS assay UPI00016632FD:  64%|██▌ | 990/1555 [01:56<00:57,  9.89it/s]UPI00016632FD: DMS=1, merged=1
Processing DMS assay UPI0000199CEF:  64%|██▌ | 990/1555 [01:56<00:57,  9.89it/s]UPI0000199CEF: DMS=1, merged=1
Processing DMS assay UPI00021CF38C:  64%|██▌ | 992/1555 [01:56<00:57,  9.84it/s]UPI00021CF38C: DMS=1, merged=1
Processing DMS assay UPI000013D80E:  64%|██▌ | 992/1555 [01:56<00:57,  9.84it/s]UPI000013D80E: DMS=1, merged=1
Processing DMS assay UPI000013D6CB:  64%|██▌ | 994/1555 [01:56<00:56,  9.99it/s]UPI000013D6CB: DMS=1, merged=1
Processing DMS assay UPI000013D7E3:  64%|██▌ | 994/1555 [01:56<00:56,  9.99it/s]UPI000013D7E3: DMS=1, merged=1
Processing DMS assay UPI000013CCDF:  64%|██▌ | 996/1555 [01:56<00:56,  9.95it/s]UPI000013CCDF: DMS=1, merged=1
Processing DMS assay UPI00000503E3:  64%|██▌ | 996/1555 [01:57<00:56,  9.95it/s]UPI00000503E3: DMS=1, merged=1
Processing DMS assay UPI000006D8B0:  64%|██▌ | 998/1555 [01:57<00:55, 10.07it/s]UPI000006D8B0: DMS=3, merged=3
Processing DMS assay UPI0001B794AD:  64%|██▌ | 998/1555 [01:57<00:55, 10.07it/s]UPI0001B794AD: DMS=1, merged=1
Processing DMS assay UPI000007413A:  64%|█▉ | 1000/1555 [01:57<00:55, 10.05it/s]UPI000007413A: DMS=1, merged=1
Processing DMS assay UPI000012CF8B:  64%|█▉ | 1000/1555 [01:57<00:55, 10.05it/s]UPI000012CF8B: DMS=1, merged=1
Processing DMS assay UPI000020A0AE:  64%|█▉ | 1002/1555 [01:57<00:55, 10.05it/s]UPI000020A0AE: DMS=1, merged=1
Processing DMS assay UPI00001323E1:  64%|█▉ | 1002/1555 [01:57<00:55, 10.05it/s]UPI00001323E1: DMS=1, merged=1
Processing DMS assay UPI0000136846:  65%|█▉ | 1004/1555 [01:57<00:54, 10.08it/s]UPI0000136846: DMS=1, merged=1
Processing DMS assay UPI00000742DC:  65%|█▉ | 1004/1555 [01:57<00:54, 10.08it/s]UPI00000742DC: DMS=1, merged=1
Processing DMS assay UPI0000203ED6:  65%|█▉ | 1006/1555 [01:57<00:54, 10.11it/s]UPI0000203ED6: DMS=1, merged=1
Processing DMS assay UPI000178DEEC:  65%|█▉ | 1006/1555 [01:58<00:54, 10.11it/s]UPI000178DEEC: DMS=1, merged=1
Processing DMS assay UPI000045725F:  65%|█▉ | 1008/1555 [01:58<00:53, 10.16it/s]UPI000045725F: DMS=1, merged=1
Processing DMS assay UPI00033351D1:  65%|█▉ | 1008/1555 [01:58<00:53, 10.16it/s]UPI00033351D1: DMS=1, merged=1
Processing DMS assay UPI00001D8160:  65%|█▉ | 1010/1555 [01:58<00:53, 10.10it/s]UPI00001D8160: DMS=1, merged=1
Processing DMS assay UPI0000038CE3:  65%|█▉ | 1010/1555 [01:58<00:53, 10.10it/s]UPI0000038CE3: DMS=1, merged=1
Processing DMS assay UPI0000070D27:  65%|█▉ | 1012/1555 [01:58<00:54, 10.03it/s]UPI0000070D27: DMS=1, merged=1
Processing DMS assay UPI0001B79456:  65%|█▉ | 1012/1555 [01:58<00:54, 10.03it/s]UPI0001B79456: DMS=1, merged=1
Processing DMS assay UPI00002021CA:  65%|█▉ | 1014/1555 [01:58<00:54,  9.99it/s]UPI00002021CA: DMS=1, merged=1
Processing DMS assay UPI000013CD7C:  65%|█▉ | 1014/1555 [01:58<00:54,  9.99it/s]UPI000013CD7C: DMS=1, merged=1
Processing DMS assay UPI0000071891:  65%|█▉ | 1016/1555 [01:58<00:54,  9.96it/s]UPI0000071891: DMS=1, merged=1
Processing DMS assay UPI000013D6B1:  65%|█▉ | 1016/1555 [01:59<00:54,  9.96it/s]UPI000013D6B1: DMS=1, merged=1
Processing DMS assay UPI000013DEA0:  65%|█▉ | 1018/1555 [01:59<00:53, 10.01it/s]UPI000013DEA0: DMS=2, merged=2
Processing DMS assay UPI000000D799:  65%|█▉ | 1018/1555 [01:59<00:53, 10.01it/s]UPI000000D799: DMS=1, merged=1
Processing DMS assay UPI000013C5D0:  66%|█▉ | 1020/1555 [01:59<00:54,  9.88it/s]UPI000013C5D0: DMS=1, merged=1
Processing DMS assay UPI000013C34D:  66%|█▉ | 1021/1555 [01:59<00:54,  9.84it/s]UPI000013C34D: DMS=1, merged=1
Processing DMS assay UPI00000743C2:  66%|█▉ | 1022/1555 [01:59<00:54,  9.77it/s]UPI00000743C2: DMS=1, merged=1
Processing DMS assay UPI0000000A01:  66%|█▉ | 1023/1555 [01:59<00:55,  9.66it/s]UPI0000000A01: DMS=1, merged=1
Processing DMS assay UPI000013C6CB:  66%|█▉ | 1024/1555 [01:59<00:55,  9.63it/s]UPI000013C6CB: DMS=1, merged=1
Processing DMS assay UPI00001B4EFC:  66%|█▉ | 1025/1555 [01:59<00:55,  9.55it/s]UPI00001B4EFC: DMS=5, merged=5
Processing DMS assay UPI00001FDCF7:  66%|█▉ | 1026/1555 [02:00<00:56,  9.32it/s]UPI00001FDCF7: DMS=1, merged=1
Processing DMS assay UPI00002263B3:  66%|█▉ | 1027/1555 [02:00<00:58,  8.99it/s]UPI00002263B3: DMS=1, merged=1
Processing DMS assay UPI0000197460:  66%|█▉ | 1028/1555 [02:00<01:03,  8.36it/s]UPI0000197460: DMS=2, merged=2
Processing DMS assay UPI000013E592:  66%|█▉ | 1029/1555 [02:00<01:01,  8.56it/s]UPI000013E592: DMS=2, merged=2
Processing DMS assay UPI00004DDD95:  66%|█▉ | 1030/1555 [02:00<00:58,  8.93it/s]UPI00004DDD95: DMS=1, merged=1
Processing DMS assay UPI0000D616C3:  66%|█▉ | 1031/1555 [02:00<00:56,  9.20it/s]UPI0000D616C3: DMS=1, merged=1
Processing DMS assay UPI0000129B6F:  66%|█▉ | 1032/1555 [02:00<00:55,  9.42it/s]UPI0000129B6F: DMS=1, merged=1
Processing DMS assay UPI00004588F6:  66%|█▉ | 1032/1555 [02:00<00:55,  9.42it/s]UPI00004588F6: DMS=1, merged=1
Processing DMS assay UPI000035B018:  66%|█▉ | 1034/1555 [02:00<00:53,  9.75it/s]UPI000035B018: DMS=1, merged=1
Processing DMS assay UPI0000071C18:  66%|█▉ | 1034/1555 [02:00<00:53,  9.75it/s]UPI0000071C18: DMS=1, merged=1
Processing DMS assay UPI00001C1EF8:  67%|█▉ | 1036/1555 [02:01<00:52,  9.89it/s]UPI00001C1EF8: DMS=1, merged=1
Processing DMS assay UPI0000405B22:  67%|██ | 1037/1555 [02:01<00:52,  9.85it/s]UPI0000405B22: DMS=1, merged=1
Processing DMS assay UPI000012B3DF:  67%|██ | 1037/1555 [02:01<00:52,  9.85it/s]UPI000012B3DF: DMS=1, merged=1
Processing DMS assay UPI000006FBBD:  67%|██ | 1039/1555 [02:01<00:52,  9.92it/s]UPI000006FBBD: DMS=1, merged=1
Processing DMS assay UPI0000161087:  67%|██ | 1039/1555 [02:01<00:52,  9.92it/s]UPI0000161087: DMS=1, merged=1
Processing DMS assay UPI000020630A:  67%|██ | 1041/1555 [02:01<00:51,  9.91it/s]UPI000020630A: DMS=2, merged=2
Processing DMS assay UPI00003D7962:  67%|██ | 1042/1555 [02:01<00:52,  9.71it/s]UPI00003D7962: DMS=1, merged=1
Processing DMS assay UPI000020E164:  67%|██ | 1043/1555 [02:01<00:53,  9.59it/s]UPI000020E164: DMS=1, merged=1
Processing DMS assay UPI00000738BA:  67%|██ | 1044/1555 [02:01<00:53,  9.48it/s]UPI00000738BA: DMS=3, merged=3
Processing DMS assay UPI0001B300F3:  67%|██ | 1045/1555 [02:02<00:54,  9.40it/s]UPI0001B300F3: DMS=4, merged=4
Processing DMS assay UPI00004193C9:  67%|██ | 1046/1555 [02:02<00:54,  9.39it/s]UPI00004193C9: DMS=1, merged=1
Processing DMS assay UPI000013D01B:  67%|██ | 1047/1555 [02:02<00:55,  9.13it/s]UPI000013D01B: DMS=1, merged=1
Processing DMS assay UPI0000366BAD:  67%|██ | 1048/1555 [02:02<00:54,  9.25it/s]UPI0000366BAD: DMS=2, merged=2
Processing DMS assay UPI000012DA10:  67%|██ | 1049/1555 [02:02<00:53,  9.44it/s]UPI000012DA10: DMS=1, merged=1
Processing DMS assay UPI0001E8F4C1:  67%|██ | 1049/1555 [02:02<00:53,  9.44it/s]UPI0001E8F4C1: DMS=1, merged=1
Processing DMS assay UPI0002A47099:  68%|██ | 1051/1555 [02:02<00:51,  9.80it/s]UPI0002A47099: DMS=1, merged=1
Processing DMS assay UPI0002840CC6:  68%|██ | 1051/1555 [02:02<00:51,  9.80it/s]UPI0002840CC6: DMS=1, merged=1
Processing DMS assay UPI0000160791:  68%|██ | 1053/1555 [02:02<00:51,  9.83it/s]UPI0000160791: DMS=1, merged=1
Processing DMS assay UPI000041A871:  68%|██ | 1054/1555 [02:02<00:51,  9.78it/s]UPI000041A871: DMS=1, merged=1

Processing DMS assay UPI000049DE26:  68%|██ | 1055/1555 [02:03<00:51,  9.68it/s]UPI000049DE26: DMS=2, merged=2
Processing DMS assay UPI000012DC9B:  68%|██ | 1056/1555 [02:03<00:51,  9.60it/s]UPI000012DC9B: DMS=1, merged=1
Processing DMS assay UPI000013FD3E:  68%|██ | 1057/1555 [02:03<00:51,  9.65it/s]UPI000013FD3E: DMS=1, merged=1
Processing DMS assay UPI00004191D3:  68%|██ | 1057/1555 [02:03<00:51,  9.65it/s]UPI00004191D3: DMS=1, merged=1
Processing DMS assay UPI0000359605:  68%|██ | 1059/1555 [02:03<00:50,  9.80it/s]UPI0000359605: DMS=1, merged=1
Processing DMS assay UPI000013CC65:  68%|██ | 1060/1555 [02:03<00:50,  9.85it/s]UPI000013CC65: DMS=1, merged=1
Processing DMS assay UPI00001B03C6:  68%|██ | 1061/1555 [02:03<00:50,  9.81it/s]UPI00001B03C6: DMS=1, merged=1
Processing DMS assay UPI000059DB31:  68%|██ | 1061/1555 [02:03<00:50,  9.81it/s]UPI000059DB31: DMS=1, merged=1
Processing DMS assay UPI0000E5AEF3:  68%|██ | 1063/1555 [02:03<00:49,  9.98it/s]UPI0000E5AEF3: DMS=1, merged=1
Processing DMS assay UPI000155B91C:  68%|██ | 1064/1555 [02:03<00:49,  9.96it/s]UPI000155B91C: DMS=1, merged=1
Processing DMS assay UPI000013E535:  68%|██ | 1064/1555 [02:04<00:49,  9.96it/s]UPI000013E535: DMS=1, merged=1
Processing DMS assay UPI0001B3CB30:  69%|██ | 1066/1555 [02:04<00:48, 10.01it/s]UPI0001B3CB30: DMS=3, merged=3
Processing DMS assay UPI0002064E1F:  69%|██ | 1067/1555 [02:04<00:49,  9.86it/s]UPI0002064E1F: DMS=1, merged=1
Processing DMS assay UPI0000132184:  69%|██ | 1068/1555 [02:04<00:49,  9.79it/s]UPI0000132184: DMS=1, merged=1
Processing DMS assay UPI0000141565:  69%|██ | 1069/1555 [02:04<00:49,  9.76it/s]UPI0000141565: DMS=3, merged=3
Processing DMS assay UPI0001711D28:  69%|██ | 1070/1555 [02:04<00:49,  9.73it/s]UPI0001711D28: DMS=2, merged=2
Processing DMS assay UPI000059D669:  69%|██ | 1071/1555 [02:04<00:50,  9.65it/s]UPI000059D669: DMS=1, merged=1
Processing DMS assay UPI000012DDC2:  69%|██ | 1072/1555 [02:04<00:49,  9.73it/s]UPI000012DDC2: DMS=1, merged=1
Processing DMS assay UPI000013E37F:  69%|██ | 1073/1555 [02:04<00:49,  9.68it/s]UPI000013E37F: DMS=1, merged=1
Processing DMS assay UPI00000557D8:  69%|██ | 1073/1555 [02:04<00:49,  9.68it/s]UPI00000557D8: DMS=1, merged=1
Processing DMS assay UPI000007206C:  69%|██ | 1075/1555 [02:05<00:48,  9.89it/s]UPI000007206C: DMS=1, merged=1
Processing DMS assay UPI00000723B9:  69%|██ | 1075/1555 [02:05<00:48,  9.89it/s]UPI00000723B9: DMS=1, merged=1
Processing DMS assay UPI000013C350:  69%|██ | 1077/1555 [02:05<00:48,  9.88it/s]UPI000013C350: DMS=1, merged=1
Processing DMS assay UPI00001301E8:  69%|██ | 1078/1555 [02:05<00:48,  9.77it/s]UPI00001301E8: DMS=2, merged=2
Processing DMS assay UPI0000198666:  69%|██ | 1079/1555 [02:05<00:49,  9.59it/s]UPI0000198666: DMS=3, merged=3
Processing DMS assay UPI000013E667:  69%|██ | 1080/1555 [02:05<00:49,  9.62it/s]UPI000013E667: DMS=1, merged=1
Processing DMS assay UPI0000212176:  70%|██ | 1081/1555 [02:05<00:48,  9.68it/s]UPI0000212176: DMS=1, merged=1
Processing DMS assay UPI00001615E1:  70%|██ | 1082/1555 [02:05<00:48,  9.72it/s]UPI00001615E1: DMS=1, merged=1
Processing DMS assay UPI0000197DF0:  70%|██ | 1083/1555 [02:05<00:48,  9.73it/s]UPI0000197DF0: DMS=1, merged=1
Processing DMS assay UPI00003519AE:  70%|██ | 1084/1555 [02:06<00:48,  9.78it/s]UPI00003519AE: DMS=1, merged=1
Processing DMS assay UPI00001279CC:  70%|██ | 1085/1555 [02:06<00:48,  9.73it/s]UPI00001279CC: DMS=1, merged=1
Processing DMS assay UPI000006F3AC:  70%|██ | 1086/1555 [02:06<00:48,  9.69it/s]UPI000006F3AC: DMS=1, merged=1
Processing DMS assay UPI000040C55F:  70%|██ | 1087/1555 [02:06<00:49,  9.46it/s]UPI000040C55F: DMS=1, merged=1
Processing DMS assay UPI00001AE729:  70%|██ | 1088/1555 [02:06<00:49,  9.46it/s]UPI00001AE729: DMS=1, merged=1
Processing DMS assay UPI0000DA182F:  70%|██ | 1089/1555 [02:06<00:48,  9.54it/s]UPI0000DA182F: DMS=1, merged=1
Processing DMS assay UPI0000E5ADF3:  70%|██ | 1090/1555 [02:06<00:48,  9.58it/s]UPI0000E5ADF3: DMS=1, merged=1
Processing DMS assay UPI0001D0434B:  70%|██ | 1091/1555 [02:06<00:48,  9.58it/s]UPI0001D0434B: DMS=2, merged=2
Processing DMS assay UPI0001662AC1:  70%|██ | 1092/1555 [02:06<00:48,  9.52it/s]UPI0001662AC1: DMS=1, merged=1
Processing DMS assay UPI000011785A:  70%|██ | 1093/1555 [02:06<00:48,  9.43it/s]UPI000011785A: DMS=1, merged=1
Processing DMS assay UPI0001837EA2:  70%|██ | 1094/1555 [02:07<00:48,  9.54it/s]UPI0001837EA2: DMS=2, merged=2
Processing DMS assay UPI00001320B0:  70%|██ | 1095/1555 [02:07<00:48,  9.46it/s]UPI00001320B0: DMS=2, merged=2
Processing DMS assay UPI0000052A8C:  70%|██ | 1096/1555 [02:07<00:48,  9.54it/s]UPI0000052A8C: DMS=1, merged=1
Processing DMS assay UPI00021CF3CC:  71%|██ | 1097/1555 [02:07<00:47,  9.56it/s]UPI00021CF3CC: DMS=1, merged=1
Processing DMS assay UPI000002B371:  71%|██ | 1098/1555 [02:07<00:47,  9.60it/s]UPI000002B371: DMS=1, merged=1
Processing DMS assay UPI0002840938:  71%|██ | 1099/1555 [02:07<00:47,  9.59it/s]UPI0002840938: DMS=1, merged=1
Processing DMS assay UPI0001747A7C:  71%|██ | 1100/1555 [02:07<00:47,  9.63it/s]UPI0001747A7C: DMS=1, merged=1
Processing DMS assay UPI0001C0B37D:  71%|██ | 1101/1555 [02:07<00:47,  9.62it/s]UPI0001C0B37D: DMS=1, merged=1
Processing DMS assay UPI0000136B58:  71%|██▏| 1102/1555 [02:07<00:46,  9.66it/s]UPI0000136B58: DMS=1, merged=1
Processing DMS assay UPI000013DF8A:  71%|██▏| 1103/1555 [02:07<00:46,  9.70it/s]UPI000013DF8A: DMS=1, merged=1
Processing DMS assay UPI000013EFE9:  71%|██▏| 1104/1555 [02:08<00:46,  9.66it/s]UPI000013EFE9: DMS=1, merged=1
Processing DMS assay UPI00015B3C70:  71%|██▏| 1105/1555 [02:08<00:46,  9.69it/s]UPI00015B3C70: DMS=1, merged=1
Processing DMS assay UPI00006E232B:  71%|██▏| 1106/1555 [02:08<00:46,  9.64it/s]UPI00006E232B: DMS=1, merged=1
Processing DMS assay UPI000016021B:  71%|██▏| 1106/1555 [02:08<00:46,  9.64it/s]UPI000016021B: DMS=1, merged=1
Processing DMS assay UPI000013D057:  71%|██▏| 1108/1555 [02:08<00:45,  9.80it/s]UPI000013D057: DMS=1, merged=1
Processing DMS assay UPI000000127D:  71%|██▏| 1108/1555 [02:08<00:45,  9.80it/s]UPI000000127D: DMS=1, merged=1
Processing DMS assay UPI00003588F0:  71%|██▏| 1110/1555 [02:08<00:44,  9.90it/s]UPI00003588F0: DMS=1, merged=1
Processing DMS assay UPI0000E671FE:  71%|██▏| 1110/1555 [02:08<00:44,  9.90it/s]UPI0000E671FE: DMS=1, merged=1
Processing DMS assay UPI0000DBEF37:  72%|██▏| 1112/1555 [02:08<00:44,  9.90it/s]UPI0000DBEF37: DMS=1, merged=1
Processing DMS assay UPI00001A832D:  72%|██▏| 1113/1555 [02:09<00:44,  9.84it/s]UPI00001A832D: DMS=1, merged=1
Processing DMS assay UPI000004C619:  72%|██▏| 1114/1555 [02:09<00:46,  9.49it/s]UPI000004C619: DMS=1, merged=1
Processing DMS assay UPI0000046406:  72%|██▏| 1115/1555 [02:09<00:46,  9.53it/s]UPI0000046406: DMS=1, merged=1
Processing DMS assay UPI00003D4D6C:  72%|██▏| 1116/1555 [02:09<00:46,  9.54it/s]UPI00003D4D6C: DMS=1, merged=1
Processing DMS assay UPI00002020EB:  72%|██▏| 1117/1555 [02:09<00:45,  9.54it/s]UPI00002020EB: DMS=3, merged=3
Processing DMS assay UPI0000039B1A:  72%|██▏| 1118/1555 [02:09<00:46,  9.50it/s]UPI0000039B1A: DMS=1, merged=1
Processing DMS assay UPI0000039E60:  72%|██▏| 1119/1555 [02:09<00:46,  9.33it/s]UPI0000039E60: DMS=1, merged=1
Processing DMS assay UPI0000070C71:  72%|██▏| 1120/1555 [02:09<00:46,  9.30it/s]UPI0000070C71: DMS=1, merged=1
Processing DMS assay UPI0001612CC0:  72%|██▏| 1121/1555 [02:09<00:46,  9.35it/s]UPI0001612CC0: DMS=1, merged=1
Processing DMS assay UPI00001AE77D:  72%|██▏| 1122/1555 [02:09<00:45,  9.48it/s]UPI00001AE77D: DMS=1, merged=1
Processing DMS assay UPI0001AE68B4:  72%|██▏| 1123/1555 [02:10<00:45,  9.47it/s]UPI0001AE68B4: DMS=1, merged=1
Processing DMS assay UPI000204A78B:  72%|██▏| 1124/1555 [02:10<00:44,  9.62it/s]UPI000204A78B: DMS=1, merged=1
Processing DMS assay UPI0000167E20:  72%|██▏| 1124/1555 [02:10<00:44,  9.62it/s]UPI0000167E20: DMS=1, merged=1
Processing DMS assay UPI000003B115:  72%|██▏| 1126/1555 [02:10<00:44,  9.73it/s]UPI000003B115: DMS=1, merged=1
Processing DMS assay UPI000006EEEC:  72%|██▏| 1126/1555 [02:10<00:44,  9.73it/s]UPI000006EEEC: DMS=1, merged=1
Processing DMS assay UPI00001BDC7C:  73%|██▏| 1128/1555 [02:10<00:43,  9.84it/s]UPI00001BDC7C: DMS=2, merged=2

Processing DMS assay UPI000045779F:  73%|██▏| 1129/1555 [02:10<00:43,  9.73it/s]UPI000045779F: DMS=2, merged=2
Processing DMS assay UPI0002840E7F:  73%|██▏| 1130/1555 [02:10<00:43,  9.76it/s]UPI0002840E7F: DMS=1, merged=1
Processing DMS assay UPI000020ADBC:  73%|██▏| 1130/1555 [02:10<00:43,  9.76it/s]UPI000020ADBC: DMS=2, merged=2
Processing DMS assay UPI0000457614:  73%|██▏| 1132/1555 [02:10<00:42,  9.85it/s]UPI0000457614: DMS=1, merged=1
Processing DMS assay UPI000013CF5D:  73%|██▏| 1133/1555 [02:11<00:43,  9.81it/s]UPI000013CF5D: DMS=2, merged=2
Processing DMS assay UPI0000070A3C:  73%|██▏| 1134/1555 [02:11<00:42,  9.83it/s]UPI0000070A3C: DMS=2, merged=2
Processing DMS assay UPI0000198BEF:  73%|██▏| 1135/1555 [02:11<00:42,  9.82it/s]UPI0000198BEF: DMS=1, merged=1
Processing DMS assay UPI0000136C3F:  73%|██▏| 1136/1555 [02:11<00:42,  9.84it/s]UPI0000136C3F: DMS=1, merged=1
Processing DMS assay UPI00000719CD:  73%|██▏| 1136/1555 [02:11<00:42,  9.84it/s]UPI00000719CD: DMS=1, merged=1
Processing DMS assay UPI00000725EE:  73%|██▏| 1138/1555 [02:11<00:42,  9.92it/s]UPI00000725EE: DMS=1, merged=1
Processing DMS assay UPI0000D617B1:  73%|██▏| 1138/1555 [02:11<00:42,  9.92it/s]UPI0000D617B1: DMS=1, merged=1
Processing DMS assay UPI000003166A:  73%|██▏| 1140/1555 [02:11<00:41, 10.02it/s]UPI000003166A: DMS=1, merged=1
Processing DMS assay UPI000023271E:  73%|██▏| 1140/1555 [02:11<00:41, 10.02it/s]UPI000023271E: DMS=1, merged=1
Processing DMS assay UPI0000129CA7:  73%|██▏| 1142/1555 [02:11<00:40, 10.15it/s]UPI0000129CA7: DMS=1, merged=1
Processing DMS assay UPI0000456F25:  73%|██▏| 1142/1555 [02:12<00:40, 10.15it/s]UPI0000456F25: DMS=1, merged=1
Processing DMS assay UPI00001C1C97:  74%|██▏| 1144/1555 [02:12<00:40, 10.12it/s]UPI00001C1C97: DMS=1, merged=1
Processing DMS assay UPI0000001C9F:  74%|██▏| 1144/1555 [02:12<00:40, 10.12it/s]UPI0000001C9F: DMS=1, merged=1
Processing DMS assay UPI00000467CA:  74%|██▏| 1146/1555 [02:12<00:40, 10.10it/s]UPI00000467CA: DMS=1, merged=1
Processing DMS assay UPI0000EBB7D6:  74%|██▏| 1146/1555 [02:12<00:40, 10.10it/s]UPI0000EBB7D6: DMS=1, merged=1
Processing DMS assay UPI000016783D:  74%|██▏| 1148/1555 [02:12<00:40, 10.08it/s]UPI000016783D: DMS=1, merged=1
Processing DMS assay UPI00000437FE:  74%|██▏| 1148/1555 [02:12<00:40, 10.08it/s]UPI00000437FE: DMS=1, merged=1
Processing DMS assay UPI00001B07C3:  74%|██▏| 1150/1555 [02:12<00:40, 10.04it/s]                                    mutated_sequence         HMM
0  MCAARLAAAAAAQSVYAFSARPLAGGEPVSLGSLRGKVLLIENVAS...        -inf
1  MCAARLAAAAAQSVYAFSARPLAGGEPVSLGSLRGKVLLIENVASL...        -inf HMM mutated_sequence 1150
UPI00001B07C3: DMS=2, merged=2
Processing DMS assay UPI000013C3DC:  74%|██▏| 1150/1555 [02:12<00:40, 10.04it/s]UPI000013C3DC: DMS=1, merged=1
Processing DMS assay UPI0000359594:  74%|██▏| 1152/1555 [02:13<00:41,  9.77it/s]UPI0000359594: DMS=1, merged=1
Processing DMS assay UPI0000423DF4:  74%|██▏| 1152/1555 [02:13<00:41,  9.77it/s]UPI0000423DF4: DMS=1, merged=1
Processing DMS assay UPI000012ADC5:  74%|██▏| 1154/1555 [02:13<00:40,  9.84it/s]UPI000012ADC5: DMS=2, merged=2
Processing DMS assay UPI00006C181B:  74%|██▏| 1155/1555 [02:13<00:40,  9.81it/s]UPI00006C181B: DMS=1, merged=1
Processing DMS assay UPI000004A07B:  74%|██▏| 1155/1555 [02:13<00:40,  9.81it/s]UPI000004A07B: DMS=1, merged=1
Processing DMS assay UPI0000E5AFF9:  74%|██▏| 1157/1555 [02:13<00:40,  9.92it/s]UPI0000E5AFF9: DMS=1, merged=1
Processing DMS assay UPI000023281A:  74%|██▏| 1157/1555 [02:13<00:40,  9.92it/s]UPI000023281A: DMS=1, merged=1
Processing DMS assay UPI000014153E:  75%|██▏| 1159/1555 [02:13<00:39, 10.07it/s]UPI000014153E: DMS=1, merged=1
Processing DMS assay UPI000013CB8B:  75%|██▏| 1159/1555 [02:13<00:39, 10.07it/s]UPI000013CB8B: DMS=1, merged=1
Processing DMS assay UPI00004575C6:  75%|██▏| 1161/1555 [02:13<00:39, 10.07it/s]UPI00004575C6: DMS=1, merged=1
Processing DMS assay UPI00022F843B:  75%|██▏| 1161/1555 [02:14<00:39, 10.07it/s]UPI00022F843B: DMS=1, merged=1
Processing DMS assay UPI0000206B64:  75%|██▏| 1163/1555 [02:14<00:39, 10.01it/s]UPI0000206B64: DMS=1, merged=1
Processing DMS assay UPI0000E599FA:  75%|██▏| 1163/1555 [02:14<00:39, 10.01it/s]UPI0000E599FA: DMS=1, merged=1
Processing DMS assay UPI00015E00D0:  75%|██▏| 1165/1555 [02:14<00:38, 10.01it/s]UPI00015E00D0: DMS=1, merged=1
Processing DMS assay UPI0000EE0485:  75%|██▏| 1165/1555 [02:14<00:38, 10.01it/s]UPI0000EE0485: DMS=1, merged=1
Processing DMS assay UPI00004589BB:  75%|██▎| 1167/1555 [02:14<00:40,  9.66it/s]UPI00004589BB: DMS=1, merged=1
Processing DMS assay UPI0000130C80:  75%|██▎| 1168/1555 [02:14<00:39,  9.70it/s]UPI0000130C80: DMS=1, merged=1
Processing DMS assay UPI00001C1E1E:  75%|██▎| 1169/1555 [02:14<00:39,  9.72it/s]UPI00001C1E1E: DMS=5, merged=5
Processing DMS assay UPI000006FF4C:  75%|██▎| 1170/1555 [02:14<00:39,  9.67it/s]UPI000006FF4C: DMS=1, merged=1
Processing DMS assay UPI0000071B6E:  75%|██▎| 1171/1555 [02:14<00:39,  9.69it/s]UPI0000071B6E: DMS=1, merged=1
Processing DMS assay UPI000012ADEC:  75%|██▎| 1172/1555 [02:15<00:39,  9.71it/s]UPI000012ADEC: DMS=1, merged=1
Processing DMS assay UPI000013C70B:  75%|██▎| 1173/1555 [02:15<00:39,  9.71it/s]UPI000013C70B: DMS=1, merged=1
Processing DMS assay UPI0000131BD3:  75%|██▎| 1174/1555 [02:15<00:39,  9.75it/s]UPI0000131BD3: DMS=1, merged=1
Processing DMS assay UPI0000E5A38D:  75%|██▎| 1174/1555 [02:15<00:39,  9.75it/s]UPI0000E5A38D: DMS=1, merged=1
Processing DMS assay UPI00001AE868:  76%|██▎| 1176/1555 [02:15<00:38,  9.88it/s]UPI00001AE868: DMS=1, merged=1
Processing DMS assay UPI0000203C32:  76%|██▎| 1177/1555 [02:15<00:38,  9.89it/s]UPI0000203C32: DMS=1, merged=1
Processing DMS assay UPI000006F1B6:  76%|██▎| 1177/1555 [02:15<00:38,  9.89it/s]UPI000006F1B6: DMS=1, merged=1
Processing DMS assay UPI000004A077:  76%|██▎| 1179/1555 [02:15<00:37,  9.98it/s]UPI000004A077: DMS=1, merged=1
Processing DMS assay UPI000013E694:  76%|██▎| 1180/1555 [02:15<00:38,  9.86it/s]UPI000013E694: DMS=1, merged=1
Processing DMS assay UPI0000488BDC:  76%|██▎| 1181/1555 [02:15<00:37,  9.88it/s]UPI0000488BDC: DMS=1, merged=1
Processing DMS assay UPI0000071E24:  76%|██▎| 1182/1555 [02:16<00:37,  9.89it/s]UPI0000071E24: DMS=1, merged=1
Processing DMS assay UPI000059D33E:  76%|██▎| 1183/1555 [02:16<00:38,  9.79it/s]UPI000059D33E: DMS=1, merged=1
Processing DMS assay UPI000013D842:  76%|██▎| 1184/1555 [02:16<00:37,  9.80it/s]UPI000013D842: DMS=1, merged=1
Processing DMS assay UPI00001378FC:  76%|██▎| 1185/1555 [02:16<00:38,  9.70it/s]UPI00001378FC: DMS=1, merged=1
Processing DMS assay UPI0001838820:  76%|██▎| 1186/1555 [02:16<00:37,  9.73it/s]UPI0001838820: DMS=2, merged=2
Processing DMS assay UPI00001AFE92:  76%|██▎| 1187/1555 [02:16<00:38,  9.56it/s]UPI00001AFE92: DMS=1, merged=1
Processing DMS assay UPI000013C8B1:  76%|██▎| 1188/1555 [02:16<00:38,  9.58it/s]UPI000013C8B1: DMS=1, merged=1
Processing DMS assay UPI000004B1EC:  76%|██▎| 1189/1555 [02:16<00:37,  9.65it/s]UPI000004B1EC: DMS=1, merged=1
Processing DMS assay UPI00001D7FAE:  76%|██▎| 1189/1555 [02:16<00:37,  9.65it/s]UPI00001D7FAE: DMS=1, merged=1
Processing DMS assay UPI0000140198:  77%|██▎| 1191/1555 [02:16<00:37,  9.74it/s]UPI0000140198: DMS=1, merged=1
Processing DMS assay UPI0000135F5C:  77%|██▎| 1192/1555 [02:17<00:37,  9.68it/s]UPI0000135F5C: DMS=1, merged=1
Processing DMS assay UPI000000D824:  77%|██▎| 1193/1555 [02:17<00:37,  9.69it/s]UPI000000D824: DMS=1, merged=1
Processing DMS assay UPI0001F7848D:  77%|██▎| 1194/1555 [02:17<00:37,  9.73it/s]UPI0001F7848D: DMS=1, merged=1
Processing DMS assay UPI000004673A:  77%|██▎| 1194/1555 [02:17<00:37,  9.73it/s]UPI000004673A: DMS=1, merged=1
Processing DMS assay UPI00001DFBF3:  77%|██▎| 1196/1555 [02:17<00:35,  9.99it/s]UPI00001DFBF3: DMS=1, merged=1
Processing DMS assay UPI00001D68E9:  77%|██▎| 1196/1555 [02:17<00:35,  9.99it/s]UPI00001D68E9: DMS=1, merged=1
Processing DMS assay UPI00001AED69:  77%|██▎| 1198/1555 [02:17<00:35, 10.03it/s]UPI00001AED69: DMS=1, merged=1
Processing DMS assay UPI00004C3E05:  77%|██▎| 1198/1555 [02:17<00:35, 10.03it/s]UPI00004C3E05: DMS=1, merged=1
Processing DMS assay UPI000012ADD0:  77%|██▎| 1200/1555 [02:17<00:35, 10.07it/s]UPI000012ADD0: DMS=1, merged=1

Processing DMS assay UPI000012BB5B:  77%|██▎| 1200/1555 [02:17<00:35, 10.07it/s]UPI000012BB5B: DMS=1, merged=1
Processing DMS assay UPI000003032B:  77%|██▎| 1202/1555 [02:18<00:35, 10.02it/s]UPI000003032B: DMS=1, merged=1
Processing DMS assay UPI000004A951:  77%|██▎| 1202/1555 [02:18<00:35, 10.02it/s]UPI000004A951: DMS=1, merged=1
Processing DMS assay UPI0000D61567:  77%|██▎| 1204/1555 [02:18<00:35,  9.98it/s]UPI0000D61567: DMS=1, merged=1
Processing DMS assay UPI0000037B1F:  77%|██▎| 1205/1555 [02:18<00:35,  9.96it/s]UPI0000037B1F: DMS=1, merged=1
Processing DMS assay UPI00004565DA:  77%|██▎| 1205/1555 [02:18<00:35,  9.96it/s]UPI00004565DA: DMS=1, merged=1
Processing DMS assay UPI000013DD75:  78%|██▎| 1207/1555 [02:18<00:34, 10.03it/s]UPI000013DD75: DMS=1, merged=1
Processing DMS assay UPI00001C2000:  78%|██▎| 1207/1555 [02:18<00:34, 10.03it/s]UPI00001C2000: DMS=1, merged=1
Processing DMS assay UPI0001A5E4A3:  78%|██▎| 1209/1555 [02:18<00:34, 10.05it/s]UPI0001A5E4A3: DMS=1, merged=1
Processing DMS assay UPI00001AECDC:  78%|██▎| 1209/1555 [02:18<00:34, 10.05it/s]UPI00001AECDC: DMS=2, merged=2
Processing DMS assay UPI000002ADD2:  78%|██▎| 1211/1555 [02:18<00:34, 10.02it/s]UPI000002ADD2: DMS=3, merged=3
Processing DMS assay UPI0000041CE2:  78%|██▎| 1211/1555 [02:19<00:34, 10.02it/s]UPI0000041CE2: DMS=1, merged=1
Processing DMS assay UPI00001A9480:  78%|██▎| 1213/1555 [02:19<00:34,  9.85it/s]UPI00001A9480: DMS=1, merged=1
Processing DMS assay UPI00025A2EC3:  78%|██▎| 1214/1555 [02:19<00:34,  9.76it/s]UPI00025A2EC3: DMS=1, merged=1
Processing DMS assay UPI0001B79574:  78%|██▎| 1215/1555 [02:19<00:34,  9.75it/s]UPI0001B79574: DMS=1, merged=1
Processing DMS assay UPI000022A768:  78%|██▎| 1216/1555 [02:19<00:36,  9.35it/s]UPI000022A768: DMS=1, merged=1
Processing DMS assay UPI000046FD46:  78%|██▎| 1217/1555 [02:19<00:35,  9.40it/s]UPI000046FD46: DMS=1, merged=1
Processing DMS assay UPI0000126640:  78%|██▎| 1218/1555 [02:19<00:35,  9.50it/s]UPI0000126640: DMS=3, merged=3
Processing DMS assay UPI00000389E8:  78%|██▎| 1219/1555 [02:19<00:35,  9.44it/s]UPI00000389E8: DMS=1, merged=1
Processing DMS assay UPI000020E71F:  78%|██▎| 1220/1555 [02:19<00:35,  9.53it/s]UPI000020E71F: DMS=1, merged=1
Processing DMS assay UPI0000044645:  79%|██▎| 1221/1555 [02:20<00:34,  9.59it/s]UPI0000044645: DMS=1, merged=1
Processing DMS assay UPI0001AE67FB:  79%|██▎| 1221/1555 [02:20<00:34,  9.59it/s]UPI0001AE67FB: DMS=1, merged=1
Processing DMS assay UPI0000072AD5:  79%|██▎| 1223/1555 [02:20<00:34,  9.76it/s]UPI0000072AD5: DMS=1, merged=1
Processing DMS assay UPI0000246F54:  79%|██▎| 1224/1555 [02:20<00:34,  9.72it/s]UPI0000246F54: DMS=1, merged=1
Processing DMS assay UPI0000E03260:  79%|██▎| 1225/1555 [02:20<00:33,  9.72it/s]UPI0000E03260: DMS=1, merged=1
Processing DMS assay UPI0000424CC7:  79%|██▎| 1226/1555 [02:20<00:33,  9.68it/s]UPI0000424CC7: DMS=1, merged=1
Processing DMS assay UPI0000E5924D:  79%|██▎| 1227/1555 [02:20<00:33,  9.67it/s]UPI0000E5924D: DMS=1, merged=1
Processing DMS assay UPI0000231C71:  79%|██▎| 1228/1555 [02:20<00:33,  9.72it/s]UPI0000231C71: DMS=1, merged=1
Processing DMS assay UPI000012666A:  79%|██▎| 1229/1555 [02:20<00:33,  9.74it/s]UPI000012666A: DMS=1, merged=1
Processing DMS assay UPI000013E87D:  79%|██▎| 1230/1555 [02:20<00:33,  9.78it/s]UPI000013E87D: DMS=1, merged=1
Processing DMS assay UPI0000072AAB:  79%|██▎| 1231/1555 [02:21<00:32,  9.84it/s]UPI0000072AAB: DMS=1, merged=1
Processing DMS assay UPI0000205CB5:  79%|██▍| 1232/1555 [02:21<00:32,  9.87it/s]UPI0000205CB5: DMS=2, merged=2
Processing DMS assay UPI0000212786:  79%|██▍| 1233/1555 [02:21<00:33,  9.72it/s]UPI0000212786: DMS=5, merged=5
Processing DMS assay UPI00000421FD:  79%|██▍| 1234/1555 [02:21<00:34,  9.41it/s]UPI00000421FD: DMS=1, merged=1
Processing DMS assay UPI000013DDDC:  79%|██▍| 1235/1555 [02:21<00:33,  9.52it/s]UPI000013DDDC: DMS=1, merged=1
Processing DMS assay UPI0001662BAD:  79%|██▍| 1236/1555 [02:21<00:33,  9.49it/s]UPI0001662BAD: DMS=1, merged=1
Processing DMS assay UPI0000201E92:  80%|██▍| 1237/1555 [02:21<00:33,  9.44it/s]UPI0000201E92: DMS=1, merged=1
Processing DMS assay UPI00001BDAC0:  80%|██▍| 1237/1555 [02:21<00:33,  9.44it/s]UPI00001BDAC0: DMS=1, merged=1
Processing DMS assay UPI000012ADD6:  80%|██▍| 1239/1555 [02:21<00:32,  9.60it/s]UPI000012ADD6: DMS=3, merged=3
Processing DMS assay UPI000022AC91:  80%|██▍| 1240/1555 [02:22<00:33,  9.49it/s]UPI000022AC91: DMS=1, merged=1
Processing DMS assay UPI000006F1A1:  80%|██▍| 1241/1555 [02:22<00:32,  9.61it/s]UPI000006F1A1: DMS=1, merged=1
Processing DMS assay UPI00001376B5:  80%|██▍| 1242/1555 [02:22<00:32,  9.65it/s]UPI00001376B5: DMS=1, merged=1
Processing DMS assay UPI0000161FDC:  80%|██▍| 1243/1555 [02:22<00:32,  9.74it/s]UPI0000161FDC: DMS=1, merged=1
Processing DMS assay UPI0000140E62:  80%|██▍| 1244/1555 [02:22<00:31,  9.77it/s]UPI0000140E62: DMS=1, merged=1
Processing DMS assay UPI000013E44F:  80%|██▍| 1245/1555 [02:22<00:31,  9.71it/s]UPI000013E44F: DMS=1, merged=1
Processing DMS assay UPI0000209875:  80%|██▍| 1246/1555 [02:22<00:31,  9.70it/s]UPI0000209875: DMS=2, merged=2
Processing DMS assay UPI0000251D78:  80%|██▍| 1247/1555 [02:22<00:31,  9.75it/s]UPI0000251D78: DMS=1, merged=1
Processing DMS assay UPI000059D3CC:  80%|██▍| 1248/1555 [02:22<00:31,  9.78it/s]UPI000059D3CC: DMS=1, merged=1
Processing DMS assay UPI0001929538:  80%|██▍| 1249/1555 [02:22<00:31,  9.78it/s]UPI0001929538: DMS=1, merged=1
Processing DMS assay UPI000013E413:  80%|██▍| 1250/1555 [02:23<00:31,  9.82it/s]UPI000013E413: DMS=1, merged=1
Processing DMS assay UPI000013D308:  80%|██▍| 1251/1555 [02:23<00:30,  9.82it/s]UPI000013D308: DMS=2, merged=2
Processing DMS assay UPI00001AF305:  81%|██▍| 1252/1555 [02:23<00:31,  9.70it/s]UPI00001AF305: DMS=1, merged=1
Processing DMS assay UPI0001DD21C7:  81%|██▍| 1253/1555 [02:23<00:30,  9.76it/s]UPI0001DD21C7: DMS=1, merged=1
Processing DMS assay UPI000004A10E:  81%|██▍| 1253/1555 [02:23<00:30,  9.76it/s]UPI000004A10E: DMS=1, merged=1
Processing DMS assay UPI000007443D:  81%|██▍| 1255/1555 [02:23<00:30,  9.96it/s]UPI000007443D: DMS=2, merged=2
Processing DMS assay UPI0000367134:  81%|██▍| 1256/1555 [02:23<00:30,  9.96it/s]UPI0000367134: DMS=1, merged=1
Processing DMS assay UPI0000048EB8:  81%|██▍| 1256/1555 [02:23<00:30,  9.96it/s]UPI0000048EB8: DMS=1, merged=1
Processing DMS assay UPI00015E04B4:  81%|██▍| 1258/1555 [02:23<00:29,  9.99it/s]UPI00015E04B4: DMS=1, merged=1
Processing DMS assay UPI00015E06EA:  81%|██▍| 1259/1555 [02:23<00:29,  9.98it/s]UPI00015E06EA: DMS=3, merged=3
Processing DMS assay UPI0002065974:  81%|██▍| 1260/1555 [02:24<00:29,  9.89it/s]UPI0002065974: DMS=2, merged=2
Processing DMS assay UPI0000073AA5:  81%|██▍| 1261/1555 [02:24<00:29,  9.83it/s]UPI0000073AA5: DMS=1, merged=1
Processing DMS assay UPI00001AFDEB:  81%|██▍| 1262/1555 [02:24<00:29,  9.80it/s]UPI00001AFDEB: DMS=1, merged=1
Processing DMS assay UPI0000073F52:  81%|██▍| 1263/1555 [02:24<00:29,  9.85it/s]UPI0000073F52: DMS=1, merged=1
Processing DMS assay UPI00002326B6:  81%|██▍| 1263/1555 [02:24<00:29,  9.85it/s]UPI00002326B6: DMS=1, merged=1
Processing DMS assay UPI0000129881:  81%|██▍| 1265/1555 [02:24<00:29,  9.95it/s]UPI0000129881: DMS=1, merged=1
Processing DMS assay UPI000007385F:  81%|██▍| 1266/1555 [02:24<00:29,  9.88it/s]UPI000007385F: DMS=1, merged=1
Processing DMS assay UPI0001610E83:  81%|██▍| 1267/1555 [02:24<00:29,  9.69it/s]UPI0001610E83: DMS=1, merged=1
Processing DMS assay UPI000006F554:  82%|██▍| 1268/1555 [02:24<00:29,  9.65it/s]UPI000006F554: DMS=1, merged=1
Processing DMS assay UPI00015E05B9:  82%|██▍| 1269/1555 [02:24<00:29,  9.69it/s]UPI00015E05B9: DMS=1, merged=1
Processing DMS assay UPI000004F638:  82%|██▍| 1269/1555 [02:25<00:29,  9.69it/s]UPI000004F638: DMS=1, merged=1
Processing DMS assay UPI000006FECD:  82%|██▍| 1271/1555 [02:25<00:29,  9.75it/s]UPI000006FECD: DMS=1, merged=1
Processing DMS assay UPI00025A2F44:  82%|██▍| 1272/1555 [02:25<00:28,  9.76it/s]UPI00025A2F44: DMS=1, merged=1
Processing DMS assay UPI000013D104:  82%|██▍| 1273/1555 [02:25<00:28,  9.73it/s]UPI000013D104: DMS=1, merged=1
Processing DMS assay UPI000066DA6A:  82%|██▍| 1274/1555 [02:25<00:28,  9.74it/s]UPI000066DA6A: DMS=1, merged=1

Processing DMS assay UPI00004C8020:  82%|██▍| 1275/1555 [02:25<00:28,  9.74it/s]UPI00004C8020: DMS=2, merged=2
Processing DMS assay UPI0000072C2E:  82%|██▍| 1276/1555 [02:25<00:28,  9.74it/s]UPI0000072C2E: DMS=1, merged=1
Processing DMS assay UPI0000423C4C:  82%|██▍| 1277/1555 [02:25<00:28,  9.77it/s]UPI0000423C4C: DMS=1, merged=1
Processing DMS assay UPI00001C1E94:  82%|██▍| 1278/1555 [02:25<00:28,  9.75it/s]UPI00001C1E94: DMS=1, merged=1
Processing DMS assay UPI00001B647D:  82%|██▍| 1278/1555 [02:25<00:28,  9.75it/s]UPI00001B647D: DMS=1, merged=1
Processing DMS assay UPI0000073CB8:  82%|██▍| 1280/1555 [02:26<00:27,  9.91it/s]UPI0000073CB8: DMS=1, merged=1
Processing DMS assay UPI000013CDC7:  82%|██▍| 1281/1555 [02:26<00:27,  9.83it/s]UPI000013CDC7: DMS=2, merged=2
Processing DMS assay UPI0001A48FC8:  82%|██▍| 1282/1555 [02:26<00:27,  9.85it/s]UPI0001A48FC8: DMS=1, merged=1
Processing DMS assay UPI000195170D:  83%|██▍| 1283/1555 [02:26<00:28,  9.50it/s]UPI000195170D: DMS=1, merged=1
Processing DMS assay UPI0000141917:  83%|██▍| 1283/1555 [02:26<00:28,  9.50it/s]UPI0000141917: DMS=2, merged=2
Processing DMS assay UPI000013DFEA:  83%|██▍| 1285/1555 [02:26<00:27,  9.76it/s]UPI000013DFEA: DMS=1, merged=1
Processing DMS assay UPI00004700E1:  83%|██▍| 1285/1555 [02:26<00:27,  9.76it/s]UPI00004700E1: DMS=1, merged=1
Processing DMS assay UPI000050ED33:  83%|██▍| 1287/1555 [02:26<00:27,  9.88it/s]UPI000050ED33: DMS=1, merged=1
Processing DMS assay UPI000004E7FC:  83%|██▍| 1288/1555 [02:26<00:27,  9.88it/s]UPI000004E7FC: DMS=1, merged=1
Processing DMS assay UPI000204A77C:  83%|██▍| 1288/1555 [02:26<00:27,  9.88it/s]UPI000204A77C: DMS=1, merged=1
Processing DMS assay UPI0001662BC1:  83%|██▍| 1290/1555 [02:27<00:26, 10.02it/s]UPI0001662BC1: DMS=1, merged=1
Processing DMS assay UPI0000167B08:  83%|██▍| 1291/1555 [02:27<00:26, 10.01it/s]UPI0000167B08: DMS=1, merged=1
Processing DMS assay UPI0001EE4B77:  83%|██▍| 1291/1555 [02:27<00:26, 10.01it/s]UPI0001EE4B77: DMS=1, merged=1
Processing DMS assay UPI000006FC41:  83%|██▍| 1293/1555 [02:27<00:26, 10.06it/s]UPI000006FC41: DMS=1, merged=1
Processing DMS assay UPI0000070AF2:  83%|██▍| 1293/1555 [02:27<00:26, 10.06it/s]UPI0000070AF2: DMS=1, merged=1
Processing DMS assay UPI000034ECE0:  83%|██▍| 1295/1555 [02:27<00:25, 10.11it/s]UPI000034ECE0: DMS=3, merged=3
Processing DMS assay UPI000058E2EA:  83%|██▍| 1295/1555 [02:27<00:25, 10.11it/s]UPI000058E2EA: DMS=2, merged=2
Processing DMS assay UPI00004C2CAA:  83%|██▌| 1297/1555 [02:27<00:25,  9.94it/s]UPI00004C2CAA: DMS=1, merged=1
Processing DMS assay UPI0000072F87:  83%|██▌| 1297/1555 [02:27<00:25,  9.94it/s]UPI0000072F87: DMS=1, merged=1
Processing DMS assay UPI000161137B:  84%|██▌| 1299/1555 [02:27<00:25, 10.02it/s]UPI000161137B: DMS=1, merged=1
Processing DMS assay UPI00001294AC:  84%|██▌| 1299/1555 [02:28<00:25, 10.02it/s]UPI00001294AC: DMS=1, merged=1
Processing DMS assay UPI00001B6532:  84%|██▌| 1301/1555 [02:28<00:25, 10.10it/s]UPI00001B6532: DMS=1, merged=1
Processing DMS assay UPI0001881663:  84%|██▌| 1301/1555 [02:28<00:25, 10.10it/s]UPI0001881663: DMS=1, merged=1
Processing DMS assay UPI000020187D:  84%|██▌| 1303/1555 [02:28<00:25, 10.05it/s]UPI000020187D: DMS=1, merged=1
Processing DMS assay UPI000006D077:  84%|██▌| 1303/1555 [02:28<00:25, 10.05it/s]UPI000006D077: DMS=1, merged=1
Processing DMS assay UPI000013DC6C:  84%|██▌| 1305/1555 [02:28<00:24, 10.06it/s]UPI000013DC6C: DMS=3, merged=3
Processing DMS assay UPI000013C755:  84%|██▌| 1305/1555 [02:28<00:24, 10.06it/s]UPI000013C755: DMS=1, merged=1
Processing DMS assay UPI0000DAC777:  84%|██▌| 1307/1555 [02:28<00:24, 10.11it/s]UPI0000DAC777: DMS=2, merged=2
Processing DMS assay UPI000042467C:  84%|██▌| 1307/1555 [02:28<00:24, 10.11it/s]UPI000042467C: DMS=3, merged=3
Processing DMS assay UPI00006AB830:  84%|██▌| 1309/1555 [02:28<00:24, 10.10it/s]UPI00006AB830: DMS=1, merged=1
Processing DMS assay UPI00002077A2:  84%|██▌| 1309/1555 [02:29<00:24, 10.10it/s]UPI00002077A2: DMS=1, merged=1
Processing DMS assay UPI0001AE641D:  84%|██▌| 1311/1555 [02:29<00:24, 10.16it/s]UPI0001AE641D: DMS=1, merged=1
Processing DMS assay UPI0000229786:  84%|██▌| 1311/1555 [02:29<00:24, 10.16it/s]UPI0000229786: DMS=1, merged=1
Processing DMS assay UPI00018848F1:  84%|██▌| 1313/1555 [02:29<00:23, 10.23it/s]UPI00018848F1: DMS=1, merged=1
Processing DMS assay UPI00001AEE5A:  84%|██▌| 1313/1555 [02:29<00:23, 10.23it/s]UPI00001AEE5A: DMS=1, merged=1
Processing DMS assay UPI00017A8741:  85%|██▌| 1315/1555 [02:29<00:23, 10.25it/s]UPI00017A8741: DMS=1, merged=1
Processing DMS assay UPI0000141054:  85%|██▌| 1315/1555 [02:29<00:23, 10.25it/s]UPI0000141054: DMS=1, merged=1
Processing DMS assay UPI000013D1EC:  85%|██▌| 1317/1555 [02:29<00:23, 10.23it/s]UPI000013D1EC: DMS=1, merged=1
Processing DMS assay UPI0000169571:  85%|██▌| 1317/1555 [02:29<00:23, 10.23it/s]UPI0000169571: DMS=1, merged=1
Processing DMS assay UPI0002065925:  85%|██▌| 1319/1555 [02:29<00:23, 10.24it/s]UPI0002065925: DMS=2, merged=2
Processing DMS assay UPI000067CB88:  85%|██▌| 1319/1555 [02:30<00:23, 10.24it/s]UPI000067CB88: DMS=1, merged=1
Processing DMS assay UPI000006F773:  85%|██▌| 1321/1555 [02:30<00:22, 10.24it/s]UPI000006F773: DMS=1, merged=1
Processing DMS assay UPI0000251DD8:  85%|██▌| 1321/1555 [02:30<00:22, 10.24it/s]UPI0000251DD8: DMS=2, merged=2
Processing DMS assay UPI0000470B60:  85%|██▌| 1323/1555 [02:30<00:22, 10.22it/s]UPI0000470B60: DMS=1, merged=1
Processing DMS assay UPI0000073246:  85%|██▌| 1323/1555 [02:30<00:22, 10.22it/s]UPI0000073246: DMS=2, merged=2
Processing DMS assay UPI000013E18E:  85%|██▌| 1325/1555 [02:30<00:22, 10.15it/s]UPI000013E18E: DMS=1, merged=1
Processing DMS assay UPI00001C1F20:  85%|██▌| 1325/1555 [02:30<00:22, 10.15it/s]UPI00001C1F20: DMS=1, merged=1
Processing DMS assay UPI0000185F04:  85%|██▌| 1327/1555 [02:30<00:22, 10.19it/s]UPI0000185F04: DMS=1, merged=1
Processing DMS assay UPI000004A2BE:  85%|██▌| 1327/1555 [02:30<00:22, 10.19it/s]UPI000004A2BE: DMS=1, merged=1
Processing DMS assay UPI0000127442:  85%|██▌| 1329/1555 [02:30<00:22, 10.22it/s]UPI0000127442: DMS=1, merged=1
Processing DMS assay UPI000013CDEE:  85%|██▌| 1329/1555 [02:31<00:22, 10.22it/s]UPI000013CDEE: DMS=1, merged=1
Processing DMS assay UPI00001D7B21:  86%|██▌| 1331/1555 [02:31<00:22, 10.12it/s]UPI00001D7B21: DMS=1, merged=1
Processing DMS assay UPI000013F27D:  86%|██▌| 1331/1555 [02:31<00:22, 10.12it/s]UPI000013F27D: DMS=1, merged=1
Processing DMS assay UPI0000037B54:  86%|██▌| 1333/1555 [02:31<00:21, 10.12it/s]UPI0000037B54: DMS=1, merged=1
Processing DMS assay UPI0000E0A787:  86%|██▌| 1333/1555 [02:31<00:21, 10.12it/s]UPI0000E0A787: DMS=1, merged=1
Processing DMS assay UPI00001C1FDF:  86%|██▌| 1335/1555 [02:31<00:21, 10.09it/s]UPI00001C1FDF: DMS=1, merged=1
Processing DMS assay UPI00002004B5:  86%|██▌| 1335/1555 [02:31<00:21, 10.09it/s]UPI00002004B5: DMS=1, merged=1
Processing DMS assay UPI0000041DD3:  86%|██▌| 1337/1555 [02:31<00:21, 10.16it/s]UPI0000041DD3: DMS=1, merged=1
Processing DMS assay UPI0000073ADE:  86%|██▌| 1337/1555 [02:31<00:21, 10.16it/s]UPI0000073ADE: DMS=1, merged=1
Processing DMS assay UPI000013DE11:  86%|██▌| 1339/1555 [02:31<00:21, 10.16it/s]UPI000013DE11: DMS=1, merged=1
Processing DMS assay UPI00015E09B8:  86%|██▌| 1339/1555 [02:32<00:21, 10.16it/s]UPI00015E09B8: DMS=1, merged=1
Processing DMS assay UPI0000049802:  86%|██▌| 1341/1555 [02:32<00:20, 10.22it/s]UPI0000049802: DMS=1, merged=1
Processing DMS assay UPI000013DA0D:  86%|██▌| 1341/1555 [02:32<00:20, 10.22it/s]UPI000013DA0D: DMS=1, merged=1
Processing DMS assay UPI0000374562:  86%|██▌| 1343/1555 [02:32<00:20, 10.15it/s]UPI0000374562: DMS=1, merged=1
Processing DMS assay UPI000013CCD8:  86%|██▌| 1343/1555 [02:32<00:20, 10.15it/s]UPI000013CCD8: DMS=1, merged=1
Processing DMS assay UPI0000073D30:  86%|██▌| 1345/1555 [02:32<00:20, 10.10it/s]UPI0000073D30: DMS=1, merged=1
Processing DMS assay UPI000015F97E:  86%|██▌| 1345/1555 [02:32<00:20, 10.10it/s]UPI000015F97E: DMS=1, merged=1
Processing DMS assay UPI00001D818D:  87%|██▌| 1347/1555 [02:32<00:20, 10.13it/s]UPI00001D818D: DMS=2, merged=2
Processing DMS assay UPI00001FEBF9:  87%|██▌| 1347/1555 [02:32<00:20, 10.13it/s]UPI00001FEBF9: DMS=1, merged=1

Processing DMS assay UPI0000073E41:  87%|██▌| 1349/1555 [02:32<00:20, 10.18it/s]UPI0000073E41: DMS=1, merged=1
Processing DMS assay UPI0000246F73:  87%|██▌| 1349/1555 [02:33<00:20, 10.18it/s]UPI0000246F73: DMS=1, merged=1
Processing DMS assay UPI0001642876:  87%|██▌| 1351/1555 [02:33<00:20, 10.20it/s]UPI0001642876: DMS=1, merged=1
Processing DMS assay UPI00001D771D:  87%|██▌| 1351/1555 [02:33<00:20, 10.20it/s]UPI00001D771D: DMS=1, merged=1
Processing DMS assay UPI000013E4EC:  87%|██▌| 1353/1555 [02:33<00:19, 10.19it/s]UPI000013E4EC: DMS=1, merged=1
Processing DMS assay UPI00001C1FA8:  87%|██▌| 1353/1555 [02:33<00:19, 10.19it/s]UPI00001C1FA8: DMS=1, merged=1
Processing DMS assay UPI0000458A54:  87%|██▌| 1355/1555 [02:33<00:19, 10.18it/s]UPI0000458A54: DMS=1, merged=1
Processing DMS assay UPI000066D9E3:  87%|██▌| 1355/1555 [02:33<00:19, 10.18it/s]UPI000066D9E3: DMS=1, merged=1
Processing DMS assay UPI0000126665:  87%|██▌| 1357/1555 [02:33<00:19, 10.19it/s]UPI0000126665: DMS=1, merged=1
Processing DMS assay UPI00000015B6:  87%|██▌| 1357/1555 [02:33<00:19, 10.19it/s]UPI00000015B6: DMS=1, merged=1
Processing DMS assay UPI0000070598:  87%|██▌| 1359/1555 [02:33<00:19, 10.16it/s]UPI0000070598: DMS=1, merged=1
Processing DMS assay UPI00003FEC88:  87%|██▌| 1359/1555 [02:33<00:19, 10.16it/s]UPI00003FEC88: DMS=1, merged=1
Processing DMS assay UPI0001CE93AE:  88%|██▋| 1361/1555 [02:34<00:19, 10.14it/s]UPI0001CE93AE: DMS=1, merged=1
Processing DMS assay UPI00004CEC5B:  88%|██▋| 1361/1555 [02:34<00:19, 10.14it/s]UPI00004CEC5B: DMS=1, merged=1
Processing DMS assay UPI000007315E:  88%|██▋| 1363/1555 [02:34<00:19,  9.98it/s]UPI000007315E: DMS=1, merged=1
Processing DMS assay UPI0000E0BF7B:  88%|██▋| 1364/1555 [02:34<00:19,  9.62it/s]UPI0000E0BF7B: DMS=1, merged=1
Processing DMS assay UPI00001F9669:  88%|██▋| 1365/1555 [02:34<00:21,  8.89it/s]UPI00001F9669: DMS=1, merged=1
Processing DMS assay UPI000004FDF5:  88%|██▋| 1366/1555 [02:34<00:21,  8.94it/s]UPI000004FDF5: DMS=2, merged=2
Processing DMS assay UPI000000CC09:  88%|██▋| 1367/1555 [02:34<00:20,  9.14it/s]UPI000000CC09: DMS=1, merged=1
Processing DMS assay UPI000022D996:  88%|██▋| 1368/1555 [02:34<00:20,  9.33it/s]UPI000022D996: DMS=1, merged=1
Processing DMS assay UPI0000231C2D:  88%|██▋| 1369/1555 [02:34<00:19,  9.47it/s]UPI0000231C2D: DMS=1, merged=1
Processing DMS assay UPI000015F240:  88%|██▋| 1370/1555 [02:35<00:19,  9.59it/s]UPI000015F240: DMS=1, merged=1
Processing DMS assay UPI00021CF3BF:  88%|██▋| 1371/1555 [02:35<00:19,  9.63it/s]UPI00021CF3BF: DMS=1, merged=1
Processing DMS assay UPI000011D62A:  88%|██▋| 1371/1555 [02:35<00:19,  9.63it/s]UPI000011D62A: DMS=1, merged=1
Processing DMS assay UPI000013E507:  88%|██▋| 1373/1555 [02:35<00:18,  9.80it/s]UPI000013E507: DMS=1, merged=1
Processing DMS assay UPI000013DCDA:  88%|██▋| 1374/1555 [02:35<00:18,  9.80it/s]UPI000013DCDA: DMS=1, merged=1
Processing DMS assay UPI0001881A85:  88%|██▋| 1375/1555 [02:35<00:18,  9.76it/s]UPI0001881A85: DMS=1, merged=1
Processing DMS assay UPI0001AE62FE:  88%|██▋| 1376/1555 [02:35<00:18,  9.78it/s]UPI0001AE62FE: DMS=1, merged=1
Processing DMS assay UPI0000418EA1:  88%|██▋| 1376/1555 [02:35<00:18,  9.78it/s]UPI0000418EA1: DMS=1, merged=1
Processing DMS assay UPI00001D9756:  89%|██▋| 1378/1555 [02:35<00:17,  9.86it/s]UPI00001D9756: DMS=1, merged=1
Processing DMS assay UPI000013E280:  89%|██▋| 1378/1555 [02:35<00:17,  9.86it/s]UPI000013E280: DMS=1, merged=1
Processing DMS assay UPI000016864A:  89%|██▋| 1380/1555 [02:36<00:17,  9.92it/s]UPI000016864A: DMS=1, merged=1
Processing DMS assay UPI00001AE786:  89%|██▋| 1381/1555 [02:36<00:17,  9.93it/s]UPI00001AE786: DMS=1, merged=1
Processing DMS assay UPI000166C19F:  89%|██▋| 1382/1555 [02:36<00:17,  9.87it/s]UPI000166C19F: DMS=1, merged=1
Processing DMS assay UPI000022BFB0:  89%|██▋| 1383/1555 [02:36<00:17,  9.87it/s]UPI000022BFB0: DMS=1, merged=1
Processing DMS assay UPI0000413F35:  89%|██▋| 1383/1555 [02:36<00:17,  9.87it/s]UPI0000413F35: DMS=1, merged=1
Processing DMS assay UPI000013CFAC:  89%|██▋| 1385/1555 [02:36<00:17,  9.75it/s]UPI000013CFAC: DMS=1, merged=1
Processing DMS assay UPI0000205DDE:  89%|██▋| 1386/1555 [02:36<00:17,  9.81it/s]UPI0000205DDE: DMS=1, merged=1
Processing DMS assay UPI0000046C44:  89%|██▋| 1387/1555 [02:36<00:17,  9.83it/s]UPI0000046C44: DMS=1, merged=1
Processing DMS assay UPI0000037465:  89%|██▋| 1387/1555 [02:36<00:17,  9.83it/s]UPI0000037465: DMS=1, merged=1
Processing DMS assay UPI0000130507:  89%|██▋| 1389/1555 [02:37<00:16,  9.94it/s]UPI0000130507: DMS=1, merged=1
Processing DMS assay UPI000013E60F:  89%|██▋| 1390/1555 [02:37<00:16,  9.95it/s]UPI000013E60F: DMS=1, merged=1
Processing DMS assay UPI0000041BDE:  89%|██▋| 1391/1555 [02:37<00:16,  9.90it/s]UPI0000041BDE: DMS=1, merged=1
Processing DMS assay UPI000006EEED:  89%|██▋| 1391/1555 [02:37<00:16,  9.90it/s]UPI000006EEED: DMS=1, merged=1
Processing DMS assay UPI0000EADF0B:  90%|██▋| 1393/1555 [02:37<00:16,  9.91it/s]UPI0000EADF0B: DMS=1, merged=1
Processing DMS assay UPI0000D820CC:  90%|██▋| 1394/1555 [02:37<00:16,  9.71it/s]UPI0000D820CC: DMS=1, merged=1
Processing DMS assay UPI000013CE13:  90%|██▋| 1394/1555 [02:37<00:16,  9.71it/s]UPI000013CE13: DMS=1, merged=1
Processing DMS assay UPI0000074578:  90%|██▋| 1396/1555 [02:37<00:16,  9.78it/s]UPI0000074578: DMS=1, merged=1
Processing DMS assay UPI000005104D:  90%|██▋| 1397/1555 [02:37<00:16,  9.54it/s]UPI000005104D: DMS=1, merged=1
Processing DMS assay UPI00001C2011:  90%|██▋| 1398/1555 [02:37<00:16,  9.51it/s]UPI00001C2011: DMS=1, merged=1
Processing DMS assay UPI000198C8A7:  90%|██▋| 1399/1555 [02:38<00:16,  9.53it/s]UPI000198C8A7: DMS=1, merged=1
Processing DMS assay UPI0002065B81:  90%|██▋| 1400/1555 [02:38<00:16,  9.58it/s]UPI0002065B81: DMS=1, merged=1
Processing DMS assay UPI0001AE795F:  90%|██▋| 1401/1555 [02:38<00:16,  9.56it/s]UPI0001AE795F: DMS=1, merged=1
Processing DMS assay UPI000013811E:  90%|██▋| 1401/1555 [02:38<00:16,  9.56it/s]UPI000013811E: DMS=1, merged=1
Processing DMS assay UPI000006D7C1:  90%|██▋| 1403/1555 [02:38<00:15,  9.73it/s]UPI000006D7C1: DMS=2, merged=2
Processing DMS assay UPI000013EFF9:  90%|██▋| 1404/1555 [02:38<00:15,  9.69it/s]UPI000013EFF9: DMS=1, merged=1
Processing DMS assay UPI000013D82E:  90%|██▋| 1405/1555 [02:38<00:15,  9.76it/s]UPI000013D82E: DMS=2, merged=2
Processing DMS assay UPI00004EC29C:  90%|██▋| 1406/1555 [02:38<00:15,  9.79it/s]UPI00004EC29C: DMS=1, merged=1
Processing DMS assay UPI000051AE2E:  90%|██▋| 1407/1555 [02:38<00:15,  9.79it/s]UPI000051AE2E: DMS=1, merged=1
Processing DMS assay UPI000013D704:  91%|██▋| 1408/1555 [02:38<00:14,  9.81it/s]UPI000013D704: DMS=1, merged=1
Processing DMS assay UPI000016ABE3:  91%|██▋| 1408/1555 [02:39<00:14,  9.81it/s]UPI000016ABE3: DMS=1, merged=1
Processing DMS assay UPI000019B3C1:  91%|██▋| 1410/1555 [02:39<00:14,  9.89it/s]UPI000019B3C1: DMS=1, merged=1
Processing DMS assay UPI000013C57B:  91%|██▋| 1410/1555 [02:39<00:14,  9.89it/s]UPI000013C57B: DMS=1, merged=1
Processing DMS assay UPI0000141A8E:  91%|██▋| 1412/1555 [02:39<00:14,  9.98it/s]UPI0000141A8E: DMS=3, merged=3
Processing DMS assay UPI000020E56F:  91%|██▋| 1413/1555 [02:39<00:14,  9.92it/s]UPI000020E56F: DMS=1, merged=1
Processing DMS assay UPI00001AADF3:  91%|██▋| 1414/1555 [02:39<00:14,  9.64it/s]UPI00001AADF3: DMS=1, merged=1
Processing DMS assay UPI0000071679:  91%|██▋| 1414/1555 [02:39<00:14,  9.64it/s]UPI0000071679: DMS=1, merged=1
Processing DMS assay UPI0000126A2D:  91%|██▋| 1416/1555 [02:39<00:14,  9.86it/s]UPI0000126A2D: DMS=1, merged=1
Processing DMS assay UPI0000EE4A53:  91%|██▋| 1417/1555 [02:39<00:13,  9.87it/s]UPI0000EE4A53: DMS=3, merged=3
Processing DMS assay UPI00001A96B8:  91%|██▋| 1418/1555 [02:39<00:14,  9.76it/s]UPI00001A96B8: DMS=1, merged=1
Processing DMS assay UPI0000161631:  91%|██▋| 1418/1555 [02:40<00:14,  9.76it/s]UPI0000161631: DMS=1, merged=1
Processing DMS assay UPI00015E0572:  91%|██▋| 1420/1555 [02:40<00:13,  9.83it/s]UPI00015E0572: DMS=1, merged=1
Processing DMS assay UPI0002065466:  91%|██▋| 1420/1555 [02:40<00:13,  9.83it/s]UPI0002065466: DMS=1, merged=1
Processing DMS assay UPI0000167B2F:  91%|██▋| 1422/1555 [02:40<00:13,  9.91it/s]UPI0000167B2F: DMS=1, merged=1

Processing DMS assay UPI0000456EEB:  91%|██▋| 1422/1555 [02:40<00:13,  9.91it/s]UPI0000456EEB: DMS=1, merged=1
Processing DMS assay UPI00006E2246:  92%|██▋| 1424/1555 [02:40<00:13,  9.97it/s]UPI00006E2246: DMS=1, merged=1
Processing DMS assay UPI000013C98D:  92%|██▋| 1424/1555 [02:40<00:13,  9.97it/s]UPI000013C98D: DMS=1, merged=1
Processing DMS assay UPI000015153B:  92%|██▊| 1426/1555 [02:40<00:12,  9.97it/s]UPI000015153B: DMS=1, merged=1
Processing DMS assay UPI0000070FB1:  92%|██▊| 1426/1555 [02:40<00:12,  9.97it/s]UPI0000070FB1: DMS=1, merged=1
Processing DMS assay UPI00001293CB:  92%|██▊| 1428/1555 [02:40<00:12, 10.07it/s]UPI00001293CB: DMS=1, merged=1
Processing DMS assay UPI00001F9E3B:  92%|██▊| 1428/1555 [02:41<00:12, 10.07it/s]UPI00001F9E3B: DMS=2, merged=2
Processing DMS assay UPI0000208B29:  92%|██▊| 1430/1555 [02:41<00:12, 10.09it/s]UPI0000208B29: DMS=1, merged=1
Processing DMS assay UPI00001B4B18:  92%|██▊| 1430/1555 [02:41<00:12, 10.09it/s]UPI00001B4B18: DMS=1, merged=1
Processing DMS assay UPI00001273CC:  92%|██▊| 1432/1555 [02:41<00:12, 10.09it/s]UPI00001273CC: DMS=1, merged=1
Processing DMS assay UPI0000470BBD:  92%|██▊| 1432/1555 [02:41<00:12, 10.09it/s]UPI0000470BBD: DMS=1, merged=1
Processing DMS assay UPI00000718AE:  92%|██▊| 1434/1555 [02:41<00:11, 10.13it/s]UPI00000718AE: DMS=1, merged=1
Processing DMS assay UPI000013D567:  92%|██▊| 1434/1555 [02:41<00:11, 10.13it/s]UPI000013D567: DMS=2, merged=2
Processing DMS assay UPI0000140E19:  92%|██▊| 1436/1555 [02:41<00:11, 10.05it/s]UPI0000140E19: DMS=1, merged=1
Processing DMS assay UPI0000141657:  92%|██▊| 1436/1555 [02:41<00:11, 10.05it/s]UPI0000141657: DMS=1, merged=1
Processing DMS assay UPI000013D783:  92%|██▊| 1438/1555 [02:41<00:11, 10.10it/s]UPI000013D783: DMS=1, merged=1
Processing DMS assay UPI000013EF6E:  92%|██▊| 1438/1555 [02:42<00:11, 10.10it/s]UPI000013EF6E: DMS=1, merged=1
Processing DMS assay UPI00001AEBA4:  93%|██▊| 1440/1555 [02:42<00:11, 10.15it/s]UPI00001AEBA4: DMS=1, merged=1
Processing DMS assay UPI00000711D1:  93%|██▊| 1440/1555 [02:42<00:11, 10.15it/s]UPI00000711D1: DMS=2, merged=2
Processing DMS assay UPI00001313D9:  93%|██▊| 1442/1555 [02:42<00:11, 10.19it/s]UPI00001313D9: DMS=1, merged=1
Processing DMS assay UPI0000D6DA73:  93%|██▊| 1442/1555 [02:42<00:11, 10.19it/s]UPI0000D6DA73: DMS=1, merged=1
Processing DMS assay UPI00015E040A:  93%|██▊| 1444/1555 [02:42<00:10, 10.26it/s]UPI00015E040A: DMS=1, merged=1
Processing DMS assay UPI000065CA24:  93%|██▊| 1444/1555 [02:42<00:10, 10.26it/s]UPI000065CA24: DMS=2, merged=2
Processing DMS assay UPI000006F76F:  93%|██▊| 1446/1555 [02:42<00:10, 10.11it/s]UPI000006F76F: DMS=1, merged=1
Processing DMS assay UPI00001BE8EA:  93%|██▊| 1446/1555 [02:42<00:10, 10.11it/s]UPI00001BE8EA: DMS=1, merged=1
Processing DMS assay UPI00001313B6:  93%|██▊| 1448/1555 [02:42<00:10, 10.16it/s]UPI00001313B6: DMS=1, merged=1
Processing DMS assay UPI000013D92B:  93%|██▊| 1448/1555 [02:43<00:10, 10.16it/s]UPI000013D92B: DMS=1, merged=1
Processing DMS assay UPI000004B634:  93%|██▊| 1450/1555 [02:43<00:10, 10.10it/s]UPI000004B634: DMS=1, merged=1
Processing DMS assay UPI00004574E1:  93%|██▊| 1450/1555 [02:43<00:10, 10.10it/s]UPI00004574E1: DMS=3, merged=3
Processing DMS assay UPI00001B4B16:  93%|██▊| 1452/1555 [02:43<00:10,  9.81it/s]UPI00001B4B16: DMS=1, merged=1
Processing DMS assay UPI000013D915:  93%|██▊| 1452/1555 [02:43<00:10,  9.81it/s]UPI000013D915: DMS=1, merged=1
Processing DMS assay UPI00001B0366:  94%|██▊| 1454/1555 [02:43<00:10,  9.93it/s]UPI00001B0366: DMS=3, merged=3
Processing DMS assay UPI00015B3B88:  94%|██▊| 1454/1555 [02:43<00:10,  9.93it/s]UPI00015B3B88: DMS=1, merged=1
Processing DMS assay UPI000004CB0B:  94%|██▊| 1456/1555 [02:43<00:09, 10.01it/s]UPI000004CB0B: DMS=1, merged=1
Processing DMS assay UPI00001A95DE:  94%|██▊| 1456/1555 [02:43<00:09, 10.01it/s]UPI00001A95DE: DMS=1, merged=1
Processing DMS assay UPI000003B052:  94%|██▊| 1458/1555 [02:43<00:09, 10.08it/s]UPI000003B052: DMS=1, merged=1
Processing DMS assay UPI000017DF81:  94%|██▊| 1458/1555 [02:44<00:09, 10.08it/s]UPI000017DF81: DMS=1, merged=1
Processing DMS assay UPI0001611034:  94%|██▊| 1460/1555 [02:44<00:09, 10.19it/s]UPI0001611034: DMS=3, merged=3
Processing DMS assay UPI0000202F63:  94%|██▊| 1460/1555 [02:44<00:09, 10.19it/s]UPI0000202F63: DMS=3, merged=3
Processing DMS assay UPI00000728B5:  94%|██▊| 1462/1555 [02:44<00:09,  9.98it/s]UPI00000728B5: DMS=1, merged=1
Processing DMS assay UPI0002A47704:  94%|██▊| 1462/1555 [02:44<00:09,  9.98it/s]UPI0002A47704: DMS=1, merged=1
Processing DMS assay UPI0000074451:  94%|██▊| 1464/1555 [02:44<00:09, 10.04it/s]UPI0000074451: DMS=1, merged=1
Processing DMS assay UPI000049DE01:  94%|██▊| 1464/1555 [02:44<00:09, 10.04it/s]UPI000049DE01: DMS=3, merged=3
Processing DMS assay UPI0000073639:  94%|██▊| 1466/1555 [02:44<00:08, 10.14it/s]UPI0000073639: DMS=1, merged=1
Processing DMS assay UPI0000E59EF5:  94%|██▊| 1466/1555 [02:44<00:08, 10.14it/s]UPI0000E59EF5: DMS=1, merged=1
Processing DMS assay UPI000023731A:  94%|██▊| 1468/1555 [02:44<00:08, 10.18it/s]UPI000023731A: DMS=1, merged=1
Processing DMS assay UPI0000000B17:  94%|██▊| 1468/1555 [02:45<00:08, 10.18it/s]UPI0000000B17: DMS=3, merged=3
Processing DMS assay UPI000013D56A:  95%|██▊| 1470/1555 [02:45<00:08, 10.18it/s]UPI000013D56A: DMS=1, merged=1
Processing DMS assay UPI00005D3C95:  95%|██▊| 1470/1555 [02:45<00:08, 10.18it/s]UPI00005D3C95: DMS=2, merged=2
Processing DMS assay UPI00000467E6:  95%|██▊| 1472/1555 [02:45<00:08, 10.13it/s]UPI00000467E6: DMS=1, merged=1
Processing DMS assay UPI00015386B3:  95%|██▊| 1472/1555 [02:45<00:08, 10.13it/s]UPI00015386B3: DMS=1, merged=1
Processing DMS assay UPI000006EA15:  95%|██▊| 1474/1555 [02:45<00:07, 10.17it/s]UPI000006EA15: DMS=1, merged=1
Processing DMS assay UPI00000715E9:  95%|██▊| 1474/1555 [02:45<00:07, 10.17it/s]UPI00000715E9: DMS=1, merged=1
Processing DMS assay UPI000013D4C2:  95%|██▊| 1476/1555 [02:45<00:07, 10.17it/s]UPI000013D4C2: DMS=1, merged=1
Processing DMS assay UPI0000160D96:  95%|██▊| 1476/1555 [02:45<00:07, 10.17it/s]UPI0000160D96: DMS=1, merged=1
Processing DMS assay UPI000006CF77:  95%|██▊| 1478/1555 [02:45<00:07, 10.18it/s]UPI000006CF77: DMS=1, merged=1
Processing DMS assay UPI000013DCB6:  95%|██▊| 1478/1555 [02:46<00:07, 10.18it/s]UPI000013DCB6: DMS=1, merged=1
Processing DMS assay UPI000015FD15:  95%|██▊| 1480/1555 [02:46<00:07, 10.14it/s]UPI000015FD15: DMS=1, merged=1
Processing DMS assay UPI0001823FDC:  95%|██▊| 1480/1555 [02:46<00:07, 10.14it/s]UPI0001823FDC: DMS=3, merged=3
Processing DMS assay UPI0000071834:  95%|██▊| 1482/1555 [02:46<00:07, 10.09it/s]UPI0000071834: DMS=1, merged=1
Processing DMS assay UPI000006FF0C:  95%|██▊| 1482/1555 [02:46<00:07, 10.09it/s]UPI000006FF0C: DMS=1, merged=1
Processing DMS assay UPI0000505465:  95%|██▊| 1484/1555 [02:46<00:07, 10.12it/s]UPI0000505465: DMS=2, merged=2
Processing DMS assay UPI0000E5B01A:  95%|██▊| 1484/1555 [02:46<00:07, 10.12it/s]UPI0000E5B01A: DMS=1, merged=1
Processing DMS assay UPI000045882C:  96%|██▊| 1486/1555 [02:46<00:06, 10.16it/s]UPI000045882C: DMS=1, merged=1
Processing DMS assay UPI0000031D01:  96%|██▊| 1486/1555 [02:46<00:06, 10.16it/s]UPI0000031D01: DMS=1, merged=1
Processing DMS assay UPI000020F9BB:  96%|██▊| 1488/1555 [02:46<00:06, 10.23it/s]UPI000020F9BB: DMS=1, merged=1
Processing DMS assay UPI00001AAC44:  96%|██▊| 1488/1555 [02:46<00:06, 10.23it/s]UPI00001AAC44: DMS=1, merged=1
Processing DMS assay UPI00024672CE:  96%|██▊| 1490/1555 [02:47<00:06, 10.23it/s]UPI00024672CE: DMS=2, merged=2
Processing DMS assay UPI000000DA9E:  96%|██▊| 1490/1555 [02:47<00:06, 10.23it/s]UPI000000DA9E: DMS=1, merged=1
Processing DMS assay UPI00001AE937:  96%|██▉| 1492/1555 [02:47<00:06, 10.18it/s]UPI00001AE937: DMS=3, merged=3
Processing DMS assay UPI00001285F3:  96%|██▉| 1492/1555 [02:47<00:06, 10.18it/s]UPI00001285F3: DMS=1, merged=1
Processing DMS assay UPI00001D822A:  96%|██▉| 1494/1555 [02:47<00:06,  9.99it/s]UPI00001D822A: DMS=1, merged=1
Processing DMS assay UPI0000052952:  96%|██▉| 1495/1555 [02:47<00:06,  9.98it/s]UPI0000052952: DMS=1, merged=1
Processing DMS assay UPI00004A3B76:  96%|██▉| 1496/1555 [02:47<00:05,  9.97it/s]UPI00004A3B76: DMS=1, merged=1

Processing DMS assay UPI0000164A41:  96%|██▉| 1496/1555 [02:47<00:05,  9.97it/s]UPI0000164A41: DMS=1, merged=1
Processing DMS assay UPI0000D62427:  96%|██▉| 1498/1555 [02:47<00:05, 10.09it/s]UPI0000D62427: DMS=1, merged=1
Processing DMS assay UPI000059DA57:  96%|██▉| 1498/1555 [02:47<00:05, 10.09it/s]UPI000059DA57: DMS=1, merged=1
Processing DMS assay UPI000012D193:  96%|██▉| 1500/1555 [02:48<00:05, 10.20it/s]UPI000012D193: DMS=1, merged=1
Processing DMS assay UPI0000DA5AF5:  96%|██▉| 1500/1555 [02:48<00:05, 10.20it/s]UPI0000DA5AF5: DMS=1, merged=1
Processing DMS assay UPI000000D72E:  97%|██▉| 1502/1555 [02:48<00:05, 10.29it/s]UPI000000D72E: DMS=1, merged=1
Processing DMS assay UPI000006E083:  97%|██▉| 1502/1555 [02:48<00:05, 10.29it/s]UPI000006E083: DMS=1, merged=1
Processing DMS assay UPI000004980B:  97%|██▉| 1504/1555 [02:48<00:04, 10.33it/s]UPI000004980B: DMS=1, merged=1
Processing DMS assay UPI000013C68E:  97%|██▉| 1504/1555 [02:48<00:04, 10.33it/s]UPI000013C68E: DMS=1, merged=1
Processing DMS assay UPI0000041E80:  97%|██▉| 1506/1555 [02:48<00:04, 10.30it/s]UPI0000041E80: DMS=1, merged=1
Processing DMS assay UPI0000073D24:  97%|██▉| 1506/1555 [02:48<00:04, 10.30it/s]UPI0000073D24: DMS=1, merged=1
Processing DMS assay UPI000012FE45:  97%|██▉| 1508/1555 [02:48<00:04, 10.25it/s]UPI000012FE45: DMS=2, merged=2
Processing DMS assay UPI00001A8223:  97%|██▉| 1508/1555 [02:48<00:04, 10.25it/s]UPI00001A8223: DMS=1, merged=1
Processing DMS assay UPI00001612A6:  97%|██▉| 1510/1555 [02:49<00:04, 10.18it/s]UPI00001612A6: DMS=1, merged=1
Processing DMS assay UPI000006D9E4:  97%|██▉| 1510/1555 [02:49<00:04, 10.18it/s]UPI000006D9E4: DMS=1, merged=1
Processing DMS assay UPI0000047F3B:  97%|██▉| 1512/1555 [02:49<00:04, 10.23it/s]UPI0000047F3B: DMS=1, merged=1
Processing DMS assay UPI000020B8EF:  97%|██▉| 1512/1555 [02:49<00:04, 10.23it/s]UPI000020B8EF: DMS=1, merged=1
Processing DMS assay UPI0000137078:  97%|██▉| 1514/1555 [02:49<00:04, 10.18it/s]UPI0000137078: DMS=1, merged=1
Processing DMS assay UPI0000246C98:  97%|██▉| 1514/1555 [02:49<00:04, 10.18it/s]UPI0000246C98: DMS=1, merged=1
Processing DMS assay UPI00001D82A6:  97%|██▉| 1516/1555 [02:49<00:03, 10.18it/s]UPI00001D82A6: DMS=1, merged=1
Processing DMS assay UPI0001533DAA:  97%|██▉| 1516/1555 [02:49<00:03, 10.18it/s]UPI0001533DAA: DMS=1, merged=1
Processing DMS assay UPI00000398BB:  98%|██▉| 1518/1555 [02:49<00:03, 10.14it/s]UPI00000398BB: DMS=1, merged=1
Processing DMS assay UPI0001E8F37E:  98%|██▉| 1518/1555 [02:49<00:03, 10.14it/s]UPI0001E8F37E: DMS=1, merged=1
Processing DMS assay UPI0000190820:  98%|██▉| 1520/1555 [02:50<00:03, 10.17it/s]UPI0000190820: DMS=1, merged=1
Processing DMS assay UPI000013DE67:  98%|██▉| 1520/1555 [02:50<00:03, 10.17it/s]UPI000013DE67: DMS=1, merged=1
Processing DMS assay UPI0000073FE5:  98%|██▉| 1522/1555 [02:50<00:03, 10.13it/s]UPI0000073FE5: DMS=1, merged=1
Processing DMS assay UPI0000073BBA:  98%|██▉| 1522/1555 [02:50<00:03, 10.13it/s]UPI0000073BBA: DMS=1, merged=1
Processing DMS assay UPI000041512B:  98%|██▉| 1524/1555 [02:50<00:03, 10.14it/s]UPI000041512B: DMS=1, merged=1
Processing DMS assay UPI000013EA1F:  98%|██▉| 1524/1555 [02:50<00:03, 10.14it/s]UPI000013EA1F: DMS=1, merged=1
Processing DMS assay UPI0000072D52:  98%|██▉| 1526/1555 [02:50<00:02, 10.17it/s]UPI0000072D52: DMS=1, merged=1
Processing DMS assay UPI00001FEDD8:  98%|██▉| 1526/1555 [02:50<00:02, 10.17it/s]UPI00001FEDD8: DMS=1, merged=1
Processing DMS assay UPI0000071E9E:  98%|██▉| 1528/1555 [02:50<00:02, 10.18it/s]UPI0000071E9E: DMS=1, merged=1
Processing DMS assay UPI0000201AC8:  98%|██▉| 1528/1555 [02:50<00:02, 10.18it/s]UPI0000201AC8: DMS=1, merged=1
Processing DMS assay UPI00017A6F19:  98%|██▉| 1530/1555 [02:51<00:02, 10.16it/s]UPI00017A6F19: DMS=1, merged=1
Processing DMS assay UPI0000070494:  98%|██▉| 1530/1555 [02:51<00:02, 10.16it/s]UPI0000070494: DMS=1, merged=1
Processing DMS assay UPI00006C19FA:  99%|██▉| 1532/1555 [02:51<00:02, 10.16it/s]UPI00006C19FA: DMS=1, merged=1
Processing DMS assay UPI000012ADEA:  99%|██▉| 1532/1555 [02:51<00:02, 10.16it/s]UPI000012ADEA: DMS=1, merged=1
Processing DMS assay UPI0000456F39:  99%|██▉| 1534/1555 [02:51<00:02, 10.23it/s]UPI0000456F39: DMS=1, merged=1
Processing DMS assay UPI00025A2DFB:  99%|██▉| 1534/1555 [02:51<00:02, 10.23it/s]UPI00025A2DFB: DMS=1, merged=1
Processing DMS assay UPI0000E06BD6:  99%|██▉| 1536/1555 [02:51<00:01, 10.25it/s]UPI0000E06BD6: DMS=1, merged=1
Processing DMS assay UPI0001573469:  99%|██▉| 1536/1555 [02:51<00:01, 10.25it/s]UPI0001573469: DMS=2, merged=2
Processing DMS assay UPI000002A38D:  99%|██▉| 1538/1555 [02:51<00:01, 10.02it/s]UPI000002A38D: DMS=1, merged=1
Processing DMS assay UPI000050BBEF:  99%|██▉| 1538/1555 [02:51<00:01, 10.02it/s]UPI000050BBEF: DMS=1, merged=1
Processing DMS assay UPI00001419CC:  99%|██▉| 1540/1555 [02:52<00:01, 10.03it/s]UPI00001419CC: DMS=1, merged=1
Processing DMS assay UPI0000074015:  99%|██▉| 1540/1555 [02:52<00:01, 10.03it/s]UPI0000074015: DMS=1, merged=1
Processing DMS assay UPI00001C2068:  99%|██▉| 1542/1555 [02:52<00:01, 10.06it/s]UPI00001C2068: DMS=1, merged=1
Processing DMS assay UPI00005788EA:  99%|██▉| 1542/1555 [02:52<00:01, 10.06it/s]UPI00005788EA: DMS=1, merged=1
Processing DMS assay UPI00006BFF57:  99%|██▉| 1544/1555 [02:52<00:01, 10.06it/s]UPI00006BFF57: DMS=8, merged=8
Processing DMS assay UPI000013D050:  99%|██▉| 1544/1555 [02:52<00:01, 10.06it/s]UPI000013D050: DMS=1, merged=1
Processing DMS assay UPI000011F17B:  99%|██▉| 1546/1555 [02:52<00:00, 10.03it/s]UPI000011F17B: DMS=2, merged=2
Processing DMS assay UPI000004064B:  99%|██▉| 1546/1555 [02:52<00:00, 10.03it/s]UPI000004064B: DMS=1, merged=1
Processing DMS assay UPI0000127E5B: 100%|██▉| 1548/1555 [02:52<00:00, 10.11it/s]UPI0000127E5B: DMS=1, merged=1
Processing DMS assay UPI00001BB2B9: 100%|██▉| 1548/1555 [02:52<00:00, 10.11it/s]UPI00001BB2B9: DMS=2, merged=2
Processing DMS assay UPI000008AB1D: 100%|██▉| 1550/1555 [02:53<00:00, 10.17it/s]UPI000008AB1D: DMS=1, merged=1
Processing DMS assay UPI0000456761: 100%|██▉| 1550/1555 [02:53<00:00, 10.17it/s]UPI0000456761: DMS=1, merged=1
Processing DMS assay UPI000015FEE1: 100%|██▉| 1552/1555 [02:53<00:00, 10.21it/s]UPI000015FEE1: DMS=1, merged=1
Processing DMS assay UPI000012CBC3: 100%|██▉| 1552/1555 [02:53<00:00, 10.21it/s]UPI000012CBC3: DMS=1, merged=1
Processing DMS assay UPI000019080B: 100%|██▉| 1554/1555 [02:53<00:00, 10.10it/s]UPI000019080B: DMS=1, merged=1
Processing DMS assay UPI000019080B: 100%|███| 1555/1555 [02:53<00:00,  8.96it/s]

In [9]:
!/n/groups/marks/users/aaron/pmhc/envs/dl_binder_design/bin/python PR/ProteinGym/proteingym/performance_clinical_benchmarks.py \
    --input_scoring_files_folder ./PR/.cache/ProteinGym/v1.2/zero_shot_clinical_indels_scores/merged_scores \
    --output_performance_file_folder ./PR/.cache/ProteinGym/v1.2/benchmarks \
    --clinical_reference_file_path ./ProteinGym/reference_files/clinical_indels.csv \
    --indel_mode \
    --config_file ./PR/config.json

Found 1555 genes in reference file
Evaluating 18 models
Pooled 2878 variants across 1555 genes
real -inf: 4  | true NaN: 297
real -inf: 0  | true NaN: 0
real -inf: 0  | true NaN: 0
real -inf: 0  | true NaN: 0
real -inf: 0  | true NaN: 0
real -inf: 0  | true NaN: 0
real -inf: 0  | true NaN: 0
real -inf: 0  | true NaN: 0
real -inf: 0  | true NaN: 0
real -inf: 0  | true NaN: 0
real -inf: 0  | true NaN: 0
real -inf: 0  | true NaN: 0
real -inf: 0  | true NaN: 0
real -inf: 0  | true NaN: 0
real -inf: 0  | true NaN: 0
real -inf: 0  | true NaN: 0
real -inf: 0  | true NaN: 104
real -inf: 0  | true NaN: 0

Summary results saved to ./PR/.cache/ProteinGym/v1.2/benchmarks/indels/AUC/Summary_performance_clinical_indels_AUC.csv
 Model_rank                 Model_name      Model type  Average_AUC  Num_variants
          1                PoET (200M)             MSA        0.931          2878
          2                    Provean             MSA        0.921          2878
          3 Tranception L no retrieval Single sequence        0.857          2878
          4              Tranception L             MSA        0.853          2878
          5              Tranception M             MSA        0.839          2878
          6 Tranception M no retrieval Single sequence        0.837          2878
          7        Hidden Markov Model             MSA        0.566          2581
          8                     Unirep Single sequence        0.460          2774
          9                   ProtGPT2 Single sequence        0.440          2878
         10                  Progen2 S Single sequence        0.432          2878
         11               Progen2 Base Single sequence        0.427          2878
         12                     RITA S Single sequence        0.414          2878
         13                  Progen2 L Single sequence        0.409          2878
         14                  Progen2 M Single sequence        0.406          2878
         15                 Progen2 XL Single sequence        0.405          2878
         16                     RITA M Single sequence        0.361          2878
         17                    RITA XL Single sequence        0.351          2878
         18                     RITA L Single sequence        0.345          2878

## Generate all the files required for completeness
1. Move all the scores I obtained to `/n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/model_scores/` after preprocessing (column names: mutated_sequence,PoET2_score)

dms_subs_output_dir = './PR/.cache/ProteinGym/zero_shot_substitutions_scores/PoET-2/'
dms_subs_dms_dir = "./PR/.cache/ProteinGym/DMS_ProteinGym_substitutions/"
dms_indels_output_dir = './PR/.cache/ProteinGym/zero_shot_indels_scores/PoET-2/'
dms_indels_dms_dir = "./PR/.cache/ProteinGym/DMS_ProteinGym_indels/"

clinical_subs_output_dir = './PR/.cache/ProteinGym/zero_shot_clinical_substitutions_scores/PoET-2'
clinical_subs_dms_dir = "./PR/.cache/ProteinGym/clinical_ProteinGym_substitutions"
clinical_indels_output_dir = "./PR/.cache/ProteinGym/zero_shot_clinical_indels_scores/PoET-2"
clinical_indels_dms_dir = "./PR/.cache/ProteinGym/clinical_ProteinGym_indels"

In [12]:
score_folder = '/n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/model_scores'

In [14]:
for score_file in glob.glob(dms_subs_output_dir + '*.csv'):
    score_df = pd.read_csv(score_file)
    dms_id = os.path.basename(score_file).removesuffix(".csv")
    dms_df = pd.read_csv(dms_subs_dms_dir + dms_id + ".csv")
    output_score = pd.concat([dms_df['mutated_sequence'].reset_index(drop=True),
                              score_df['PoET-2'].reset_index(drop=True)], axis=1)
    output_score.to_csv(score_folder + os.sep + "zero_shot_substitutions" + os.sep + "PoET2" + os.sep + dms_id + ".csv")

In [16]:
for score_file in glob.glob(dms_indels_output_dir + '*.csv'):
    score_df = pd.read_csv(score_file)
    dms_id = os.path.basename(score_file).removesuffix(".csv")
    dms_df = pd.read_csv(dms_indels_dms_dir + dms_id + ".csv")
    output_score = pd.concat([dms_df['mutated_sequence'].reset_index(drop=True),
                              score_df['PoET-2'].reset_index(drop=True)], axis=1)
    output_score.to_csv(score_folder + os.sep + "zero_shot_indels" + os.sep + "PoET2" + os.sep + dms_id + ".csv")

In [18]:
for score_file in glob.glob(clinical_subs_output_dir + '/*.csv'):
    score_df = pd.read_csv(score_file)
    dms_id = os.path.basename(score_file).removesuffix(".csv")
    dms_df = pd.read_csv(clinical_subs_dms_dir + os.sep + dms_id + ".csv")
    output_score = pd.concat([dms_df['mutated_sequence'].reset_index(drop=True),
                              score_df['PoET-2'].reset_index(drop=True)], axis=1)
    output_score.to_csv(score_folder + os.sep + "zero_shot_clinical_substitutions" + os.sep + "PoET2" + os.sep + dms_id + ".csv")

In [22]:
for score_file in glob.glob(clinical_indels_output_dir + '/*.csv'):
    score_df = pd.read_csv(score_file)
    dms_id = os.path.basename(score_file).removesuffix(".csv")
    dms_df = pd.read_csv(clinical_indels_dms_dir + os.sep + dms_id + ".csv")
    output_score = pd.concat([dms_df['mutated_sequence'].reset_index(drop=True),
                              score_df['PoET-2'].reset_index(drop=True)], axis=1)
    output_score.to_csv(score_folder + os.sep + "zero_shot_clinical_indels" + os.sep + "PoET2" + os.sep + dms_id + ".csv")

2. Merge all the scores

In [ ]:
!cd /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym2/
!/n/groups/marks/users/aaron/pmhc/envs/dl_binder_design/bin/python PR/ProteinGym/proteingym/merge.py \
    --DMS_assays_location ./PR/.cache/ProteinGym/DMS_ProteinGym_substitutions \
    --model_scores_location /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/model_scores/zero_shot_substitutions \
    --merged_scores_dir /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/model_scores/merged_scores/zero_shot_substitutions \
    --mutation_type substitutions \
    --dataset DMS \
    --DMS_reference_file ./ProteinGym/reference_files/DMS_substitutions.csv \
    --config_file ./PR/config.json

Processing DMS assay A0A140D2T1_ZIKV_Sourisseau_2019:   0%| | 0/217 [00:00<?, ?iA0A140D2T1_ZIKV_Sourisseau_2019: DMS=9576, merged=9576
Processing DMS assay A0A192B1T2_9HIV1_Haddox_2018:   0%| | 1/217 [00:29<1:47:09,A0A192B1T2_9HIV1_Haddox_2018: DMS=12577, merged=12577
Processing DMS assay A0A1I9GEU1_NEIME_Kennouche_2019:   1%| | 2/217 [00:43<1:13:A0A1I9GEU1_NEIME_Kennouche_2019: DMS=922, merged=922
Processing DMS assay A0A247D711_LISMN_Stadelmann_2021:   1%| | 3/217 [00:45<41:5A0A247D711_LISMN_Stadelmann_2021: DMS=1653, merged=1653
Processing DMS assay A0A2Z5U3Z0_9INFA_Doud_2016:   2%| | 4/217 [00:46<27:24,  7.A0A2Z5U3Z0_9INFA_Doud_2016: DMS=10715, merged=10715
Processing DMS assay A0A2Z5U3Z0_9INFA_Wu_2014:   2%| | 5/217 [00:56<29:33,  8.37A0A2Z5U3Z0_9INFA_Wu_2014: DMS=2350, merged=2350
Processing DMS assay A4_HUMAN_Seuma_2022:   3%| | 6/217 [00:59<23:00,  6.54s/it]A4_HUMAN_Seuma_2022: DMS=14811, merged=14811
Processing DMS assay A4D664_9INFA_Soh_2019:   3%| | 7/217 [01:14<33:24,  9.54s/iA4D664_9INFA_Soh_2019: DMS=14421, merged=14421
Processing DMS assay A4GRB6_PSEAI_Chen_2020:   4%| | 8/217 [01:29<39:17, 11.28s/A4GRB6_PSEAI_Chen_2020: DMS=5004, merged=5004
Processing DMS assay AACC1_PSEAI_Dandage_2018:   4%| | 9/217 [01:33<31:16,  9.02AACC1_PSEAI_Dandage_2018: DMS=1801, merged=1801
Processing DMS assay ACE2_HUMAN_Chan_2020:   5%| | 10/217 [01:35<23:27,  6.80s/iACE2_HUMAN_Chan_2020: DMS=2223, merged=2223
Processing DMS assay ADRB2_HUMAN_Jones_2020:   5%| | 11/217 [01:39<19:55,  5.80sADRB2_HUMAN_Jones_2020: DMS=7800, merged=7800
Processing DMS assay AICDA_HUMAN_Gajula_2014_3cycles:   6%| | 12/217 [01:45<20:3AICDA_HUMAN_Gajula_2014_3cycles: DMS=209, merged=209
Processing DMS assay AMFR_HUMAN_Tsuboyama_2023_4G3O:   6%| | 13/217 [01:46<15:07AMFR_HUMAN_Tsuboyama_2023_4G3O: DMS=2972, merged=2972
Processing DMS assay AMIE_PSEAE_Wrenbeck_2017:   6%| | 14/217 [01:48<12:37,  3.7AMIE_PSEAE_Wrenbeck_2017: DMS=6227, merged=6227
Processing DMS assay ANCSZ_Hobbs_2022:   7%|▏  | 15/217 [01:53<13:55,  4.14s/it]ANCSZ_Hobbs_2022: DMS=4670, merged=4670
Processing DMS assay ARGR_ECOLI_Tsuboyama_2023_1AOY:   7%| | 16/217 [01:58<14:45ARGR_ECOLI_Tsuboyama_2023_1AOY: DMS=1287, merged=1287
Processing DMS assay B2L11_HUMAN_Dutta_2010_binding-Mcl-1:   8%| | 17/217 [02:00B2L11_HUMAN_Dutta_2010_binding-Mcl-1: DMS=170, merged=170
Processing DMS assay BBC1_YEAST_Tsuboyama_2023_1TG0:   8%| | 18/217 [02:01<09:07BBC1_YEAST_Tsuboyama_2023_1TG0: DMS=2069, merged=2069
Processing DMS assay BCHB_CHLTE_Tsuboyama_2023_2KRU:   9%| | 19/217 [02:03<08:11BCHB_CHLTE_Tsuboyama_2023_2KRU: DMS=1572, merged=1572
Processing DMS assay BLAT_ECOLX_Deng_2012:   9%| | 20/217 [02:04<07:18,  2.22s/iBLAT_ECOLX_Deng_2012: DMS=4996, merged=4996
Processing DMS assay BLAT_ECOLX_Firnberg_2014:  10%| | 21/217 [02:08<09:03,  2.7BLAT_ECOLX_Firnberg_2014: DMS=4783, merged=4783
Processing DMS assay BLAT_ECOLX_Jacquier_2013:  10%| | 22/217 [02:12<10:04,  3.1BLAT_ECOLX_Jacquier_2013: DMS=989, merged=989
Processing DMS assay BLAT_ECOLX_Stiffler_2015:  11%| | 23/217 [02:14<08:34,  2.6BLAT_ECOLX_Stiffler_2015: DMS=4996, merged=4996
Processing DMS assay BRCA1_HUMAN_Findlay_2018:  11%| | 24/217 [02:18<10:03,  3.1BRCA1_HUMAN_Findlay_2018: DMS=1837, merged=1837
Processing DMS assay BRCA2_HUMAN_Erwood_2022_HEK293T:  12%| | 25/217 [02:22<11:1BRCA2_HUMAN_Erwood_2022_HEK293T: DMS=265, merged=265
Processing DMS assay C6KNH7_9INFA_Lee_2018:  12%| | 26/217 [02:24<09:29,  2.98s/C6KNH7_9INFA_Lee_2018: DMS=10754, merged=10754
Processing DMS assay CALM1_HUMAN_Weile_2017:  12%| | 27/217 [02:34<15:57,  5.04sCALM1_HUMAN_Weile_2017: DMS=1813, merged=1813
Processing DMS assay CAPSD_AAV2S_Sinai_2021:  13%|▏| 28/217 [02:36<12:45,  4.05sCAPSD_AAV2S_Sinai_2021: DMS=42328, merged=42328
Processing DMS assay CAR11_HUMAN_Meitlis_2020_gof:  13%|▏| 29/217 [03:20<50:05, CAR11_HUMAN_Meitlis_2020_gof: DMS=2374, merged=2374
Processing DMS assay CAR11_HUMAN_Meitlis_2020_lof:  14%|▏| 30/217 [03:24<39:07, CAR11_HUMAN_Meitlis_2020_lof: DMS=2395, merged=2395
Processing DMS assay CAS9_STRP1_Spencer_2017_positive:  14%|▏| 31/217 [03:28<31:CAS9_STRP1_Spencer_2017_positive: DMS=8117, merged=8117
Processing DMS assay CASP3_HUMAN_Roychowdhury_2020:  15%|▏| 32/217 [03:41<33:24,CASP3_HUMAN_Roychowdhury_2020: DMS=1567, merged=1567
Processing DMS assay CASP7_HUMAN_Roychowdhury_2020:  15%|▏| 33/217 [03:43<24:57,CASP7_HUMAN_Roychowdhury_2020: DMS=1680, merged=1680
Processing DMS assay CATR_CHLRE_Tsuboyama_2023_2AMI:  16%|▏| 34/217 [03:45<19:10CATR_CHLRE_Tsuboyama_2023_2AMI: DMS=1903, merged=1903
Processing DMS assay CBPA2_HUMAN_Tsuboyama_2023_1O6X:  16%|▏| 35/217 [03:46<14:5CBPA2_HUMAN_Tsuboyama_2023_1O6X: DMS=2068, merged=2068
Processing DMS assay CBS_HUMAN_Sun_2020:  17%|▏| 36/217 [03:48<11:55,  3.95s/it]CBS_HUMAN_Sun_2020: DMS=7217, merged=7217
Processing DMS assay CBX4_HUMAN_Tsuboyama_2023_2K28:  17%|▏| 37/217 [03:55<14:39CBX4_HUMAN_Tsuboyama_2023_2K28: DMS=2282, merged=2282
Processing DMS assay CCDB_ECOLI_Adkar_2012:  18%|▏| 38/217 [03:57<11:53,  3.99s/CCDB_ECOLI_Adkar_2012: DMS=1176, merged=1176
Processing DMS assay CCDB_ECOLI_Tripathi_2016:  18%|▏| 39/217 [03:59<09:29,  3.2CCDB_ECOLI_Tripathi_2016: DMS=1663, merged=1663
Processing DMS assay CCR5_HUMAN_Gill_2023:  18%|▏| 40/217 [04:00<08:01,  2.72s/iCCR5_HUMAN_Gill_2023: DMS=6137, merged=6137
Processing DMS assay CD19_HUMAN_Klesmith_2019_FMC_singles:  19%|▏| 41/217 [04:05CD19_HUMAN_Klesmith_2019_FMC_singles: DMS=3761, merged=3761
Processing DMS assay CP2C9_HUMAN_Amorosi_2021_abundance:  19%|▏| 42/217 [04:09<1CP2C9_HUMAN_Amorosi_2021_abundance: DMS=6370, merged=6370
Processing DMS assay CP2C9_HUMAN_Amorosi_2021_activity:  20%|▏| 43/217 [04:16<12CP2C9_HUMAN_Amorosi_2021_activity: DMS=6142, merged=6142
Processing DMS assay CSN4_MOUSE_Tsuboyama_2023_1UFM:  20%|▏| 44/217 [04:21<13:47CSN4_MOUSE_Tsuboyama_2023_1UFM: DMS=3295, merged=3295
Processing DMS assay CUE1_YEAST_Tsuboyama_2023_2MYX:  21%|▏| 45/217 [04:24<11:36CUE1_YEAST_Tsuboyama_2023_2MYX: DMS=1580, merged=1580
Processing DMS assay D7PM05_CLYGR_Somermeyer_2022:  21%|▏| 46/217 [04:25<09:23, D7PM05_CLYGR_Somermeyer_2022: DMS=24515, merged=24515
Processing DMS assay DLG4_HUMAN_Faure_2021:  22%|▏| 47/217 [04:41<20:12,  7.13s/DLG4_HUMAN_Faure_2021: DMS=6976, merged=6976
Processing DMS assay DLG4_RAT_McLaughlin_2012:  22%|▏| 48/217 [04:50<21:17,  7.5DLG4_RAT_McLaughlin_2012: DMS=1576, merged=1576
Processing DMS assay DN7A_SACS2_Tsuboyama_2023_1JIC:  23%|▏| 49/217 [04:52<16:56DN7A_SACS2_Tsuboyama_2023_1JIC: DMS=1008, merged=1008
Processing DMS assay DNJA1_HUMAN_Tsuboyama_2023_2LO1:  23%|▏| 50/217 [04:54<12:5DNJA1_HUMAN_Tsuboyama_2023_2LO1: DMS=2264, merged=2264
Processing DMS assay DOCK1_MOUSE_Tsuboyama_2023_2M0Y:  24%|▏| 51/217 [04:55<10:2DOCK1_MOUSE_Tsuboyama_2023_2M0Y: DMS=2915, merged=2915
Processing DMS assay DYR_ECOLI_Nguyen_2023:  24%|▏| 52/217 [04:57<08:58,  3.27s/DYR_ECOLI_Nguyen_2023: DMS=2916, merged=2916
Processing DMS assay DYR_ECOLI_Thompson_2019:  24%|▏| 53/217 [05:00<08:07,  2.97DYR_ECOLI_Thompson_2019: DMS=2363, merged=2363
Processing DMS assay ENV_HV1B9_DuenasDecamp_2016:  25%|▏| 54/217 [05:02<07:18,  ENV_HV1B9_DuenasDecamp_2016: DMS=375, merged=375
Processing DMS assay ENV_HV1BR_Haddox_2016:  25%|▎| 55/217 [05:03<06:09,  2.28s/ENV_HV1BR_Haddox_2016: DMS=12863, merged=12863
Processing DMS assay ENVZ_ECOLI_Ghose_2023:  26%|▎| 56/217 [05:18<16:30,  6.15s/ENVZ_ECOLI_Ghose_2023: DMS=1121, merged=1121
Processing DMS assay EPHB2_HUMAN_Tsuboyama_2023_1F0M:  26%|▎| 57/217 [05:20<12:3EPHB2_HUMAN_Tsuboyama_2023_1F0M: DMS=1960, merged=1960
Processing DMS assay ERBB2_HUMAN_Elazar_2016:  27%|▎| 58/217 [05:21<10:06,  3.82ERBB2_HUMAN_Elazar_2016: DMS=326, merged=326
Processing DMS assay ESTA_BACSU_Nutschel_2020:  27%|▎| 59/217 [05:23<08:05,  3.0ESTA_BACSU_Nutschel_2020: DMS=2172, merged=2172
Processing DMS assay F7YBW8_MESOW_Ding_2023:  28%|▎| 60/217 [05:25<07:13,  2.76sF7YBW8_MESOW_Ding_2023: DMS=7922, merged=7922
Processing DMS assay F7YBW8_MESOW_Aakre_2015:  28%|▎| 61/217 [05:30<08:50,  3.40F7YBW8_MESOW_Aakre_2015: DMS=9192, merged=9192
Processing DMS assay FECA_ECOLI_Tsuboyama_2023_2D1U:  29%|▎| 62/217 [05:35<10:20FECA_ECOLI_Tsuboyama_2023_2D1U: DMS=1886, merged=1886

Processing DMS assay FKBP3_HUMAN_Tsuboyama_2023_2KFV:  29%|▎| 63/217 [05:37<08:2FKBP3_HUMAN_Tsuboyama_2023_2KFV: DMS=1237, merged=1237
Processing DMS assay GAL4_YEAST_Kitzman_2015:  29%|▎| 64/217 [05:38<06:53,  2.70GAL4_YEAST_Kitzman_2015: DMS=1195, merged=1195
Processing DMS assay GCN4_YEAST_Staller_2018:  30%|▎| 65/217 [05:40<06:29,  2.56GCN4_YEAST_Staller_2018: DMS=2638, merged=2638
Processing DMS assay GDIA_HUMAN_Silverstein_2021:  30%|▎| 66/217 [05:43<06:44,  GDIA_HUMAN_Silverstein_2021: DMS=1154, merged=1154
Processing DMS assay GFP_AEQVI_Sarkisyan_2016:  31%|▎| 67/217 [05:45<05:59,  2.3Note: Protriever scored 2000/51714 mutants for GFP_AEQVI_Sarkisyan_2016; rest left as NaN.
GFP_AEQVI_Sarkisyan_2016: DMS=51714, merged=51714
Processing DMS assay GLPA_HUMAN_Elazar_2016:  31%|▎| 68/217 [06:20<30:15, 12.19sGLPA_HUMAN_Elazar_2016: DMS=245, merged=245
Processing DMS assay GRB2_HUMAN_Faure_2021:  32%|▎| 69/217 [06:21<21:42,  8.80s/Note: Protriever scored 2000/63366 mutants for GRB2_HUMAN_Faure_2021; rest left as NaN.
GRB2_HUMAN_Faure_2021: DMS=63366, merged=63366
Processing DMS assay HCP_LAMBD_Tsuboyama_2023_2L6Q:  32%|▎| 70/217 [07:00<43:42,HCP_LAMBD_Tsuboyama_2023_2L6Q: DMS=1040, merged=1040
Processing DMS assay HECD1_HUMAN_Tsuboyama_2023_3DKM:  33%|▎| 71/217 [07:01<31:2HECD1_HUMAN_Tsuboyama_2023_3DKM: DMS=5586, merged=5586
Processing DMS assay HEM3_HUMAN_Loggerenberg_2023:  33%|▎| 72/217 [07:04<24:13, HEM3_HUMAN_Loggerenberg_2023: DMS=5689, merged=5689
Processing DMS assay HIS7_YEAST_Pokusaeva_2019:  34%|▎| 73/217 [07:09<20:17,  8.

In [ ]:
!/n/groups/marks/users/aaron/pmhc/envs/dl_binder_design/bin/python PR/ProteinGym/proteingym/merge.py \
    --DMS_assays_location ./PR/.cache/ProteinGym/DMS_ProteinGym_indels \
    --model_scores_location /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/model_scores/zero_shot_indels \
    --merged_scores_dir /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/model_scores/merged_scores/zero_shot_indels \
    --mutation_type indels \
    --dataset DMS \
    --DMS_reference_file ./ProteinGym/reference_files/DMS_indels.csv \
    --config_file ./PR/config.json

In [ ]:
!/n/groups/marks/users/aaron/pmhc/envs/dl_binder_design/bin/python PR/ProteinGym/proteingym/merge.py \
    --DMS_assays_location ./PR/.cache/ProteinGym/clinical_ProteinGym_substitutions \
    --model_scores_location /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/model_scores/zero_shot_clinical_substitutions \
    --merged_scores_dir /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/model_scores/merged_scores/zero_shot_clinical_substitutions \
    --mutation_type substitutions \
    --dataset clinical \
    --DMS_reference_file ./ProteinGym/reference_files/clinical_substitutions.csv \
    --config_file ./PR/config.json

In [ ]:
!/n/groups/marks/users/aaron/pmhc/envs/dl_binder_design/bin/python PR/ProteinGym/proteingym/merge.py \
    --DMS_assays_location ./PR/.cache/ProteinGym/clinical_ProteinGym_indels \
    --model_scores_location /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/model_scores/zero_shot_clinical_indels \
    --merged_scores_dir /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/model_scores/merged_scores/zero_shot_clinical_indels \
    --mutation_type indels \
    --dataset clinical \
    --DMS_reference_file ./ProteinGym/reference_files/clinical_indels.csv \
    --config_file ./PR/config.json